### ISSUE TITLE
Using Node 11 throws TypeError: Cannot redefine property: pseudoRandomBytes

### ISSUE THREAD

**Issue by davesag** [sequelize/sequelize#10073]
## What are you doing?

Updated to use Node 11 and previously working code no longer works.

## What do you expect to happen?

Stuff to work

## What is actually happening?

The dependency `shimmer`,  which is itself a dependency of `cls-bluebird@2.1.0`, does not work under Node 11.0.0.  Throws

    TypeError: Cannot redefine property: pseudoRandomBytes
      at Function.defineProperty (<anonymous>)
      at defineProperty (/Users/davesag/src/my-project/node_modules/shimmer/index.js:14:10)

```
npm ls shimmer
├─┬ continuation-local-storage@3.2.1
│ ├─┬ async-listener@0.6.9
│ │ └── shimmer@1.2.0 
│ └─┬ emitter-listener@1.1.2
│   └── shimmer@1.2.0  deduped
└─┬ sequelize@4.41.0
  └─┬ cls-bluebird@2.1.0
    └── shimmer@1.2.0  deduped
```
__Sequelize version:__ 4.41.0
__Tested with latest release:__ Yes 4.41.0

**Comment by sushantdhiman** [comment]
We can't solve this at Sequelize level, can we? I am tagging this as dependency issue. Please report this issue to related dependencies which are throwing this error so it can be fixed

**Comment by SimonSchick** [comment]
Can you provide a minimal repro for this? I don't get this error.

**Comment by SimonSchick** [comment]
Ah, this was fixed: https://github.com/othiym23/async-listener/commit/e0c269a39c16892c2402b06f398201956b905033

**Comment by zatziky** [comment]
Is there anything else I need to change? The issue is not fixed for me and I'm using `v11.2.0`?

**Comment by SimonSchick** [comment]
Have you made sure to update your dependency tree?
