### ISSUE TITLE
JSONB value query generates invalid SQL with quoteIdentifiers: false

### ISSUE THREAD

**Issue by lmac6350** [sequelize/sequelize#10234]
## What are you doing?
I query JSONB value:

```
const Sequelize = require('sequelize');
const sequelize = new Sequelize('postgres', 'someuser', 'pwd', {
    host: 'localhost',    dialect: 'postgres',    modelPaths: [__dirname + '/xx',],
    quoteIdentifiers: false
});
const Test = sequelize.define('test', {name: Sequelize.STRING,  data: Sequelize.JSONB});
sequelize.sync()
    .then(() => Test.create({
        name: 'abc',
        data: {color: 'red'}
    }, {logging: console.log}))
    .then(() =>
        Test.findAll({where: {data: {color: 'red'}}, logging: console.log}));
```

## What do you expect to happen?
_I expect the query to find the one record_

## What is actually happening?
_Error because of invalid SQL_

_Output, either JSON or SQL_
```
SELECT id, name, data, createdAt, updatedAt FROM tests AS test WHERE ("test.data"#>>'{color}') = 'red';
Error: column "test.data" does not exist
```
When I remove the double quotes the sql query is fine.
When I remove the the `test` prefix of the `data` column the sql query is also fine.

__Dialect:__ postgres
__Dialect version:__ pg@7.5.0
__Database version:__ 10
__Sequelize version:__ 4.41.0
__Tested with latest release:__ No

**Comment by sushantdhiman** [comment]
This is because of `quoteIdentifiers: false`

**Comment by lmac6350** [comment]
Do you mean that JSONB query is not expected to work when `quoteIdentifiers` is set to false?
I don't want and can not set it to true.

**Comment by sushantdhiman** [comment]
Have you tried master, I thing this has been fixed in master?

**Comment by lmac6350** [comment]
I've tried master (5.0.0-beta.14) right now. 
Unfortunately it is not fixed there.

**Comment by sushantdhiman** [comment]
We only quote Postgres known words in v5 so this should not happen, odd

**Comment by ephys** [comment]
We are [deprecating `quoteIdentifiers`](https://github.com/sequelize/sequelize/pull/15879) and planning to remove it, so bugs caused by it won't be fixed
