### ISSUE TITLE
Setting transaction isolation level does not work for SQL Server 

### ISSUE THREAD

**Issue by vaidasml** [sequelize/sequelize#10361]
## What are you doing?

Setting transaction isolation level to `REPEATABLE READ` for mssql dialect.

```js
.sequelize.transaction(
        { isolationLevel: Sequelize.Transaction.ISOLATION_LEVELS.REPEATABLE_READ },
)
```

## What do you expect to happen?

Transaction to be executed under `REPEATABLE READ` isolation level.

## What is actually happening?

Transaction runs on default `READ COMMITED` isolation level.

__Dialect:__ mssql
__Sequelize version:__ 4.38.0
__Tested with latest release:__ No 

## Root Cause

1. Sequalize isolation level constants are defined as:

```js
  static get ISOLATION_LEVELS() {
    return {
      READ_UNCOMMITTED: 'READ UNCOMMITTED',
      READ_COMMITTED: 'READ COMMITTED',
      REPEATABLE_READ: 'REPEATABLE READ',
      SERIALIZABLE: 'SERIALIZABLE'
    };
```

https://github.com/sequelize/sequelize/blob/6b1ff3b1320fed5a636a1040eaaaed1d1830b980/lib/transaction.js#L247

2. Sequalize mssql dialect does a Sequalize isolation level mapping to underlying driver's isolation level mapping like this:

```js
this.options.transaction.name, connection.lib.ISOLATION_LEVEL[this.options.isolationLevel]);
```

https://github.com/sequelize/sequelize/blob/0f0255eed3d88efb179a47fe7763b7309517428a/lib/dialects/mssql/query.js#L72

3. Driver (Tedious) defines `connection.lib.ISOLATION_LEVEL` like:

```js
const ISOLATION_LEVEL = module.exports.ISOLATION_LEVEL = {
  NO_CHANGE: 0x00,
  READ_UNCOMMITTED: 0x01,
  READ_COMMITTED: 0x02,
  REPEATABLE_READ: 0x03,
  SERIALIZABLE: 0x04,
  SNAPSHOT: 0x05
};
```

https://github.com/tediousjs/tedious/blob/c22c894d887797fc0062a07b68ffaad9b3a06e72/src/transaction.js#L18

4. Setting Sequalize isolation level using constant `Sequelize.Transaction.ISOLATION_LEVELS.REPEATABLE_READ` results in the lookup of an isolation level in Tedious driver isolation level definition using key `REPEATABLE READ` (*mind the missing underscore*). It is not present (only key with underscore exists), so as a result default (`READ COMMITED`) isolation level is used. This holds true for other isolation levels having more than one word in their name (`READ UNCOMMITTED`, `READ COMMITTED`)

**Comment by eseliger** [comment]
seems legit, probably the `get ISOLATION_LEVELS` should ask the dialect for a mapping, defaulting to the previous behavior and being overwritten by mssql dialect 🤔

**Comment by alejandrogkl** [comment]
this issue is also happening in v3.24.3.
i am using 

```isolationLevel: Sequelize.Transaction.ISOLATION_LEVELS.READ_UNCOMMITTED```

a two word name :)
do you plan to solve this issue any time soon?

**Comment by thomazfeitoza** [comment]
This also happens with MySQL. It's default isolation level is REPEATABLE_READ but when i try to use something different it just not works.

I realized this happens because the "SET SESSION TRANSACTION ISOLATION LEVEL" statement should be executed before "START TRANSACTION". According to [this link](https://dev.mysql.com/doc/refman/5.7/en/set-transaction.html) you can't change a transaction isolation level after it already started.

Don't know if this is the same problem that occurs in MSSQL.

**Comment by kasora** [comment]
Same here

**Comment by kasora** [comment]
Just a hack...
`
      let tempTransaction = await sequelize.transaction();
      await sequelize.query(`COMMIT;`, { transaction: tempTransaction });
      await sequelize.query(`SET SESSION TRANSACTION ISOLATION LEVEL ${transactionLevel};`, { transaction: tempTransaction });
      await sequelize.query(`START TRANSACTION;`, { transaction: tempTransaction });
`

**Comment by misos1** [comment]
Another problem here is that seems once you set session transaction isolation level it will be here permanently for particular sequelize connection not only for current sequelize "session" (or transaction) because sequelize uses connection pool and reuses connections for its "sessions" but for mysql session means particular sequelize connection. Better would be "SET TRANSACTION ISOLATION LEVEL". Or to properly "isolate" sequelize "sessions".

Example demonstrating this:
``` node.js
await sequelize.transaction(async function(transaction)
{
	// Executing (9101e35d-e571-491b-8fc3-c03c6fed1811): START TRANSACTION;
	console.log((await sequelize.query("SELECT @@TX_ISOLATION;", { type: sequelize.QueryTypes.SELECT, transaction }))[0]["@@TX_ISOLATION"]);
	// Executing (9101e35d-e571-491b-8fc3-c03c6fed1811): SELECT @@TX_ISOLATION;
	// REPEATABLE-READ
	await sequelize.query("SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;", { transaction });
	// Executing (9101e35d-e571-491b-8fc3-c03c6fed1811): SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	console.log((await sequelize.query("SELECT @@TX_ISOLATION;", { type: sequelize.QueryTypes.SELECT, transaction }))[0]["@@TX_ISOLATION"]);
	// Executing (9101e35d-e571-491b-8fc3-c03c6fed1811): SELECT @@TX_ISOLATION;
	// READ-UNCOMMITTED
	await sequelize.transaction(async function(transaction)
	{
		// Executing (a8acc202-5d4e-4d7d-ba28-f5ac0378333e): START TRANSACTION;
		console.log((await sequelize.query("SELECT @@TX_ISOLATION;", { type: sequelize.QueryTypes.SELECT, transaction }))[0]["@@TX_ISOLATION"]);
		// Executing (a8acc202-5d4e-4d7d-ba28-f5ac0378333e): SELECT @@TX_ISOLATION;
		// REPEATABLE-READ
		// good as we started new transaction before was first finished we forced sequelize to use new connection so we still have repeatable read
		await sequelize.query("SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;", { transaction });
		// Executing (a8acc202-5d4e-4d7d-ba28-f5ac0378333e): SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
		console.log((await sequelize.query("SELECT @@TX_ISOLATION;", { type: sequelize.QueryTypes.SELECT, transaction }))[0]["@@TX_ISOLATION"]);
		// Executing (a8acc202-5d4e-4d7d-ba28-f5ac0378333e): SELECT @@TX_ISOLATION;
		// READ-UNCOMMITTED
	});
	// Executing (a8acc202-5d4e-4d7d-ba28-f5ac0378333e): COMMIT;
	// Executing (9101e35d-e571-491b-8fc3-c03c6fed1811): COMMIT;
});
await sequelize.transaction(async function(transaction)
{
	// Executing (494a41f6-4fe9-4710-9c52-ab016d4d6378): START TRANSACTION;
	console.log((await sequelize.query("SELECT @@TX_ISOLATION;", { type: sequelize.QueryTypes.SELECT, transaction }))[0]["@@TX_ISOLATION"]);
	// Executing (494a41f6-4fe9-4710-9c52-ab016d4d6378): SELECT @@TX_ISOLATION;
	// READ-UNCOMMITTED
	// so why we have read uncommitted in new session 494a41f6-4fe9-4710-9c52-ab016d4d6378? probably was reused one of above connections
	// Executing (494a41f6-4fe9-4710-9c52-ab016d4d6378): COMMIT;
});
```

**Comment by poldridge** [comment]
The OP is describing an issue that is only relevant for mssql. Setting isolation level in mysql/maria has been fixed in 5.19.6 @thomazfeitoza , @kasora , @misos1 .

This is still an issue for mssql.

**Comment by dsbert** [comment]
I'm running an older version of 5 and hit this bug. Has this been corrected in any newer versions?

**Comment by dsbert** [comment]
Maybe I answered my own question - even if this is fixed, it looks like the isolation level is not being set at all for MSSQL according to this code.

https://github.com/sequelize/sequelize/blob/41237ae1ef63d2f3258dc0f69a926c4a96647ff0/lib/dialects/mssql/query-generator.js#L764

**Comment by muakdag** [comment]
The issue still exists in MSSQL with Sequelize 6.37.4 and Tedious 18.6.1. Any News?
