### ISSUE TITLE
tedious deprecated The "config.userName"

### ISSUE THREAD

**Issue by ycxfun** [sequelize/sequelize#10377]
tedious deprecated The "config.userName" property is deprecated and future tedious versions will no longer support it. Please switch to using the new "config.authentication" property instead.

tedious deprecated The "config.password" property is deprecated and future tedious versions will no longer support it. Please switch to using the new "config.authentication" property instead.

tedious deprecated The default value for `options.encrypt` will change from `false` to `true`. Please pass `false` explicitly if you want to retain current behaviour.

**Comment by wKovacs64** [comment]
For reference:

https://github.com/tediousjs/tedious/commit/6170d19
https://tediousjs.github.io/tedious/api-connection.html#function_newConnection

**Comment by sushantdhiman** [comment]
Fixed by https://github.com/sequelize/sequelize/pull/10494

**Comment by LucianHij** [comment]
I do no see how is this fixed. I installed sequalize beta 5. I installed tedious@6. But i am still getting those warnings regardin `tedious deprecated`.
