### ISSUE TITLE
Ability to disable connection pooling

### ISSUE THREAD

**Issue by gabegorelick** [sequelize/sequelize#10424]
## What are you doing?
Disabling sequelize's connection pool is a common request. Normally, [this would cause huge amounts of connection overhead](https://github.com/sequelize/sequelize/issues/8468#issuecomment-431599221), but often times users need to prioritize other concerns and so are willing to make that sacrifice (#8468). 

Also, having a local connection pool may not be needed, and may even be counterproductive, if one is running an external connection pool like PgBouncer. 

Currently, the best method to disable the connection pool is [this](https://github.com/sequelize/sequelize/issues/8468#issuecomment-430821770):
```js
Sequelize.addHook('afterInit', function(sequelize) {
  sequelize.options.handleDisconnects = false;

  // Disable pool completely
  sequelize.connectionManager.pool.clear();
  sequelize.connectionManager.pool = null;
  sequelize.connectionManager.getConnection = function getConnection() {
    return this._connect(sequelize.config);
  };
  sequelize.connectionManager.releaseConnection = function releaseConnection(connection) {
    return this._disconnect(connection);
  };
})
```

## What do you expect to happen?
An option like `pool: false`.

Sequelize used to support this, but it was removed in #5914 in favor of setting `pool.max` to `1`. But setting max pool size to 1 is not the same as disabling pooling.

__Dialect:__ any
__Dialect version:__ any
__Database version:__ any
__Sequelize version:__ master
__Tested with latest release:__ yes

**Comment by john-landgrave** [comment]
I have been running into the need for the same thing. Basically, connections were lingering waaay too long and I was constantly running into the connection limit on a AWS RDS small db (for our staging environment). It is worth noting that I had to modify things a little from the provided snippet:

```
Sequelize.addHook('afterInit', function (sequelize) {
  sequelize.options.handleDisconnects = false;

  // Disable pool completely
  sequelize.connectionManager.pool.destroyAllNow();
  sequelize.connectionManager.pool = null;
  sequelize.connectionManager.getConnection = function getConnection() {
    return this._connect(sequelize.config);
  };
  sequelize.connectionManager.releaseConnection = function releaseConnection(connection) {
    return this._disconnect(connection);
  };
})
```

I changed `clear()` to `destroyAllNow()` because clear wasn't a method?

**Comment by brandonw** [comment]
I ended up abandoning this approach, because eliminating the pooling of connections had a very noticeable performance impact, even using pgbouncer.

**Comment by slifty** [comment]
I just wanted to offer my use case for this feature: integration tests.  Jest will hang unless DB connections close; I was hoping to disable connection pooling entirely when running tests so that connections close immediately after a given query is run.

**Comment by rsaphala** [comment]
any updates on this?

**Comment by intellix** [comment]
We're constantly getting "ResourceRequest Timed Out" when doing heavy API calls or when the site gets slashdotted. After installing pgbouncer I thought the problem would be solved but it seems the issue is still generic-pool trying to create another connection when we already have a single connection as needed.

This was the secret sauce and thanks for the workaround :) Would love to get this

**Comment by sdemontfort** [comment]
A heads up to all who are considering using this code to remove Sequelize connection pooling. We have used this approach in production, as we use PgBouncer to do the pooling on our nodes. 
However, we hit an issue. Sequelize does some meta table lookups (at least for Postgres) on **every connection** when pooling is disabled. This won't be a problem for you if your `pg_class` and `pg_type` tables are small, but we have a lot of tables and so they've become quite big.

We're considering keeping pooling from Sequelize -> PgBouncer as this also reduces overhead from our application, by not needing to open a new TCP connection (plus run the expensive meta table lookups) every time we run a query .

**Comment by theoephraim** [comment]
anyone have any updates or tips on this topic?
I have set up pgbouncer in front of my database, but I'm very unclear on what would be the optimal pool settings for sequelize in this scenario.

**Comment by mrdulin** [comment]
same issue. Besides, there is a question: https://stackoverflow.com/questions/63263087/whats-the-difference-between-orm-query-builder-library-connection-pool-size-and

**Comment by sdemontfort** [comment]
In response to the above, we've been using Sequelize with the above overrides in production for over 6 months now, in front of PgBouncer. The pooling settings aren't relevant any more because they aren't used with the above overrides.
We also ended up overriding a particular method (`_refreshDynamicOIDs`) to ensure Sequelize doesn't attempt to do a large meta-table query before the actual requested query is run.

If you do however want to enable Sequelize's pooling infront of Pgbouncer, _this may make sense._ Some benefits of doing so might be:
- Your application (e.g. a NodeJs service) will hold open the TCP connections to the PgBouncer container if Sequelize pooling is enabled, which _might_ mean less DNS lookups from your service to PgBouncer. Which, even if you're using a DNS to access PgBouncer in a Docker container _can_ incur some latency
- No need to hack around in the current implementation of Sequelize library

Some negatives of doing so:
- You'll lose some of the control that PgBouncer enables around TCP_KEEP_ALIVES etc, as Sequelize will use it's settings to keep connections open to PgBouncer, etc. Using both also means more moving parts for debugging connection issues

**Comment by pankajtiwary** [comment]
Dear All, I am using Sequelize 5.22.3 and have found very strange problem. I am also using RDS Postgres as database.
Whenever, I add connection pool setting in my sequelize configuration, It opens of hundreds of connections and that goes till 3000 connections. I have read that, there is some bug in connection pool which was later resolved.
I am just wondering if anyone has got this earlier and any solution or work around?
Thanks in Advance

**Comment by rbulmer55** [comment]
I am using sequelize in serverless lambda functions and connection initialization takes over a second. I'm guessing the pool contributes to this, If there was a way to disable pooling that might help the initialization times for serverless functions. It might be a more common use case as people start moving systems over to serverless architecture. (using postgres and Aurora serverless). 

Each lambda that spins up only needs one connection, I'm going to set the max pool size to one for now to see if this improves the performance. But hopefully I'm onto a strong use case for disabling pools again in sequelize.

**Comment by gsogol** [comment]
We have the same issue and are trying to set the max connection to 1 and using RDS Proxy and currently in process to see but seeing the exact same issue, connections through the roof. #YouHadOneJob :(

**Comment by aaronbean** [comment]
We didn't notice it in our low-traffic testing environment, but once we pushed our new codebase using the latest version of Sequelize (it was running 3.30.x previously), we saw the number of connections skyrocket, to the point where we got a `SequelizeConnectionError: remaining connection slots are reserved for non-replication superuser connections` error message.  We have set our pool parameters in every which way we can think of, but not matter what, it just keeps opening new connections and doesn't close the old ones.  We're running out of ideas!

**Comment by gsogol** [comment]
Still the same for us. It's unfortunate and we as well are out of options. RDS proxy does not work with prepared statements which Sequelize uses (as well as most ORMs) but what's the point of having those pool settings when setting max to 1 creates over 1500 for us still. 🤦🏻‍♂️

**Comment by intellix** [comment]
not sure if the above workaround still works but it looks like SequelizePool is quite deep in the code and everything goes through it. 

The documentation gives a good write-up and example of using the pool with AWS Lambda: https://sequelize.org/docs/v6/other-topics/aws-lambda/

I think having a connection pool is pretty much always the case if you're using Postgres cause the connection management is awful without it. Does anyone have any similar advice for how best to handle application pooling when using something like pgBouncer?

I'm looking at both my database and pgBouncer (pooler) and it's basically full of idle connections (98% idle) and I think it's a misconfiguration of sequelize-pool.

I can see that since the last time I looked there's now a **maxUses** option. Would disabling application pooling essentially be setting that to 1? So a connection is acquired and then released after it's use.

**Comment by ephys** [comment]
After diving in the pool source code, I am pretty sure that you can achieve your goals with the existing configuration options:

- If you want connections to only be used once, but allow multiple concurrent connections, set `maxUses` to 1 and `max` to `Infinity`
- If you want a single connection, set `max` to 1

Thanks @intellix for pointing `maxUses` out

**Comment by jedwards1211** [comment]
@ephys if we use `maxUses: 1` will Sequelize perform the meta table lookups @sdemontfort mentioned for every new connection?

> Sequelize does some meta table lookups (at least for Postgres) on every connection when pooling is disabled. This won't be a problem for you if your pg_class and pg_type tables are small, but we have a lot of tables and so they've become quite big.

**Comment by ephys** [comment]
It is still an issue yes, the OID map refresh is called every time a connection is established

**Comment by jedwards1211** [comment]
Interestingly depesz recommends using both an external connection pool and an application-local connection pool in this article on pgBouncer: https://www.depesz.com/2012/12/02/what-is-the-point-of-bouncing/

So maybe there's not so much of a need to disable Sequelize's connection pooling when working with an external connection pool.
