### ISSUE TITLE
TypeError: Cannot read property 'databaseVersion' of undefined

### ISSUE THREAD

**Issue by williamoliveira** [sequelize/sequelize#10443]
I am getting this error intermittently, I dont have a minimum code example as I have no idea why it happens

```
TypeError: Cannot read property 'databaseVersion' of undefined
       at ConnectionManager.getConnection (/home/myapp/api/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:246:32)
       at Promise.try (/home/myapp/api/node_modules/sequelize/lib/sequelize.js:554:34)
   From previous event:
       at Promise.resolve.retryParameters (/home/myapp/api/node_modules/sequelize/lib/sequelize.js:454:64)
       at /home/myapp/api/node_modules/retry-as-promised/index.js:39:21
       at retryAsPromised (/home/myapp/api/node_modules/retry-as-promised/index.js:29:10)
       at Sequelize.query (/home/myapp/api/node_modules/sequelize/lib/sequelize.js:454:28)
       at QueryInterface.select (/home/myapp/api/node_modules/sequelize/lib/query-interface.js:1104:27)
       at Promise.try.then.then.then (/home/myapp/api/node_modules/sequelize/lib/model.js:1598:34)
       at bound (domain.js:396:14)
       at runBound (domain.js:409:12)
   From previous event:
       at Function.findAll (/home/myapp/api/node_modules/sequelize/lib/model.js:1595:8)
       at Function.findOne (/home/myapp/api/node_modules/sequelize/lib/model.js:1752:17)
```

__Dialect:__ postgres
__Dialect version:__ pg 6
__Database version:__ PostgreSQL 10.5-R1
__Sequelize version:__ 4.42.0
__Tested with latest release:__ No

**Comment by dennis2k** [comment]
Having the same issue after upgrading from 4.41 to 4.42 - running on mssql

**Comment by arusanovt** [comment]
Same here, most of the time it works ok, but after a day or two it starts happening, pgsql

**Comment by williamoliveira** [comment]
@arusanovt are you on 4.42 also?

**Comment by arusanovt** [comment]
Yep, I guess the error somehow connected to `generic-pool`
https://github.com/sequelize/sequelize/commit/00e49847366ad10f96d05c966041530253adf672

**Comment by arusanovt** [comment]
Tried 4.41 overnight and error still happening after sometime
sequelize 4.41.0
pg 7.7.1
and a new error popups from `generic-pool` which is used by sequelize
```
TypeError: Cannot create property 'next' on string '[Circular ~]'
  File "/app/node_modules/sequelize/node_modules/generic-pool/lib/DoublyLinkedList.js", line 72, col 22, in DoublyLinkedList.remove
    node.prev.next = node.next;
  File "/app/node_modules/sequelize/node_modules/generic-pool/lib/DoublyLinkedListIterator.js", line 59, col 16, in DequeIterator.remove
    this._list.remove(this._cursor);
  File "/app/node_modules/sequelize/node_modules/generic-pool/lib/Pool.js", line 381, col 32, in Pool._evict
    this._evictionIterator.remove();
  File "/app/node_modules/sequelize/node_modules/generic-pool/lib/Pool.js", line 392, col 14, in Timeout._scheduledEviction.setTimeout [as _onTimeout]
    this._evict();
  File "timers.js", line 436, col 11, in ontimeout
  File "timers.js", line 300, col 5, in tryOnTimeout
  File "timers.js", line 263, col 5, in listOnTimeout
  File "timers.js", line 223, col 10, in Timer.processTimers
```

**Comment by arusanovt** [comment]
I've managed to find a way to reproduce this error, and the error is in `generic-pool` package, downgrading it to `3.2.0` and removing sequelize dependency of it `package-lock.json` solved issue.

During debug, I've found that property `this.sequelize` of [`ConnectionManager`](https://github.com/sequelize/sequelize/blob/v4.42.1/lib/dialects/abstract/connection-manager.js#L246) was set to (Sic!) STRING == `'[Circular ~]'` by someone, wasn't able to find by whom, and this breaks everything that comes next

**Comment by sushantdhiman** [comment]
Looks like sentry fixed that upstream issue, hopefully it's fixed now.

**Comment by shamoons** [comment]
Still having the issue. `"@sentry/node": "5.6.2"` and `"sequelize": "^4.44.3"`

**Comment by berndartmueller** [comment]
Is there any way to fix this problem? We are also randomly experiencing this `Cannot read property 'databaseVersion' of undefined` error. `"sequelize": "4.39.0"`

**Comment by michaelvillar** [comment]
This is happening for us too.
We're on Sequelize 5.21.2 with Postgres — current Sequelize version is 5.21.3, which doesn't seem to have a fix for this.

**Comment by BrandonZacharie** [comment]
I still have this issue with Postgres / Sequelize 5.21.3 as well

**Comment by papb** [comment]
I think we really need a consistent way to reproduce this in order to be able to solve it... If anyone finds a way, please post here.

**Comment by michaelvillar** [comment]
We're using CLS, anyone else using CLS experiencing this issue?
