### ISSUE TITLE
incosistent set method result for hasOne association

### ISSUE THREAD

**Issue by neirongkuifa** [sequelize/sequelize#10526]
## What are you doing?

```js
// code here
// I have two models
const Person = sequelize.define('person', {
	id: {
		type: Sequelize.INTEGER,
		autoIncrement: true,
		allowNull: false,
		primaryKey: true
	},
	name: {
		type: Sequelize.STRING
	}
})

const Passport = sequelize.define('passport', {
	id: {
		type: Sequelize.INTEGER,
		primaryKey: true,
		autoIncrement: true,
		allowNull: false
	},
	name: Sequelize.STRING
})

// Two models have One-To-One association
Person.hasOne(Passport)

sequelize
	.sync({ force: true })
	.then(() => {
		return main()
	})
	.then(() => {
		return sequelize.close()
	})
	.then(() => {
		console.log('Close Connection')
	})
	.catch(err => {
		console.log('ERROR' + err)
	})

const main = async () => {
	try {
                const peter = await Person.create({ name: 'Peter' })
	        const paul = await Person.create({ name: 'Paul' })
	        const passportA = await Passport.create({ name: 'Peter' })
	        const passportB = await Passport.create({ name: 'Paul' })
		await peter.setPassport(passportB) //Works!
		await peter.setPassport(passportA) //Works!
		await peter.setPassport(passportB) //Fails
	} catch (err) {
		console.log(err)
	}
}
```

## What do you expect to happen?
1. When I excute peter.setPassport(passportB), the foreign key of passportB should be peter's id and passportA's fk should be null
2. When I excute peter.setPassport(passportA) then, the fk of passportB should be null and passportA's fk should be peter's id
3. When I excute peter.setPassport(passportB) again, the fk of passportB should be peter's id and passportA's fk should be null.

## What is actually happening?
1. Works as described
2. Works as described
3. passportA's fk is null. passportB's fk is null

__Dialect:__ mysql 
__Dialect version:__ 1.6.5
__Database version:__ 1.6.5
__Sequelize version:__ 4.43.0
__Tested with latest release:__5.0.0-beta.16

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
Fixed in master

**Comment by neirongkuifa** [comment]
> Fixed in master
Thanks for your reply.
I pulled directly from master branch. Tried to run the program again. The issue still exists.

**Comment by sushantdhiman** [comment]
@neirongkuifa are you sure? I am working on `master` and your code works fine on that branch

**Comment by neirongkuifa** [comment]
> @neirongkuifa are you sure? I am working on `master` and your code works fine on that branch

Yes. Here is the command line log. Notice the difference between 2 and 3
SUCCESS!
Executing (default): INSERT INTO `people` (`id`,`name`,`createdAt`,`updatedAt`) VALUES (DEFAULT,?,?,?);
Executing (default): INSERT INTO `people` (`id`,`name`,`createdAt`,`updatedAt`) VALUES (DEFAULT,?,?,?);
Executing (default): INSERT INTO `passports` (`id`,`name`,`createdAt`,`updatedAt`) VALUES (DEFAULT,?,?,?);
Executing (default): INSERT INTO `passports` (`id`,`name`,`createdAt`,`updatedAt`) VALUES (DEFAULT,?,?,?);
-----------1-------------
Executing (default): SELECT `id`, `name`, `createdAt`, `updatedAt`, `personId` FROM `passports` AS `passport` WHERE `passport`.`personId` = 1 LIMIT 1;
Executing (default): UPDATE `passports` SET `personId`=?,`updatedAt`=? WHERE `id` = ?
-----------2-------------
Executing (default): SELECT `id`, `name`, `createdAt`, `updatedAt`, `personId` FROM `passports` AS `passport` WHERE `passport`.`personId` = 1 LIMIT 1;
Executing (default): UPDATE `passports` SET `personId`=?,`updatedAt`=? WHERE `id` = ?
Executing (default): UPDATE `passports` SET `personId`=?,`updatedAt`=? WHERE `id` = ?
-----------3-------------
Executing (default): SELECT `id`, `name`, `createdAt`, `updatedAt`, `personId` FROM `passports` AS `passport` WHERE `passport`.`personId` = 1 LIMIT 1;
Executing (default): UPDATE `passports` SET `personId`=?,`updatedAt`=? WHERE `id` = ?
------------------------
Close Connection

**Comment by sushantdhiman** [comment]
`await peter.setPassport(passportB) //Fails` I thought this was actually throwing

**Comment by neirongkuifa** [comment]
> `await peter.setPassport(passportB) //Fails` I thought this was actually throwing

I tried to trace the code. It seems that the problem happened when this.changed() is called during the excution of peter.setPassport(passportB)

**Comment by neirongkuifa** [comment]
> `await peter.setPassport(passportB) //Fails` I thought this was actually throwing

Seems that issue still exists. No runtime error thrown during execution. The logic is clear and has no problem. I think it should be considered a bug.

**Comment by sushantdhiman** [comment]
You need to reload instance that may got updated after any relevant data change query.

In Case (2) you are calling `await peter.setPassport(passportA)`, this also affects `passportB` so that record is dirty, but sequelize is not aware about that. You need to reload that object before further reusing it, as it is still using old data `passportB.personId = peter.id`.

Similarly Case (3) needs reloading as well. 


```js
const Sequelize = require('./index');
const sequelize = require('./test/support').createSequelizeInstance();
const assert = require('assert');

const Person = sequelize.define('person', {
	id: {
		type: Sequelize.INTEGER,
		autoIncrement: true,
		allowNull: false,
		primaryKey: true
	},
	name: {
		type: Sequelize.STRING
	}
})

const Passport = sequelize.define('passport', {
	id: {
		type: Sequelize.INTEGER,
		primaryKey: true,
		autoIncrement: true,
		allowNull: false
	},
	name: Sequelize.STRING
})

// Two models have One-To-One association
Person.hasOne(Passport)

sequelize
	.sync({ force: true })
	.then(() => {
		return main()
	})
	.then(() => {
		return sequelize.close()
	})
	.then(() => {
		console.log('Close Connection')
	})
	.catch(err => {
		console.log('ERROR' + err)
	})

const main = async () => {
	try {
		const peter = await Person.create({ name: 'Peter' })
		const paul = await Person.create({ name: 'Paul' })
		const passportA = await Passport.create({ name: 'Peter' })
		const passportB = await Passport.create({ name: 'Paul' })

		await peter.setPassport(passportB) //Works!

		assert(peter.id === passportB.personId);
		assert(!passportA.personId);

		await peter.setPassport(passportA) //Works!

		assert(peter.id === passportA.personId);
		await passportB.reload();
		assert(!passportB.personId);

		await peter.setPassport(passportB) //Works actually

		assert(peter.id === passportB.personId);
		await passportA.reload();
		assert(!passportA.personId);

	} catch (err) {
		console.log(err)
	}
}
```

**Comment by neirongkuifa** [comment]
> You need to reload instance that may got updated after any relevant data change query.
> 
> In Case (2) you are calling `await peter.setPassport(passportA)`, this also affects `passportB` so that record is dirty, but sequelize is not aware about that. You need to reload that object before further reusing it, as it is still using old data `passportB.personId = peter.id`.
> 
> Similarly Case (3) needs reloading as well.
> 
> ```js
> const Sequelize = require('./index');
> const sequelize = require('./test/support').createSequelizeInstance();
> const assert = require('assert');
> 
> const Person = sequelize.define('person', {
> 	id: {
> 		type: Sequelize.INTEGER,
> 		autoIncrement: true,
> 		allowNull: false,
> 		primaryKey: true
> 	},
> 	name: {
> 		type: Sequelize.STRING
> 	}
> })
> 
> const Passport = sequelize.define('passport', {
> 	id: {
> 		type: Sequelize.INTEGER,
> 		primaryKey: true,
> 		autoIncrement: true,
> 		allowNull: false
> 	},
> 	name: Sequelize.STRING
> })
> 
> // Two models have One-To-One association
> Person.hasOne(Passport)
> 
> sequelize
> 	.sync({ force: true })
> 	.then(() => {
> 		return main()
> 	})
> 	.then(() => {
> 		return sequelize.close()
> 	})
> 	.then(() => {
> 		console.log('Close Connection')
> 	})
> 	.catch(err => {
> 		console.log('ERROR' + err)
> 	})
> 
> const main = async () => {
> 	try {
> 		const peter = await Person.create({ name: 'Peter' })
> 		const paul = await Person.create({ name: 'Paul' })
> 		const passportA = await Passport.create({ name: 'Peter' })
> 		const passportB = await Passport.create({ name: 'Paul' })
> 
> 		await peter.setPassport(passportB) //Works!
> 
> 		assert(peter.id === passportB.personId);
> 		assert(!passportA.personId);
> 
> 		await peter.setPassport(passportA) //Works!
> 
> 		assert(peter.id === passportA.personId);
> 		await passportB.reload();
> 		assert(!passportB.personId);
> 
> 		await peter.setPassport(passportB) //Works actually
> 
> 		assert(peter.id === passportB.personId);
> 		await passportA.reload();
> 		assert(!passportA.personId);
> 
> 	} catch (err) {
> 		console.log(err)
> 	}
> }
> ```

Thanks for your time!!! You saved me! It’s better if this can be written into doc as reload’s use case. Anyway, I should have notice this : )
