### ISSUE TITLE
Sequelize intellisense doesn't work in Visual Studio Code

### ISSUE THREAD

**Issue by Pavlex4** [sequelize/sequelize#11103]
## What are you doing?

I installed sequelize package inside Visual Studio Code and I imported it. Then I typed command new Sequelize and I opened brace and intellisense didn't appear. I also tried to define model and after typing model name and dot intellisense again didn't appear.
How to fix this problem?

## Environment
Dialect:
- [x] mysql
- [ ] postgres
- [ ] sqlite
- [ ] mssql
- [ ] any
Dialect **library** version: mysql2 1.6.5
Database version: XXX
Sequelize version: 5.8.9
Node Version: v11.12.0
OS: Windows 10 x64
If TypeScript related: TypeScript version: XXX
Tested with latest release:
- [ ] No
- [ ] Yes, specify that version:

**Comment by kuskhan** [comment]
I have the same problem here.

**Comment by raghavgrover21** [comment]
same.

**Comment by Platiplus** [comment]
I'm having the same problem - VS Code v1.35.1

**Comment by Flippittiflop** [comment]
Me too.
![image](https://user-images.githubusercontent.com/38591529/60760306-a3006880-a033-11e9-9c19-9054ee6ca588.png)

**Comment by renecruzATX** [comment]
Same but now on Version: 1.36.1

**Comment by papb** [comment]
This looks like a bug with VSCode to be honest... I just tried to reproduce, and the following happened:

1. I installed Sequelize on an empty local folder and tried to reproduce this problem, and *reproduced it successfully*

2. I navigated to `node_modules/sequelize/types/index.d.ts` and opened it as a new tab in VSCode and then closed it

3. I went back to my JS file and intellisense magically started working.

Can anyone check if this "solves" the problem as well? @kuskhan @raghavgrover21 @Platiplus @Flippittiflop @renecruzATX

**Comment by raghavgrover21** [comment]
@papb  no its not working, tried it with my 2 projects just to be sure.

**Comment by Platiplus** [comment]
> This looks like a bug with VSCode to be honest... I just tried to reproduce, and the following happened:
> 
> 1. I installed Sequelize on an empty local folder and tried to reproduce this problem, and _reproduced it successfully_
> 2. I navigated to `node_modules/sequelize/types/index.d.ts` and opened it as a new tab in VSCode and then closed it
> 3. I went back to my JS file and intellisense magically started working.
> 
> Can anyone check if this "solves" the problem as well? @kuskhan @raghavgrover21 @Platiplus @Flippittiflop @renecruzATX

That didn't solved the issue for me, the intellisense works on previous versions, but not in latest stable or 6.0.0.

What worked for me but it doesn't make sense is the following:

![image](https://user-images.githubusercontent.com/1918291/61129462-d8b9ad00-a48a-11e9-93cf-61a8f54c39f2.png)

But that only works in the connection file, when you try to import it for the modules, the autocomplete kind of works when you don't use this syntax. I'm really lost here hahaha

**Comment by papb** [comment]
@raghavgrover21 @Platiplus thanks for the replies. I am lost too. After I did what I said above, it started working and I can't reproduce the problem anymore. It started working for me magically...

**Comment by Pavlex4** [comment]
> > This looks like a bug with VSCode to be honest... I just tried to reproduce, and the following happened:
> > 
> > 1. I installed Sequelize on an empty local folder and tried to reproduce this problem, and _reproduced it successfully_
> > 2. I navigated to `node_modules/sequelize/types/index.d.ts` and opened it as a new tab in VSCode and then closed it
> > 3. I went back to my JS file and intellisense magically started working.
> > 
> > Can anyone check if this "solves" the problem as well? @kuskhan @raghavgrover21 @Platiplus @Flippittiflop @renecruzATX
> 
> That didn't solved the issue for me, the intellisense works on previous versions, but not in latest stable or 6.0.0.
> 
> What worked for me but it doesn't make sense is the following:
> 
> ![image](https://user-images.githubusercontent.com/1918291/61129462-d8b9ad00-a48a-11e9-93cf-61a8f54c39f2.png)
> 
> Using "const Sequelize = require('sequelize').Sequelize;" works.
> 
> But that only works in the connection file, when you try to import it for the modules, the autocomplete kind of works when you don't use this syntax. I'm really lost here hahaha

I tried this way and it worked. Thanks you very much.

**Comment by renecruzATX** [comment]
Beautiful!  Thanks @Platiplus!  It worked like a charm.  I have a database JS file that I created and that is where I deployed this trick.  Anywhere I import that database file the Intellisense works fine.  The hive mind works again!

**Comment by sarifconrati** [comment]
It works if you import `const Sequelize = require("sequelize").Sequelize` in the main connection file where you make connection to your database.

**Comment by XENOTpro** [comment]
`const Sequelize = require("sequelize").Sequelize` gets intellisense partly working, but (for me) intellisense is still not working within functions such as `create`.

**Comment by IvanJasenov** [comment]
On VSCode Version 1.36.1, it's also buggy but this one works
`const Sequelize = require('sequelize').Sequelize;`

Thanks, @Platiplus

**Comment by papb** [comment]
Observe that `const { Sequelize } = require('sequelize');` is more readable (IMO).

**Comment by nnaynnay** [comment]
This should also work.
`import { Sequelize } from 'sequelize';`

**Comment by sulian** [comment]
I confirm the problem in vscode 1.37.1 under Windows 10

**Comment by papb** [comment]
@sulian Does

```js
const { Sequelize } = require('sequelize');
```

instead of

```
const { Sequelize } = require('sequelize');
```

fix it for you?

**Comment by A7madXatab** [comment]
you can also try install @types/sequelize, and then import it in your file


`
const Sequelize= require('@types/sequelize')
`

**Comment by RanjithRanaRudra** [comment]
Thanks , it works if we use

const { Sequelize } = require('sequelize');
instead of

const Sequelize = require('sequelize');

**Comment by sulian** [comment]
> 
> 
> @sulian Does
> 
> ```js
> const { Sequelize } = require('sequelize');
> ```
> 
> instead of
> 
> ```js
> const Sequelize = require('sequelize');
> ```
> 
> fix it for you?

It works

**Comment by GhostGLR** [comment]
It also gets intellisense partly working, but (for me) intellisense is still not working within functions such as create() or ...

**Comment by papb** [comment]
@GhostGLR Can you show a SSCCE/MCVE/reprex where `const { Sequelize } = require('sequelize');` does not give correct intellisense for `create`?

**Comment by GhostGLR** [comment]
I Did This: 
![1](https://user-images.githubusercontent.com/45856848/63998718-04febb00-cb17-11e9-9b6f-fcc12f897db8.png)
![2](https://user-images.githubusercontent.com/45856848/63998719-05975180-cb17-11e9-9b67-9ebec4c0ac42.png)
![3](https://user-images.githubusercontent.com/45856848/63998720-05975180-cb17-11e9-8458-17fe3b0d6cc1.png)

Thanks For Helping!

**Comment by GhostGLR** [comment]
Thanks it worked.

**Comment by papb** [comment]
I have changed this to a docs issue. This just has to be better explained in our tutorials.

**Comment by husalem** [comment]
> @sulian Does
> 
> ```js
> const { Sequelize } = require('sequelize');
> ```
> 
> instead of
> 
> ```js
> const Sequelize = require('sequelize');
> ```
> 
> fix it for you?

Thanks a lot.
That solved it on VSCode 1.40.2

**Comment by papb** [comment]
This was fixed in #11825, now our tutorials always use the correct form:

```js
const { Sequelize } = require('sequelize');
```

**Comment by sharjeel288** [comment]
> > This looks like a bug with VSCode to be honest... I just tried to reproduce, and the following happened:
> > 
> > 1. I installed Sequelize on an empty local folder and tried to reproduce this problem, and _reproduced it successfully_
> > 2. I navigated to `node_modules/sequelize/types/index.d.ts` and opened it as a new tab in VSCode and then closed it
> > 3. I went back to my JS file and intellisense magically started working.
> > 
> > Can anyone check if this "solves" the problem as well? @kuskhan @raghavgrover21 @Platiplus @Flippittiflop @renecruzATX
> 
> That didn't solved the issue for me, the intellisense works on previous versions, but not in latest stable or 6.0.0.
> 
> What worked for me but it doesn't make sense is the following:
> 
> ![image](https://user-images.githubusercontent.com/1918291/61129462-d8b9ad00-a48a-11e9-93cf-61a8f54c39f2.png)
> 
> Using "const Sequelize = require('sequelize').Sequelize;" works.
> 
> But that only works in the connection file, when you try to import it for the modules, the autocomplete kind of works when you don't use this syntax. I'm really lost here hahaha

Thanks Buddy it Works for me perfectly

**Comment by ibrod1983** [comment]
For those who are having trouble using this "trick" in other modules, you can add a JSDoc comment. For instance, i have this function:

```
/**
 * @return {Sequelize} db//This will make visual code know that "db" is of type Sequelize.Sequelize
 */
function getDb() {
    return db;
}
```

And then when i use it in a model, the intellisense works:

const sequelize = getDb();

```
const Category = sequelize.define('category', {    
    name: { type: DataTypes.STRING },   

});
```

**Comment by Juanpam** [comment]
@papb The [getting started ](https://sequelize.org/v5/manual/getting-started.html)section from the V5 docs is still showing the import without destructuring. I think docs should be updated accordingly so intellisense is working right from the start :)

**Comment by itsmejay80** [comment]
@sulian  this worked for me:
`const { Sequelize } = require('sequelize');`
Thanx

**Comment by CycoStallion** [comment]
> This should also work.
> `import { Sequelize } from 'sequelize';`

This did it for me as well! Thank you

**Comment by CycoStallion** [comment]
> > This looks like a bug with VSCode to be honest... I just tried to reproduce, and the following happened:
> > 
> > 1. I installed Sequelize on an empty local folder and tried to reproduce this problem, and _reproduced it successfully_
> > 2. I navigated to `node_modules/sequelize/types/index.d.ts` and opened it as a new tab in VSCode and then closed it
> > 3. I went back to my JS file and intellisense magically started working.
> > 
> > Can anyone check if this "solves" the problem as well? @kuskhan @raghavgrover21 @Platiplus @Flippittiflop @renecruzATX
> 
> That didn't solved the issue for me, the intellisense works on previous versions, but not in latest stable or 6.0.0.
> 
> What worked for me but it doesn't make sense is the following:
> 
> ![image](https://user-images.githubusercontent.com/1918291/61129462-d8b9ad00-a48a-11e9-93cf-61a8f54c39f2.png)
> 
> Using "const Sequelize = require('sequelize').Sequelize;" works.
> 
> But that only works in the connection file, when you try to import it for the modules, the autocomplete kind of works when you don't use this syntax. I'm really lost here hahaha

Thanks @Platiplus, this worked for me too

**Comment by matheushf** [comment]
In my case I have no types/intellisense even with destructuring `require`. What solved my case was adding a tsconfig.json in my project. 
Since it's a JS project it won't be a problem and I added it to .gitignore, it's quite a ugly workaround tho...

**Comment by adamjedrzejec** [comment]
Looks like Sequelize is NOT an export default.

In recent versions of JS it would look like this:
`import { Sequelize } from 'sequelize'`

but not like this:
`import Sequelize from 'sequelize'`

**Comment by imhazard17** [comment]
> > This looks like a bug with VSCode to be honest... I just tried to reproduce, and the following happened:
> > 
> > 1. I installed Sequelize on an empty local folder and tried to reproduce this problem, and _reproduced it successfully_
> > 2. I navigated to `node_modules/sequelize/types/index.d.ts` and opened it as a new tab in VSCode and then closed it
> > 3. I went back to my JS file and intellisense magically started working.
> > 
> > Can anyone check if this "solves" the problem as well? @kuskhan @raghavgrover21 @Platiplus @Flippittiflop @renecruzATX
> 
> That didn't solved the issue for me, the intellisense works on previous versions, but not in latest stable or 6.0.0.
> 
> What worked for me but it doesn't make sense is the following:
> 
> ![image](https://user-images.githubusercontent.com/1918291/61129462-d8b9ad00-a48a-11e9-93cf-61a8f54c39f2.png)
> 
> Using "const Sequelize = require('sequelize').Sequelize;" works.
> 
> But that only works in the connection file, when you try to import it for the modules, the autocomplete kind of works when you don't use this syntax. I'm really lost here hahaha

Thanks bro it worked for me...

**Comment by daweimau** [comment]
> `const Sequelize = require("sequelize").Sequelize` gets intellisense partly working, but (for me) intellisense is still not working within functions such as `create`.

I experienced similar behaviour when working on my project inside a mounted Docker volume. I haven't figured out the "right" way to resolve this, but when I installed the npm packages in my local directory (not just inside the Docker container) then VScode intellisense was suddenly able to trace through all the class functions. 

There's probably a "right" way of curing this other than mine.

**Comment by ArunAtGitHubb** [comment]
> @sulian Does
> 
> ```js
> const { Sequelize } = require('sequelize');
> ```
> 
> instead of
> 
> ```js
> const Sequelize = require('sequelize');
> ```
> 
> fix it for you?

Yeah it fix my issue! thanks 🤗

**Comment by milon27** [comment]
# Follow this you will get Intellisense works properly. 

1. /models/index.js 

```js
'use strict';

const fs = require('fs');
const path = require('path');
const Sequelize = require('sequelize');
const basename = path.basename(__filename);
const env = process.env.NODE_ENV || 'development';
const config = require(__dirname + '/../config/config.json')[env];
const db = {};

let con;
if (config.use_env_variable) {
  con = new Sequelize(process.env[config.use_env_variable], config);
} else {
  con = new Sequelize(config.database, config.username, config.password, config);
}

fs
  .readdirSync(__dirname)
  .filter(file => {
    return (file.indexOf('.') !== 0) && (file !== basename) && (file.slice(-3) === '.js');
  })
  .forEach(file => {
    const model = require(path.join(__dirname, file));
    db[model.name] = model;
  });

Object.keys(db).forEach(modelName => {
  if (db[modelName].associate) {
    db[modelName].associate(db);
  }
});

/**
 * @return {Sequelize.Sequelize} con
 */
function getCon() {
  return con;
}

db.getCon = getCon

module.exports = db;


```


2. /models/User.js

```js
const { DataTypes } = require('sequelize');
const db = require('./index')

const User = db.getCon().define("User", {
    name: {
        type: DataTypes.STRING,
        allowNull: false
    },
    password: {
        type: DataTypes.STRING,
        allowNull: false
    }
})

module.exports = User

```

**Comment by haibert** [comment]
> # Follow this you will get Intellisense works properly.
> 1. /models/index.js
> 
> ```js
> 'use strict';
> 
> const fs = require('fs');
> const path = require('path');
> const Sequelize = require('sequelize');
> const basename = path.basename(__filename);
> const env = process.env.NODE_ENV || 'development';
> const config = require(__dirname + '/../config/config.json')[env];
> const db = {};
> 
> let con;
> if (config.use_env_variable) {
>   con = new Sequelize(process.env[config.use_env_variable], config);
> } else {
>   con = new Sequelize(config.database, config.username, config.password, config);
> }
> 
> fs
>   .readdirSync(__dirname)
>   .filter(file => {
>     return (file.indexOf('.') !== 0) && (file !== basename) && (file.slice(-3) === '.js');
>   })
>   .forEach(file => {
>     const model = require(path.join(__dirname, file));
>     db[model.name] = model;
>   });
> 
> Object.keys(db).forEach(modelName => {
>   if (db[modelName].associate) {
>     db[modelName].associate(db);
>   }
> });
> 
> /**
>  * @return {Sequelize.Sequelize} con
>  */
> function getCon() {
>   return con;
> }
> 
> db.getCon = getCon
> 
> module.exports = db;
> ```
> 
> 2. /models/User.js
> 
> ```js
> const { DataTypes } = require('sequelize');
> const db = require('./index')
> 
> const User = db.getCon().define("User", {
>     name: {
>         type: DataTypes.STRING,
>         allowNull: false
>     },
>     password: {
>         type: DataTypes.STRING,
>         allowNull: false
>     }
> })
> 
> module.exports = User
> ```

What if you are using an existing DB and used auto-sequelize to generate your models. so your models look like this 

``` javascript
const Sequelize = require('sequelize').Sequelize

class client extends Sequelize.Model {
    static init(sequelize, DataTypes) {
        return super.init(
            {
                clientID: {
                    autoIncrement: true,
                    type: DataTypes.INTEGER.UNSIGNED,
                    allowNull: false,
                    primaryKey: true,
                },
                FirstName: {
                    type: DataTypes.STRING(100),
                    allowNull: false,
                },
                LastName: {
                    type: DataTypes.STRING(100),
                    allowNull: false,
                },
                email: {
                    type: DataTypes.STRING(254),
                    allowNull: false,
                },
                CustomerName: {
                    type: DataTypes.STRING(100),
                    allowNull: false,
                },
                BusinessAddress: {
                    type: DataTypes.STRING(100),
                    allowNull: true,
                },
                BusinessCity: {
                    type: DataTypes.STRING(45),
                    allowNull: true,
                },
                BusinessState: {
                    type: DataTypes.STRING(45),
                    allowNull: true,
                },
                BusinessZip: {
                    type: DataTypes.DECIMAL(10, 0),
                    allowNull: true,
                },
                BusinessCountry: {
                    type: DataTypes.STRING(45),
                    allowNull: true,
                    defaultValue: 'USA',
                },
                BusinessPhone: {
                    type: DataTypes.STRING(15),
                    allowNull: false,
                },
                BusinessFax: {
                    type: DataTypes.STRING(15),
                    allowNull: true,
                },
                MobilePhone: {
                    type: DataTypes.STRING(15),
                    allowNull: true,
                },
                ContactName: {
                    type: DataTypes.STRING(50),
                    allowNull: true,
                },
                ContactTitle: {
                    type: DataTypes.STRING(45),
                    allowNull: true,
                },
                ContactPhone: {
                    type: DataTypes.STRING(15),
                    allowNull: true,
                },
                ContactEmail: {
                    type: DataTypes.STRING(100),
                    allowNull: true,
                },
                Comments: {
                    type: DataTypes.STRING(255),
                    allowNull: true,
                },
                Status: {
                    type: DataTypes.ENUM('Y', 'N'),
                    allowNull: true,
                    defaultValue: 'Y',
                },
                openingBalance: {
                    type: DataTypes.DECIMAL(10, 2),
                    allowNull: false,
                },
                openingBalanceAsOf: {
                    type: DataTypes.DATEONLY,
                    allowNull: false,
                },
                customerSince: {
                    type: DataTypes.DATEONLY,
                    allowNull: false,
                },
                companyTicketAttributres: {
                    type: DataTypes.TEXT,
                    allowNull: false,
                },
                nickName: {
                    type: DataTypes.STRING(255),
                    allowNull: true,
                },
                urgentNote: {
                    type: DataTypes.TEXT,
                    allowNull: false,
                },
                urgentNoteEnabled: {
                    type: DataTypes.STRING(100),
                    allowNull: false,
                },
                suspended: {
                    type: DataTypes.STRING(20),
                    allowNull: false,
                },
                suspendedDate: {
                    type: DataTypes.DATE,
                    allowNull: false,
                },
                lastUpdated: {
                    type: DataTypes.STRING(200),
                    allowNull: false,
                },
                CustomerType: {
                    type: DataTypes.STRING(200),
                    allowNull: false,
                },
                createdClientPortalID: {
                    type: DataTypes.INTEGER,
                    allowNull: false,
                },
            },
            {
                sequelize,
                tableName: 'client',
                timestamps: false,
                indexes: [
                    {
                        name: 'PRIMARY',
                        unique: true,
                        using: 'BTREE',
                        fields: [{ name: 'clientID' }],
                    },
                    {
                        name: 'ContactName',
                        using: 'BTREE',
                        fields: [{ name: 'ContactName' }],
                    },
                    {
                        name: 'CustomerName',
                        using: 'BTREE',
                        fields: [{ name: 'CustomerName' }],
                    },
                    {
                        name: 'email',
                        using: 'BTREE',
                        fields: [{ name: 'email' }],
                    },
                    {
                        name: 'urgentNote',
                        type: 'FULLTEXT',
                        fields: [{ name: 'urgentNote' }],
                    },
                ],
            }
        )
    }
}

module.exports = (sequelize, DataTypes) => {
    return client.init(sequelize, DataTypes)
}

```

**Comment by feyton** [comment]
> @sulian Does
> 
> ```js
> const { Sequelize } = require('sequelize');
> ```
> 
> instead of
> 
> ```js
> const Sequelize = require('sequelize');
> ```
> 
> fix it for you?

This worked for me. Using the default import is the issue

**Comment by sanjarcode** [comment]
The default import doesn't solve the major problem. It enabled autocomplete for the `Sequelize.*`, but autocomplete still doesn't work if the model was created using `sequelize.define()` where `sequelize` is the db instance.

**Comment by vishal30982** [comment]
This problem still exists.

vscode:
Version: 1.103.1 (user setup)
Commit: 360a4e4fd251bfce169a4ddf857c7d25d1ad40da
Date: 2025-08-12T16:25:40.542Z
Electron: 37.2.3
ElectronBuildId: 12035395
Chromium: 138.0.7204.100
Node.js: 22.17.0
V8: 13.8.500258-electron.0
OS: Windows_NT x64 10.0.19045
