### ISSUE TITLE
Bugfix invalid query log not bind parameters in sequelize@5.9.0

### ISSUE THREAD

**Issue by ryuki0628** [sequelize/sequelize#11151]
version: sequelize@5.9.0

Invalid query log not bind parameters in sequelize@5.9.0

## What are you doing?
use query logging.
execute update method.

## What do you expect to happen?
output sql log
```
Executing (default): UPDATE users SET email = 'test@test.com', updated_at = '2019-01-01 10:00:00' WHERE id = 1;
```

## What is actually happening?
query log not bind parameters

output sql log
```
Executing (default): UPDATE users SET email = ?, updated_at = ? WHERE id = ?;
```

## Environment
Dialect:
- [x] mysql
- [ ] postgres
- [ ] sqlite
- [ ] mssql
- [x] any
Database version: 5.7
Sequelize version: 5.9.0

If TypeScript related: TypeScript version: XXX
Tested with latest release:
- [ ] No
- [x] Yes, specify that version: 

## How to modify
target file path: lib/dialects/mysql/query.js
line: 37
```js
    const complete = this._logQuery(parameters ? connection.format(sql, parameters) : sql, debug);
```

**Comment by sushantdhiman** [comment]
Fixed by https://github.com/sequelize/sequelize/pull/11267

**Comment by soufian044** [comment]
I'm still seeing the same issue with the "?" in the logs for the UPDATE 
using the latest version 5.19.0

![image](https://user-images.githubusercontent.com/10144036/65225178-f0ce2e00-dac4-11e9-8fa5-b7ec489b33ee.png)

**Comment by sushantdhiman** [comment]
@soufian044 You will need to pass `logQueryParameters: true` to your Sequelize constructor options to enable parameter logging

**Comment by soufian044** [comment]
@sushantdhiman  thank you, i would suggest to update the [API Reference for the Sequelize constructor](https://sequelize.org/master/class/lib/sequelize.js~Sequelize.html#instance-constructor-constructor).

**Comment by sushantdhiman** [comment]
@soufian044 It will automatically update in 24 hours

**Comment by Nogias9x** [comment]
Hi @sushantdhiman ,

Can we somehow have it 
```sql
UPDATE `users` SET `age`=10;
```
instead of
```sql
UPDATE `users` SET `name`=?; 10
```

I've having trailing params while using MySQL
