### ISSUE TITLE
Instance in upsert hooks has all fields `changed`

### ISSUE THREAD

**Issue by armellarcier** [sequelize/sequelize#12700]
## Issue Description

In all lifecycle hooks called when using `upsert`, `instance.changed` returns the whole set of attributes, no matter whether they did change or not.

### What are you doing?

```js

```

```js
MyModel.beforeValidate = async(instance, options) => {
  instance.changed("type"); // returns true
  instance.isNewRecord; // is true
}
// original in db is { unique: 1, title: "old title", type: "post" }
MyModel.upsert({ unique: 1, title: "new title", type: "post" });
```

### What do you expect to happen?

Only the modified fields should be `changed`

### What is actually happening?

The instance gets recreated and `_previousDatavalues` is empty

### Environment

- Sequelize version: 6.3.5 
- Node.js version: v10.13.0 
- Operating System: Mac OSX

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [X] I don't know, I was using mysql, with connector library version XXX and database version 8.0.15

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by armellarcier** [comment]
Hi bot. Please stop.

**Comment by WikiRik** [comment]
Hi @armellarcier 
Sorry about the bot. Could you try this again on Sequelize 6.11.0 (the latest release)? We've added support for MySQL 8 in 6.10.0 so maybe this has been fixed

**Comment by WikiRik** [comment]
Hi @armellarcier
Can you check if this is fixed on the latest v6 release?

**Comment by ephys** [comment]
It's not fixed because whether this is a bug is debatable

Similarly to https://github.com/sequelize/sequelize/issues/13432, when using static methods like `upsert`, `update`, etc.. `beforeValidate` is not being called with the model that's really being updated.

Instead, `upsert` creates a fake model with the values it received from the method call and gives that fake model to `beforeValidate`.
It's a weird behavior but it seems intended. IMO it should just call `beforeValidate` with the raw input instead of creating a fake model.
