### ISSUE TITLE
Models.bulkInsert using options.searchPath does not work

### ISSUE THREAD

**Issue by wilski-b** [sequelize/sequelize#13454]
## Issue Creation Checklist

[y] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Issue Description

Using Sequelize version 6.3.3, and Postgres dialect, when passing options.searchPath the passed searchPath is not applied to the created statement.

### What was unclear/insufficient/not covered in the documentation

The bulkCreate options documentation shows the following description for options.searchPath: `An optional parameter to specify the schema search_path (Postgres only)`. This does not seem to work, I'm not sure if it should be submitted as a bug or a flaw in the documentation.

### If possible: Provide some suggestion on how we can enhance the docs

Fix this as a bug or remove this as an option in the documentation.

**Comment by david-annopolsky** [comment]
Hi all, @sdepold  i see this was resolved in 6.8.0 and im currently using 6.32.1

I have a migration (using umzug) where i do 
```js
export const up = async ({ context: { queryInterface, schema } }) => {
    await queryInterface.bulkInsert('type', seedTypes, { searchPath: schema })
}
```
and it doesnt seem to take on a new search path for my custom schema and the insert fails

however if i set it in the before command of my seeder everything works as expected
```js
seeder.on('beforeCommand', async () => {
  await sequelize.getQueryInterface().sequelize.query(`SET search_path TO ${config.schema},public`) 
})
```
am I missing something?

i see this issue is related specific to models so if i need to i can i open another issue for `queryInterface`

**Comment by baudday** [comment]
I don’t think this is actually resolved. Sitting here in 2025 still experiencing the same issue using `bulkInsert` not `bulkCreate`.
