### ISSUE TITLE
ERR_PACKAGE_PATH_NOT_EXPORTED error on startup with 6.12.0 on Node 12 or 14

### ISSUE THREAD

**Issue by EverlastEngineering** [sequelize/sequelize#13787]
## Issue Creation Checklist

[x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

### What do you expect to happen?

_I want Node 12 or Node 14 to continue to start when using 6.12.0._

### What is actually happening?

_We receive this error on startup after an npm update today:_

```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /Users/xxx/Source/xxx-service/WebContent/node_modules/sequelize/package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:285:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:508:3)
    at resolveExports (internal/modules/cjs/loader.js:450:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/xxx/Source/xxx-service/WebContent/node_modules/sequelize-values/lib/patches.js:9:32)
    at Module._compile (internal/modules/cjs/loader.js:1085:14) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
```

### Additional context

Manually specifying 6.11.0 works fine. I have not updated node yet since I am mirroring a deployed instance on AWS for support purposes. 

### Environment

- Sequelize version: sequelize@6.12.0  
- Node.js version: v14.17.1 or 12.22.7 (untested on others) 

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by EverlastEngineering** [comment]
Just to note the severity of this, AWS does an npm update after a server reboot, so anyone with a ^6.0.0 in their package would have a failure.

I'm not sure if I'm unique in my setup or what, but I will certainly provide any additional details on req.

**Comment by scalebig** [comment]
Yeah ... this bit us also during a build also.

**Comment by WikiRik** [comment]
@ephys do you think this might be related to your change?

**Comment by sepo-one** [comment]
Same error here

**Comment by sepo-one** [comment]
What is the temporary fix ?
(Downgrade to 6.0.0 ?)

**Comment by WikiRik** [comment]
> What is the temporary fix ?
> (Downgrade to 6.0.0 ?)

As mentioned in the post, manually specifying 6.11.0 works fine and can be used as a temporary fix

**Comment by ephys** [comment]
@WikiRik I think so, the `exports` property in package.json blocks other imports

Working on a fix

**Comment by ephys** [comment]
Should be fixed by https://github.com/sequelize/sequelize/pull/13795

**Comment by mohsinriaz17** [comment]
Similar issue on re-deploy on clever cloud, it updated the version

**Comment by tapz** [comment]
I started to get this with node 14 after updating from 6.11.0 to 6.12.0:

`(node:32) UnhandledPromiseRejectionWarning: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/sql-string' is not defined by "exports" in /app/node_modules/sequelize/package.json`

**Comment by sdepold** [comment]
Fixed in 6.12.1 :)

**Comment by ollydixon** [comment]
Was because I was importing from `"sequelize/types"` and not `"sequelize"`

VSC automatically used /types,

**Comment by lkleinert** [comment]
@ollydixon I believe i am getting that same error. How did you correct import of sequelize? My code looks like this and is still throwing the error you received when attempting to run "npx sequelize-cli db:migrate" ....in my user.js file I have ```const { Model, DataTypes } = require("sequelize");
module.exports = (sequelize, DataTypes) => {
  class User extends Model {}```
