### ISSUE TITLE
[proposal] Plugins connecting and `sequelize` instance sharing

### ISSUE THREAD

**Issue by cusspvz** [sequelize/sequelize#2508]
Since `sequelize` is relaying on `hooks` to comunicate with plugins, shouldn't be better to include a method so we can pass a `sequelize` instance to plugins?

I would propose a similar `socket.io` and  `express.js` approach...
#### Specs for `Sequelize.prototype.plugin`

1 - `.plugin` method should communicate with plugins by passing to the plugin's function: `sequelize` instance as 1st argument, and `options` object as 2nd argument.
1.1 - If first argument is a function, it should only call it with `sequelize` instance.
1.2 - For the laziest and KISS fans, if a string is provided instead as `.plugin`'s first argument, `.plugin` method should use require internally.
1.2.1 - We should be able to require relational paths
1.2.1.1 - If an wild card exists, it should search for `.js` files and require them all recursively.
1.2.2 - We should be able to require node modules
1.3 - If first argument is an array, it should call it self recursively with each value
2 - Options handling
2.1 - Second argument of `.plugin` should be optional and be passed to plugin **always** as an object
2.2 - If plugin's **function** has the key **defaultOptions** defined as an object, `.plugin` should extend options, if provided, from it.
3 - `.plugin` should throw an error if something went wrong.
4 - `.plugin` should return `sequelize` instance always for chain proposes.
#### Specs for `Sequelize.plugin`

1 - Should proxy into `Sequelize.prototype.plugin` by passing args context within `afterInit` hook
##### Core Implementation Example

```
Sequelize.plugin = function ( plugin, options ) {
  return this.addHook( 'onInit', function ( sequelize ) {
    sequelize.plugin( plugin, options );
  });
};
```
#### Plugging Examples

```
/*
 *  Plugging into Sequelize Class ( they will be applied on all future Sequelize instances )
 */
Sequelize.plugin( 'sequelize-cache-redis' );

/*
 *  Plugging into Sequelize instance (won't be applied on other Sequelize instances )
 */
var sequelize = new Sequelize( /* ... */ );

sequelize.plugin( 'sequelize-cache-redis' );

/*
 *  Plugging multiple plugins into a Sequelize Class by chaining
 */
Sequelize
  .plugin( 'sequelize-cache-redis' )
  .plugin( 'sequelize-tree' );

/*
 *  Plugging multiple plugins into a Sequelize Class by an array with names
 */
Sequelize
  .plugin([ 'sequelize-cache-redis', 'sequelize-tree' ]);

/*
 *  Plugging into a Sequelize Class from a folder of plugins
 */
Sequelize.plugin( './models/plugins/*' );

/*
 *  Plugging into a Sequelize Class providing options
 */
Sequelize.plugin( 'plugin-name', { foo: 'bars' } );

/*
 *  Plugging the same plugin into different Sequelize instances with different options
 */
var localRedisClient, sharedRedisClient;

var mysql = new Sequelize( /* mysql config */ );
var sqlite = new Sequelize( /* local sqlite config */ );

mysql.plugin( 'sequelize-cache-redis', { redis: sharedRedisClient });
sqlite.plugin( 'sequelize-cache-redis', { redis: localRedisClient });

```
#### Plugin Examples

```
/*
 *  Plugin skeleton example
 */
module.exports = function ( sequelize, options ) {
  // ...
};

// Default options definition
module.exports.defaultOptions = {
  somePluginOption: false,
};
```

```
/*
 *  Cache Plugin example
 */
module.exports = function ( sequelize, options ) {
  if( ! options.redis ) return;

  sequelize.addHook( 'afterDefine', function ( Model ) {
    if( ! Model.options.cache ) return;

    Model.addHook( 'beforeFind', function ( queryOptions ) {
      // ...
    });

    Model.addHook( 'afterFind', function ( queryOptions ) {
      // ...
    });
  });
};

// Default options definition
module.exports.defaultOptions = {
  redis: false,
};
```

Opinions and suggestions?
@overlookmotel @mickhansen @janmeier

**Comment by mickhansen** [comment]
Close to finishing up 2.0 and would like to focus on this after that.

Do we have any examples of other javascript systems that have plugin/package support that we could take a look at aswell?

**Comment by cusspvz** [comment]
We did some research before creating [hotplug](https://github.com/findhit/findhit-hotplug) and some of them were:
* reading packages of from `package.json` dependencies;
* plugging using a method on instances;

IMHO, as i described before, since **sequelize** is relying the plugin system on top of hooks, this API is the best approach and covers all cases.

**Comment by cusspvz** [comment]
I've added specs for `Sequelize.plugin` implementation also

**Comment by cusspvz** [comment]
> Close to finishing up 2.0 and would like to focus on this after that.

since `2.0` is already up, shouln't **sequelize** have something like this already?

ping @mickhansen @janmeier

**Comment by mickhansen** [comment]
@cusspvz Ideally, but time is limited :)

**Comment by overlookmotel** [comment]
I'm not saying anything new here, but just to repeat, I've been thinking about this on and off since this issue was originally raised in December, and I still favour the approach of:

1. `.plug()` method being on the Sequelize _constructor_ rather than sequelize instances
2. Where plugins alter the usual behaviour of sequelize in any way, the plugin must only be activated (i.e. doing the thing that alters the behaviour) when an option is passed asking it to in the `new Sequelize()` call.

Point (2) ensures that you can have multiple sequelize instances, but only have a plugin acting on some of them - allowing the kind of 'scoping' that @cusspvz requires.

Anyway, that's just my opinion...

**Comment by mickhansen** [comment]
I don't have any strong opinions about it currently, i'm developing a set of acl plugins and i'm just relying on people calling `plugin(sequelize)`.

https://github.com/mickhansen/ssacl-attribute-roles

**Comment by overlookmotel** [comment]
I think @janmeier was tending to agree with my approach, @cusspvz disagrees. So how can a decision be made?

**Comment by cusspvz** [comment]
> the plugin must only be activated (i.e. doing the thing that alters the behaviour) when an option is passed asking it to in the new Sequelize() call

Well I think we can't limit it as you are suggestion, most of plugins would require options and could be optionally activated or not, but i think that we should provide that tools for plugin developers or let them decide as they want.

A simple example of a plugin that won't require options on sequelize construction could be your ** hierarchy** behavior plugin.

> .plug() method being on the Sequelize constructor rather than sequelize instances

I tried to focus on wide appliable implementation, I had the need to define plugins for each sequelize instance and you for Sequelize constructor, so they both are present as a single wide solution.

I, and certainly more developers, could have different constructed sequelize for different proposes. A simple fact like having a restricted secure database for storing credentials and stuff like that is enough for explaining to you why it is so important.

Do you have more suggestions related to this subject? If think that if there aren't more cons about this proposal, we can close it and start execution.

**Comment by cusspvz** [comment]
@overlookmotel if you mean to allow options trough sequelize options i completely agree, but they should inherit plugin options if any.

```js
// Example:
Sequelize.plugin('plugin', { test: 'abc', foo: 'bar' });

new Sequelize({ plugin: { foo: 'disco' }  });

// Plugin should receive
{ test: 'abc', foo: 'disco', ... }
```

**Comment by alekbarszczewski** [comment]
I've also tried to put my two cents in PR #4462 but I agree that plugin should be a function (I wanted a plugin to be a instance/object initially). However I like "my" idea to pass plugins in options to either Sequelize constructor or Model constructor, for example:

```js
var sequelize = new Sequelize({ plugins: [ plugin1({ /* plugin options */ }), plugin2() ] })
// or
var User = sequelize.define('User', {}, { plugins: [ plugin1() ] }) // very handy if plugin is used only on one model!
```

For me it is very clear approach because plugins are applied in one place (I can see all plugins I am using globally or on specific model, while with ".plugin()" approach plugins may be injected/plugged/installed everywhere in code, and then it might be hard to find out which plugins someone is actually using). I am curious what do you think of this approach (why it is worse than ".plugin()" method)?

Apart from installing/plugging plugins there is one more thing that I think might be very useful for plugins: before/afterSync hooks on models (or even on sequelize instance). Let's say that I want my plugin to add a trigger on Models table. Right now, AFAIK, there is no proper hook that would allow me to do that (I would have to export some method that had to be explicitly invoked by user). With afterSync hook I could just check if trigger is not already created, and if not, then create it. This should probably go to other issue but it is also related to plugins - what do you think guys?

**Comment by overlookmotel** [comment]
@alekbarszczewski I agree that before/afterSync hooks would be a good idea. But as you say, better to raise a separate issue for this. Do you want to implement it? The changes required to create these hooks isn't too complicated.

**Comment by alekbarszczewski** [comment]
@overlookmotel Moved discussion about hooks here #4479 - I've implemented before/afterSync hooks in #4478.

**Comment by janmeier** [comment]
This issue has been going on for quite some time now, and I still don't have a very strong opinion about either way - I'm leaning mostly towards what we're doing now with just calling `plugin(sequelize)` though.

@alekbarszczewski You do make a valid point though, that the `plugins` option would ensure you can easily see which plugins are attached...

**Comment by alekbarszczewski** [comment]
@janmeier Now I am also not sure which way I prefer :). For sure the most flexible way is to leave plugin initialization/installation for plugin itself as you said. And flexibility is good I guess. Right now (without making any changes to sequelize) I can imagine three ways of plugin installation:

```js
// plugin.js
module.exports = function (sequelize) { /* do some initialization */ }

// app.js
var Sequelize = require('sequelize')
var plugin = require('plugin')
var sequelize = new Sequelize(...)
plugin(sequelize) // plugin installation
``` 

```js
// plugin.js
module.exports = function (Sequelize) {
  Sequelize.addHook('beforeInit', function (dbOptions, options) {
    /* do some initialization */
  })
  Sequelize.addHook('afterInit', function (sequelize) {
    /* do some initialization */
  })
}

// app.js
var Sequelize = require('sequelize')
var plugin = require('plugin')
plugin(Sequelize)
var sequelize = new Sequelize(...)
```

```js
// plugin.js
var Sequelize = require('sequelize') // plugin has peerDependency on sequelize
Sequelize.addHook('beforeInit', function (dbOptions, options) {
  /* do some initialization */
})
Sequelize.addHook('afterInit', function (sequelize) {
  /* do some initialization */
})

// app.js
var Sequelize = require('sequelize')
var plugin = require('plugin') // must be included before calling new Sequelize(...)
var sequelize = new Sequelize(...)
```

**Comment by janmeier** [comment]
Actually I believe it would be the prettiest if all plugins attach to the constructor (`plugin(Sequelize)`, your second approach - if they need to attach to instances, they can do so in an `afterInit` hook.

**Comment by cusspvz** [comment]
Its been a time since my last contributions here on sequelize. :)

@janmeier sorry for not agreeing with you. Most of apps I'm working ATM use some kind of `plugins` attributions and have a way to handle options. Besides, `.plugin` call seems more pretty on code than a bunch of requires / imports (ES6)

```js
import Sequelize from 'sequelize'
import PluginA from 'sequelize-plugin-a'
import PluginB from 'sequelize-plugin-b'

PluginA( Sequelize )
PluginB( Sequelize )

require( 'sequelize-plugin-c' )( Sequelize, {
  /* options */
})

export default new Sequelize( /* options */ )
```

vs

```js
import Sequelize from 'sequelize'

export default new Sequelize( /* options */ )
.plugin( 'sequelize-plugin-a' )
.plugin( 'sequelize-plugin-b' )
.plugin( 'sequelize-plugin-c', {
  /* plugin options */
})
```

or even

```js
var Sequelize = require( 'sequelize' ).plugin({
  'sequelize-plugin-a': true,
  'sequelize-plugin-b': true,
  'sequelize-plugin-c': {
    /* plugin options */
  },
})

module.exports = new Sequelize( /* options */ )
```

I really like the way `webpack` is injecting plugins, and just to cover @overlookmotel 's need to inject `DataTypes` or other assets, I really think they should be provided by module instead of injecting things into Sequelize object to avoid unwanted bugs.

**Comment by englercj** [comment]
Been nearly a year since this has seen any activity, any movement been made?

**Comment by mickhansen** [comment]
@englercj Yes and no, we've more or less decided not to decide on any specific plugin system.
We'll provide hooks where necessary but AOP + Existing hooks should really provide everything a plugin author needs.

**Comment by overlookmotel** [comment]
I have some thoughts on this but haven't had time to raise an issue yet. One feature missing from existing hooks is error handling (i.e. if an table insert fails, there's no hook at present which can catch the error and take some action).

**Comment by mickhansen** [comment]
@overlookmotel Wrapping handles that case perfectly though.

**Comment by overlookmotel** [comment]
@mickhansen True! But it'd be easier if some of the basic stuff was done first before your hook code e.g. conforming the arguments, cloning `option` object etc.

Anyway, I'll raise an issue when I get a chance. It should be possible to implement this (if everyone likes what I propose, that is) without any breaking changes, so needn't be before Sequelize v4.

**Comment by papb** [comment]
I think it might be interesting to bring this discussion back to life again, so I will reopen this.
