### ISSUE TITLE
paranoid instance.destroy() with timestamps with custom fields does not work

### ISSUE THREAD

**Issue by JSteunou** [sequelize/sequelize#2879]
I have this in my models

```
        createdAt: {
            type: DataTypes.DATE,
            field: 'created_at'
        },
        updatedAt: {
            type: DataTypes.DATE,
            field: 'updated_at'
        },
        deletedAt: {
            type: DataTypes.DATE,
            field: 'deleted_at'
        }
```

creation works well, but if I destroy the resource like this

```
db.User.create(user).then(function(dbUser) {
  return dbUser.destroy();
}).then ....;
```

it send this

```
Executing (default): UPDATE `user` SET `deletedAt`='2015-01-09 13:32:42',`updatedAt`='2015-01-09 13:32:42' WHERE `id`=1
```

Which does not work because it's not snake_case

**Comment by JSteunou** [comment]
Same issue with find. Seems all generated `where` are impacted.

```
Executing (default): SELECT `id`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt`, `deleted_at` AS `deletedAt`, `email`, `firstname`, `lastname`, FROM `user` AS `user` WHERE (`user`.`deletedAt` IS NULL AND `user`.`id`=1);
```

**Comment by mickhansen** [comment]
`find` definitely works, we have tests for that. https://github.com/sequelize/sequelize/blob/master/test/model/attributes/field.test.js
Might very well be related to the fact that it's special timestamp attributes though

**Comment by JSteunou** [comment]
Can see why. I did 

```
db.User.findOne({where: {id: id}});
```

And I assume the paranoid mode auto add `deleted_at IS NULL` and I cannot blame because it does not have a user instance to read definition.

But he can read definition on destroy ;)

**Comment by mickhansen** [comment]
Should be fixed now.

**Comment by JSteunou** [comment]
Nope, it is not. The issue is related with where clause (destroy, find, ...) and still present.

```javascript
db.User.findOne({where: {id: id}});
```

```bash
Executing (default): SELECT `id`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt`, `deleted_at` AS `deletedAt`, `email`, `firstname`, `lastname`, `uuid` FROM `user` AS `user` WHERE (`user`.`deletedAt` IS NULL AND `user`.`id`=1);
Possibly unhandled SequelizeDatabaseError: ER_BAD_FIELD_ERROR: Unknown column 'user.deletedAt' in 'where clause'
```

**Comment by mickhansen** [comment]
https://github.com/sequelize/sequelize/blob/master/test/model/attributes/field.test.js#L503

You are running against master?
If still failing please provide a reproduceable test case against master. (minimal model defnition + call)

**Comment by JSteunou** [comment]
Aaah sorry sorry, though it was published with rc7

**Comment by mickhansen** [comment]
no rc7 was published before this fix :)

**Comment by JSteunou** [comment]
Check with #master this time and I'm happy to confirm it fixes the issue.

**Comment by mickhansen** [comment]
Good :)

**Comment by JSteunou** [comment]
Hoooo @mickhansen I found a twisted case that might re-open this bug.

using 

```
db.User.destroy({where: {id: user.id}});
```

instead of

```
user.destroy();
```

still fire

```
Executing (default): UPDATE `user` SET `deletedAt`='2015-01-12 09:58:05' WHERE `id`=1
```

**Comment by mickhansen** [comment]
Well not related to original issue so normally i'd ask for a new issue, but i'll reopen.

**Comment by JSteunou** [comment]
I confirm it works fine in rc8. Thank you @mickhansen
