### ISSUE TITLE
Odd SQL generated when filtering an association.

### ISSUE THREAD

**Issue by ericrini** [sequelize/sequelize#3403]
Schema

```
sequelize.define('Advisors', {
    advisorId: {
        field: 'advisor_id',
        type: DataTypes.INTEGER.UNSIGNED,
        allowNull: false,
        primaryKey: true,
        autoIncrement: true
    },
    firstName: {
        field: 'first_name',
        type: DataTypes.STRING(32),
        allowNull: false
    },
    lastName: {
        field: 'last_name',
        type: DataTypes.STRING(32),
        allowNull: false
    }
}, {
    tableName: 'advisors',
    underscored: true,
    instanceMethods: {
        toJSON: function()
        {
            return utilities.removeSnakeAttributes(this.get());
        }
    }
});

sequelize.define('AdvisorsToPlans', {
    id: {
        field: 'advisors_ref_plans_id',
        type: DataTypes.INTEGER.UNSIGNED,
        allowNull: false,
        primaryKey: true,
        autoIncrement: true
    },
    advisorId: {
        field: 'advisor_id',
        type: DataTypes.STRING(32),
        allowNull: false
    },
    planId: {
        field: 'plan_id',
        type: DataTypes.STRING(32),
        allowNull: false
    }
}, {
    tableName: 'advisors_ref_plans',
    underscored: true,
    instanceMethods: {
        toJSON: function()
        {
            return utilities.removeSnakeAttributes(this.get());
        }
    }
});

Plans.belongsToMany(db.Advisors, {
    as: 'advisors',
    foreignKey: 'plan_id',
    through: 'advisors_ref_plans'
});

Advisors.belongsToMany(db.Plans, {
    as: 'plans',
    foreignKey: 'advisor_id',
    through: 'advisors_ref_plans'
});
```

Queries

```
Plans.findAll({
    include: [
        {
            association: db.Plans.Advisors,
            where: {
                advisorId: 1
            }
        }
    ],
    limit: 100,
    skip: 0
});
```

SQL

```
SELECT `Plans`.*, 
       `advisors`.`advisor_id`                    AS `advisors.advisorId`, 
       `advisors`.`first_name`                    AS `advisors.firstName`, 
       `advisors`.`last_name`                     AS `advisors.lastName`, 
       `advisors`.`created_at`                    AS `advisors.created_at`, 
       `advisors`.`updated_at`                    AS `advisors.updated_at`, 
       `advisors.advisors_ref_plans`.`created_at` AS 
       `advisors.advisors_ref_plans.created_at`, 
       `advisors.advisors_ref_plans`.`updated_at` AS 
       `advisors.advisors_ref_plans.updated_at`, 
       `advisors.advisors_ref_plans`.`advisor_id` AS 
       `advisors.advisors_ref_plans.advisor_id`, 
       `advisors.advisors_ref_plans`.`plan_id`    AS 
       `advisors.advisors_ref_plans.plan_id` 
FROM   (SELECT `plans`.`plan_id` AS `planId`, 
               `plans`.`created_at`, 
               `plans`.`updated_at` 
        FROM   `plans` AS `Plans` 
        WHERE  (SELECT `advisors_ref_plans`.`advisor_id` 
                FROM   `advisors_ref_plans` AS `advisors_ref_plans` 
                       INNER JOIN `advisors` AS `Advisors` 
                               ON `advisors_ref_plans`.`advisor_id` = 
                                  `advisors`.`plan_id` 
                WHERE  ( `plans`.`planid` = `advisors_ref_plans`.`plan_id` ) 
                LIMIT  1) IS NOT NULL 
        LIMIT  10) AS `Plans` 
       INNER JOIN (`advisors_ref_plans` AS `advisors.advisors_ref_plans` 
                   INNER JOIN `advisors` AS `advisors` 
                           ON `advisors`.`advisor_id` = 
       `advisors.advisors_ref_plans`.`advisor_id`) 
               ON `Plans`.`planid` = `advisors.advisors_ref_plans`.`plan_id` 
                  AND `advisors`.`advisor_id` = 1; 
```

Error

```
ER_BAD_FIELD_ERROR: Unknown column 'Plans.planId' in 'where clause'
```

If I remove the limit from the query, or the where clause from the include, things work as expected. Otherwise the SQL generated appears to be incorrect?

Perhaps there is an error in the model or query definition?

**Comment by mickhansen** [comment]
Looks like there's a bug, i'll have to try out the schema manually though.

**Comment by mikealeonetti** [comment]
Oh! I was driving myself crazy with the same issue!

Schema:
```javascript
var job = sequelize.define( 'job', {
    'id': {
        type: Sequelize.INTEGER( 10 ),
        field: 'job_id',
        allowNull: false,
        primaryKey: true,
        autoIncrement: true
    },
    'externalID' : {
        type:  Sequelize.STRING( 45 ),
        field: 'external_id',
        allowNull: false,
        unique: true,
        validate: {
            notEmpty: true
        }
    },
    'status' : {
        type:  Sequelize.STRING( 16 ),
        field: 'status',
        allowNull: false,
        defaultValue: 'processing'
    },
    'filename' : {
        type:  Sequelize.STRING( 64 ),
        field: 'filename',
        allowNull: true
    }
}, {
    'createdAt' : 'created',
    'updatedAt' : 'modified',
    'tableName' : 'jobs'
} );

var number = sequelize.define( 'number', {
    'id': {
        type: Sequelize.BIGINT( 20 ),
        field: 'number_id',
        allowNull: false,
        primaryKey: true,
        autoIncrement: true
    },
    'jobID': {
        type: Sequelize.INTEGER( 10 ),
        field: 'job_id',
        allowNull: false
    },
    'externalID' : {
        type:  Sequelize.STRING( 45 ),
        field: 'external_id',
        allowNull: false,
        unique: true,
        validate: {
            notEmpty: true
        }
    },
    'number' : {
        type:  Sequelize.STRING( 16 ),
        field: 'number',
        allowNull: false,
        validate: {
            notEmpty: true
        }
    },
    'extension' : {
        type:  Sequelize.STRING( 16 ),
        field: 'extension',
        allowNull: true
    },
    'status' : {
        type:  Sequelize.STRING( 16 ),
        field: 'status',
        allowNull: false,
        defaultValue: 'new'
    },
    'lastCall' : {
        type:  Sequelize.DATE,
        field: 'last_call',
        allowNull: true
    },
    'tries' : {
        type:  Sequelize.INTEGER,
        field: 'tries',
        allowNull: false,
        defaultValue: 0
    },
}, {
    'createdAt' : 'created',
    'updatedAt' : 'modified',
    'tableName' : 'numbers'
} );

job.hasMany( number, { 'foreignKey' : 'job_id' } );
number.belongsTo( job, { 'foreignKey' : 'job_id' } );
```

Queries:
```javascript
    // Look for messages to play
    db.job.find( {
        'where': { 'status' : [ 'new', 'inprogress', 'done' ] },
//      'limit' : 1, // Obviously
        'order' : [[ 'jobID' , 'DESC' ]], // Latest
        'include' : [
                     { 
                         'model' : db.number,
                         'where' : { 'number' : this.number }
                     }
                     ]
    } ).complete( ... );
```

SQL:
```
SELECT `job`.*,
       `numbers`.`number_id` AS `numbers.id`,
       `numbers`.`job_id` AS `numbers.jobID`,
       `numbers`.`external_id` AS `numbers.externalID`,
       `numbers`.`number` AS `numbers.number`,
       `numbers`.`extension` AS `numbers.extension`,
       `numbers`.`status` AS `numbers.status`,
       `numbers`.`last_call` AS `numbers.lastCall`,
       `numbers`.`tries` AS `numbers.tries`,
       `numbers`.`created` AS `numbers.created`,
       `numbers`.`modified` AS `numbers.modified`,
       `numbers`.`job_id` AS `numbers.job_id`
FROM
  (SELECT `job`.`job_id` AS `id`,
          `job`.`external_id` AS `externalID`,
          `job`.`status`,
          `job`.`filename`,
          `job`.`created`,
          `job`.`modified`
   FROM `jobs` AS `job`
   WHERE `job`.`status` IN ('new',
                            'inprogress',
                            'done')
     AND
       (SELECT `job_id`
        FROM `numbers` AS `numbers`
        WHERE `job`.`id` = `numbers`.`job_id`
          AND `numbers`.`number` IN ('5166610769') LIMIT 1) IS NOT NULL
   ORDER BY `job`.`jobID` DESC LIMIT 1) AS `job`
INNER JOIN `numbers` AS `numbers` ON `job`.`id` = `numbers`.`job_id`
AND `numbers`.`number` IN ('5556656565')
ORDER BY `job`.`jobID` DESC;
```

Error:
>  error: Callback: Error fetching job via number. SequelizeDatabaseError: ER_BAD_FIELD_ERROR: Unknown column 'job.id' in 'where clause'

If I remove the where from the include it works for me too. But I do need the where there.

**Comment by jrsprice** [comment]
I'm experiencing the same thing. Since I'm looking up a particular unique id, I'm using the results[0] for now. Adding in limit or using findOne is raising the ER_BAD_FIELD_ERROR.

**Comment by sitexw** [comment]
I have exactly the same problem. When you combine a join, limit and order, it is error : `Unhandled rejection SequelizeDatabaseError: ER_BAD_FIELD_ERROR: Unknown column 'User.created_at' in 'order clause'`

**Comment by Name-less** [comment]
+1, it is working when I do not use the limit but when I add both the limit and the order it reject the demand ...

here is the order (the limit is just `limit:10`) :
 `order: [  [ { model: base.Ties, as: 'MatchsTiesId' }, 'tie_schedule', 'ASC' ]  ]`

The rejection message : 
`Unhandled rejection SequelizeDatabaseError: ER_BAD_FIELD_ERROR: Unknown column 'MatchsTiesId.tie_schedule' in 'order clause' `

Nothing special for the limit ... any tips ?

**Comment by mickhansen** [comment]
@Name-less check if the attribute is getting renamed in the subquery

**Comment by Name-less** [comment]
@mickhansen here is the end of the notworking query : 
`WHERE 'bdnet_matchs'.'mtch_status' != 34 LIMIT 15) AS 'bdnet_matchs' INNER JOIN 'bdnet_draws' AS 'MatchsTiesId.TiesRoundsId.RoundsDrawsId' ON 'MatchsTiesId.TiesRoundsId.rund_drawId' = 'MatchsTiesId.TiesRoundsId.RoundsDrawsId'.'draw_id' AND 'MatchsTiesId.TiesRoundsId.RoundsDrawsId'.'draw_eventId' = 5222 LEFT OUTER JOIN ('bdnet_p2m' AS 'MatchToPair.bdnet_p2m' INNER JOIN 'bdnet_pairs' AS 'MatchToPair' ON 'MatchToPair'.'pair_id' = 'MatchToPair.bdnet_p2m'.'p2m_pairId') ON 'bdnet_matchs'.'mtch_id' = 'MatchToPair.bdnet_p2m'.'p2m_matchId' LEFT OUTER JOIN ('bdnet_i2p' AS 'MatchToPair.PairToRegi.bdnet_i2p' INNER JOIN 'bdnet_registration' AS 'MatchToPair.PairToRegi' ON 'MatchToPair.PairToRegi'.'regi_id' = 'MatchToPair.PairToRegi.bdnet_i2p'.'i2p_regiId') ON 'MatchToPair'.'pair_id' = 'MatchToPair.PairToRegi.bdnet_i2p'.'i2p_pairId' LEFT OUTER JOIN 'bdnet_members' AS 'MatchToPair.PairToRegi.RegistrationMembersId' ON 'MatchToPair.PairToRegi'.'regi_memberId' = 'MatchToPair.PairToRegi.RegistrationMembersId'.'mber_id' LEFT OUTER JOIN 'bdnet_teams' AS 'MatchToPair.PairToRegi.RegistrationTeamsId' ON 'MatchToPair.PairToRegi'.'regi_teamId' = 'MatchToPair.PairToRegi.RegistrationTeamsId'.'team_id' ORDER BY 'MatchsTiesId'.'tie_schedule' ASC;``

And the working one : 
`WHERE 'bdnet_matchs'.'mtch_status' != 34 ORDER BY 'MatchsTiesId'.'tie_schedule' ASC;'``

Look like it get renamed

**Comment by mickhansen** [comment]
@Name-less You'll need to change your order to reflect that. for `4.0` we're killing in-query renaming and will rely on client side renaming instead to make stuff like this more predictable.

**Comment by Name-less** [comment]
@mickhansen  What can I change on my order to make it working ? Because I use alias ... 
In 4.0 this will not work anymore ?

**Comment by mickhansen** [comment]
No way to have it both ways i'm afraid. There's be other stuff to update for 4.0, usually is for a semver major bump :)

**Comment by novasdream** [comment]
I Think i have the same issue.


````javascript
module.exports = function(sequelize, DataTypes) {
  var Categorias = sequelize.define("Categorias", {
    nome: DataTypes.STRING
  }, 
  {
    tableName: 'categorias',
    createdAt: false,
    updatedAt: false
    
  });

  return Categorias;
};

```

````javascript

module.exports = function(sequelize, DataTypes) {
  var Categoria = sequelize.define("Categoria", {
    categoria_id: DataTypes.INTEGER,
    grupo_id: DataTypes.STRING
  }, 
  {
    tableName: 'grupo_categorias',
    createdAt: false,
    updatedAt: false,
    classMethods: {
      associate: function(models) {
        Categoria.hasOne(models.Categorias, {
          foreignKey: {
            name: 'categoria_id',
            allowNull: true
          }
        })
      }
    },
    instanceMethods: {
      getNome: function(models, callback){
        models.Categorias.find({where: ['id ='+this.categoria_id] }).then(function(categorias)
        {
          callback(categorias.nome);
        })
      }
    }
  });

  return Categoria;
};
```

```sql
SELECT `Grupo`.`id`, 
       `Grupo`.`nome`, 
       `Grupo`.`regras`, 
       `Grupo`.`descricao`, 
       `Grupo`.`url`, 
       `Grupo`.`usuarioid`, 
       `Grupo`.`bloqueado`, 
       `Categoria`.`id`                     AS `Categoria.id`, 
       `Categoria`.`categoria_id`           AS `Categoria.categoria_id`, 
       `Categoria.Categoria`.`id`           AS `Categoria.Categoria.id`, 
       `Categoria.Categoria`.`nome`         AS `Categoria.Categoria.nome`, 
       `Categoria.Categoria`.`categoria_id` AS 
       `Categoria.Categoria.categoria_id` 
FROM   `grupos` AS `Grupo` 
       LEFT OUTER JOIN `grupo_categorias` AS `Categoria` 
                    ON `Grupo`.`id` = `Categoria`.`grupo_id` 
       LEFT OUTER JOIN `categorias` AS `Categoria.Categoria` 
                    ON `Categoria`.`id` = `Categoria.Categoria`.`categoria_id`; 
```


my error

```json
{Error: ER_BAD_FIELD_ERROR: Unknown column 'Categoria.Categoria.categoria_id' in 'field list'}
```

**Comment by gavinr** [comment]
I'm having this issue too. Would love to see a fix. Thanks to the maintainers for all the work they put into this package!

**Comment by heller166** [comment]
+1

**Comment by JasperTack** [comment]
I'm still seeing an issue like this. Has this been taken up by any other ticket?

**Comment by fxfactorial** [comment]
Needs to be reopened

**Comment by Nogias9x** [comment]
I'm using Sequelize 5.8.11.
```javascript
User.findAndCountAll({
    distinct: true,
    where: filter,
    include: userRelationships,
    offset,
    limit,
  });
```
This query work if limit = undefined, else I got "SequelizeDatabaseError: Unknown column 'blabla' in 'on clause'".
If I add `subQuery: false`, it works, but incorrectly paginate with limit != undefined.
I think this issue shoul be re-open because it makes the query result unpredictable.

**Comment by Nogias9x** [comment]
Thank you for reopening this @papb

**Comment by Nogias9x** [comment]
Is there any updates on this, please?

**Comment by Nogias9x** [comment]
Sometimes  I can work around with "separate: true". Hope it helps someone.

**Comment by papb** [comment]
> Is there any updates on this, please?

Nothing that I'm aware of, sorry

**Comment by Nogias9x** [comment]
No worries, we understand this is a difficult issue to investigate and fix @papb .
Thank you for keep working on Sequelize. It's an awesome ORM.
Have a nice day @papb

**Comment by rGaillard** [comment]
Hello,

There is any fix available for this issue?

Thank you.

**Comment by sostenesapollo12** [comment]
Hello everybody I'm trying to do something like this a couple of days ago.

When I have just
>whereParams = {
>    [op.or]: [                
>         {'produtos.nome_produto': search )},
>         {'aplicacoes.nome_aplicacao_produto': search )}                
>    ]
>}
>includeParams = [		
>	{ model:Db.Aplicacao },
>]

it works fine, but when I include a many to many table

`{ model:Db.Modelo }`

and I try to find something using the expression  'table'.'colum' , don't works and the sequelize give me the error:
> Unknown column 'aplicacoes.nome_aplicacao_produto' in 'where clause'

Can someone help ?

**Comment by Nogias9x** [comment]
I'm not sure @sostenesapollo12, but you can try playing with **`subQuery`** and **`separate`** like this.
```js
Class.findAll({
      distinct: true,
      subQuery: false, // default = true
      where: whereParams,
      include: [
             {
                  separate: true, // default = false
                  model: Student,
             },
       ]
})
```

I wish you luck :)

**Comment by muhammadfazeel** [comment]
any fix available for this issue?

**Comment by uzair004** [comment]
still getting this issue when using `where` in the include model. It resolves when I removed where clause but I do need where. otherwise it will return all data, I need specific.
