### ISSUE TITLE
Attributes modified in hooks are not saved

### ISSUE THREAD

**Issue by Verdier** [sequelize/sequelize#3534]
If you add a hook to (for exemple) a `User` model, and save an instance of the model with some attributes modified, such as:

``` javascript
user.email = 'toto@toto.com';
user.save();
```

And if you modify some user attributes into the (for exemple...) `afterValidate` hook:

``` javascript
function afterUserValidate(user) {
  if(user.changed('email')) {
    return u.md5(user.email).then((md5) => user.emailMd5 = md5);
  }
}
```

The `emailMd5` attribute is not saved. This is because dirty attributes are computed before the _pre-save_ hooks.

So my question: could we imagine to compute dirty attributes **after** the _pre-save_ hooks?

**Comment by janmeier** [comment]
@Verdier Should be fixed on latest master, can you test it?

**Comment by Hoverbear** [comment]
Confirming this, I had the same issue, am running latest master.

**Comment by mickhansen** [comment]
@Hoverbear Does it work with `member.set('complete', true|false)`

**Comment by Hoverbear** [comment]
I tried doing that as well...

```js
            afterValidate: function (member, options, fn) {
                if (member.name &&
                    member.type &&
                    member.gender &&
                    member.birthDate &&
                    member.contactName &&
                    member.contactRelation &&
                    member.contactPhone &&
                    member.medicalNumber)
                {
                    console.log("Complete");
                    member.set('complete', true);
                } else {
                    console.log("Incomplete");
                    member.set('complete', false);
                }
                fn(null, member);
            },
```

Still not saving this change.

**Comment by Hoverbear** [comment]
This appears to be isolated to the `beforeValidate` and `afterValidate` hooks.

**Comment by Verdier** [comment]
@Hoverbear: Yep, I'm confirm that's only in `beforeValidate` and `afterValidate`. Here is a workaround: 
```js
afterValidate: function (instance, options) {
 // ... change `instance` fields ...
 options.fields = instance.changed()
}
```

**Comment by mickhansen** [comment]
Looks like only `beforeCreate` is set up to figure out if values changed during a hook (in cases of default `.changed()` fields): https://github.com/sequelize/sequelize/blob/master/lib/instance.js#L583

Same code would need to be applied to after validation.

**Comment by fredrikekelund** [comment]
+1 for this

**Comment by goodwill** [comment]
Tried on 3.27 still have same problem with beforeValidate

All I did was use a model lookup for an email field, and then save the UserId if email matches, wasted me 2 hours and turn out not working. Using beforeUpdate works.

**Comment by sushantdhiman** [comment]
Its not ported to `v3`, its in master branch i.e. `v4`

**Comment by goodwill** [comment]
In this case when is 4 suppose to release?

**Comment by felixfbecker** [comment]
soon, hopefully before mid-January. See the milestone for release blockers.

**Comment by svvac** [comment]
Any chance to see this backported to 3.x series ?

**Comment by mrstif** [comment]
Hi guys,

Just upgraded from v3.30.4 to v4.2.1 to try and solve this issue but apparently it's still there...

The tests included by @sushantdhiman aren't really testing the whole scenario since what's persisted in the database isn't actually what's returned in the save/update callback. I hit the same pitfall in which the object in the callback is updated whereas getting the record directly from the database is not...

I'll try to change the tests to show what I mean.

**Comment by xitij** [comment]
In a related issue I'm seeing that when you update a field in `beforeCreate` it works fine (the value is saved). However, removing fields isn't saved properly. Ex.
```
beforeCreate: function (object, options) {
  if (object.data === 'some value') {
    delete object.data;
  }
}
```

When the value is returned after the create `object.data = 'some value'`

**Comment by arungangula** [comment]
I fixed the issue by calling the .save() method in the hooks

**Comment by akenger** [comment]
This bug still exists in 4.22.12. If you set an attribute in a beforeUpdate hook that was not part of the original list of update fields, the updated field appears in the response but not in the database.
You can't call .save in a beforeUpdate hook b/c it creates an endless loop.

**Comment by singleparty** [comment]
i have an solution
```
hooks: {
      beforeBulkUpdate (options) {
        options.attributes.version= 99
        options.fields.push('version')
      }
    }
```
version is the attributes what you want to saved

---

sequelize/lib/model.js line:2679

```
return this.runHooks('beforeBulkUpdate', options).then(() => {
          values = options.attributes;
          delete options.attributes;
        });
```

sequelize/lib/model.js line:2766
```
valuesUse = Utils.mapValueFieldNames(valuesUse, options.fields, this);
      // .......

```

**Comment by mariotacke** [comment]
Running into the same thing right now (`pg`: `7.4.1`, `sequelize`: `4.33.3`). I'm trying to reset my `updatedAt` column before it updates:

```
hooks: {
  beforeUpdate: (entity) => {
    entity.updatedAt = null;
  },
},
```

As a work-around I can manually set `updatedAt` in my `update` call, but I'd much rather set it in the model definition.

**Comment by davidmicksch** [comment]
I had a similar issue.  It turns out that I was using the async version of bcrypt to encrypt passwords before they were stored in the database.  It didn't matter which hook I tried, it would never store the result in the database, but it appeared to work fine as it returned the hashed value back to my client.  I switched over to using the synchronous version of bcrypt and that solved the problem.  Apparently by the time the ascyc version got back with the password, it was too late.

**Comment by davidmicksch** [comment]
I had a similar problem.  It turns out that I was using bcrypt in an async mode in a beforeSave hook to encrypt the user's password.  This worked fine for the create process.  However, for the update process, this ended up writing the unencrypted (original value).  I switched over to using the synchronous mode of bcrypt and it worked fine for both the create and update.   

With the async version, it did actually encrypt the password and assign it back to the attribute, but that was too late to take effect.

**Comment by JSandmark** [comment]
Surprised to find this issue! Same issue for me on Sequelize CLI [Node: 8.9.0, CLI: 3.2.0, ORM: 4.32.6], changing date-data in the beforeValidate hook when calling model.save() is not persisted. I am returning a promise from the hook and in my tests only dates are affected (not saved). Could someone else please confirm?
```
myDate: {
      type: DataType.DATE,
    },
```

**Comment by iverenshaguy** [comment]
Please has this issue been fixed, I'm going mad here

**Comment by ThaisFaria** [comment]
I called .save on the beforeDestroy hook and it worked but as pointed above, it will not work for update as it will cause an infinite loop.

**Comment by SolveSoul** [comment]
I'm at version 4.37 and I'm also having this issue. As pointed out above when using create everything works fine but when upserting the altered values in the hook are ignored. Everything inside the hook is running sync so that should not be an issue. Even when logging the values at the last line of the hook I can see the altered values, but they are not used in the Sequelize query :/

Any updates in this issue?

**Comment by gunar** [comment]
In the meantime, I've found a workaround by using `beforeCreate` and `beforeUpdate`.
```js
const beforeValidate = (instance, options) => {
  // ...
}

const options = {
  hooks: {
    // Custom "beforeValidate" hook because of a bug on sequelize.
    // See https://github.com/sequelize/sequelize/issues/3534
    beforeCreate: beforeValidate,
    beforeUpdate: beforeValidate,
  },
}

const MyModel: Model = sequelize.define('myModel', schema, options)
```

**Comment by papb** [comment]
Can someone please provide a [SSCCE](http://sscce.org/) (also known as [MCVE/reprex](https://stackoverflow.com/help/minimal-reproducible-example)) for this?

**Comment by nechmads** [comment]
I still get the same thing when using beforeCreate and Sequelize version 5.21.3
The clear password is the one saved all the time. The only way I managed to solve it is to move and use the synchronous version of bcrypt.

`
User.beforeCreate((user, options) => {
		return bcrypt.hash(userToBeSaved.password, 10, (err, hash) => {
			if (err) {
				throw err
			}

			userToBeSaved.password = hash
			console.log(userToBeSaved)
		})
	})
`

**Comment by papb** [comment]
I've removed the bug label because it is still not clear if this is a bug or feature request; [waiting for someone to provide an SSCCE](https://github.com/sequelize/sequelize/issues/3534#issuecomment-522199802).

**Comment by brian-human-interest** [comment]
Still seeing this is 2020 on a `beforeValidate` hook.

**Comment by brian-human-interest** [comment]
It looks like there's an SSCCE in this linked issue: https://github.com/sequelize/sequelize/issues/8829

Does that help?

**Comment by brian-human-interest** [comment]
Also, I think this warrants the `bug` label since the observed behavior seems to contradict how the documentation seems to suggest these hooks are used.

**Comment by itaber** [comment]
I've just spent the last day trying to figure out why my hooks weren't working, only to find out that there is a difference between the documentation and implementation.

> Arguments to hooks are passed by reference. This means, that you can change the values, and this will be reflected in the insert / update statement. 
https://sequelize.org/v4/manual/tutorial/hooks.html (we're using v4 for now)

I defiantly read that to mean I can alter the model values in the hooks and have those changes persisted.

**Comment by cbarlow1993** [comment]
@JSandmark - I have the same issue where my beforeUpdate hook triggers, fields are updated and saved however any Date type fields do not update. Using `instance.set('TimeStamp', new Date().toISOString())` does not save to the database.

**Comment by francisli** [comment]
Still debugging to try and narrow this down to a minimal reproduction example... but I'm seeing this bug in a beforeSave hook specifically with a JSONB column... I can change other column values in the same hook function, and they will be saved, but not the JSONB column, it seems...

**Comment by francisli** [comment]
After digging further, for anyone else who ends up here, it is _by design_ that the beforeUpdate (including beforeSave, on an existing record) is NOT allowed to change additional attributes that were not previously changed before the update/save call.

You can see the code in the current master branch starting here: https://github.com/sequelize/sequelize/blob/bb30483a95658bc1e729d5ae2a966f86872f955d/src/model.js#L4108

It collects a list of attributes in which it will ignore changes (ignoreChanged), which is all the configured attributes not already changed when the update/save is called. It uses that list to filter out any additional changes made during the execution of the hook.

You can override this behavior by manually adding the changed fields to options.fields before your hook function returns.

**Comment by jamesguan** [comment]
I am having this issue only for the beforeUpsert hook. beforeCreate seems to work just fine for me.

**Comment by daweimau** [comment]
I have found pass by reference behaviour in hooks does not hold true with operations using chained promises. However it does work when converted to async await.

The below code does not successfully updated `timesheet.staff_rate`:
```javascript
beforeCreate: (timesheet) => {
    timesheet
        .getStaffMember()
        .then((staff) => timesheet.staff_rate = staff.rate);
}
```

However, the below code successfully updates the same field:
```javascript
beforeCreate: async (timesheet) => {
    const staff = await timesheet.getStaffMember();
    timesheet.staff_rate = staff.rate;
}
```

One reason this is not a good thing is that it changes our capability to handle errors. Hooks do not handle async errors very gracefully, and without the ability to use promise syntax, our options are more restricted.

**Comment by reediculous456** [comment]
> I am having this issue only for the beforeUpsert hook. beforeCreate seems to work just fine for me. This is with the use case where I want to hash the password before storing it into the database upon the upsert.

I am also having this issue with the beforeUpsert hook. I am trying to do the following: 
```ts
beforeUpsert(attributes: M, options: UpsertOptions) {
  if (!options.actorId) {
    throw new Error(`Must include actorId option`);
  }
  attributes.createdBy = options.actorId;
  attributes.updatedBy = options.actorId;
  console.log(attributes);
},
```
and I see the 2 new attributes in the object, but they are not saved to the database

**Comment by reediculous456** [comment]
> Can someone please provide a [SSCCE](http://sscce.org/) (also known as [MCVE/reprex](https://stackoverflow.com/help/minimal-reproducible-example)) for this?

@papb Here is your SSCCE: https://github.com/papb/sequelize-sscce/pull/174/files

It shows that in the beforeCreate hook I can modify a property of the instance and that will save but the same is not true of beforeUpsert

**Comment by daweimau** [comment]
https://github.com/sequelize/sequelize/issues/13157 

^Probably duplicates this issue, but also includes an SSCCE @papb

**Comment by daweimau** [comment]
This is a ridiculously aggressive stale policy.

**Comment by reediculous456** [comment]
> This is a ridiculously aggressive stale policy.

Agreed
