### ISSUE TITLE
Select and parse JSON Array type

### ISSUE THREAD

**Issue by leonprou** [sequelize/sequelize#3577]
I know that JSON is pretty new to Postgres, and probably Sequelize doesn't fully support it yet. I want to perform a simple query of getting all chats for specific users, my model looks like this

```javascript
  var User = sequelize.define('User', {
...
    chats: {
      type: DataTypes.ARRAY(DataTypes.JSONB)
    }
...
})
```

so in Postgres I would do
```
SELECT chats FROM "Users" WHERE id = 1;
```

But writing this as a raw query in sequelize return the postgres array as string that I cannot parse.  So I'm using `array_to_json` function:

```javascript
db.sequelize.query('SELECT array_to_json(chats) FROM "Users" WHERE id = ?',
  { type: sequelize.QueryTypes.SELECT, replacements: [1] })
  .then(function(ans) {
    console.log(typeof ans[0].array_to_json);
    console.log(ans[0].array_to_json);
  }); 
```
And voila I'm getting the parsed js object as I wanted.

Now, is there nicer way to do this without the use of raw query?

**Comment by janmeier** [comment]
Is there any reason you are not simply calling `User.find`, that should parse the data properly?

You could perhaps call `db.sequelize.query('SELECT array_to_json(chats) FROM "Users" WHERE id = ?', User)`. This will return a built instance of user to the callback, the values should be parsed properly here as well

**Comment by mickhansen** [comment]
Any reason to use an array of JSONB rather than just JSONB?

**Comment by leonprou** [comment]
Thanks for answering :+1: 

@janmeier I cannot parse the result of User.find, because it's a postgres array. you can notice it wrapped with curly braces and not with brackets of JSON notation.

```javascript
db.User.find(1)
  .then(function(user) {
    console.log(typeof user.chats)
   // output: string
    console.log(user.chats)
  // output: {"{\"id\": 10, \"topics\": [\"love\"], \"userId\": 2}","{\"id\": 20, \"topics\": [\"peace\", \"understanding\"], \"userId\": 2}"}
  });
```

``` javascript
db.sequelize.query('SELECT array_to_json(chats) FROM "Users" WHERE id = ?', User)
```
Is working, but I'm looking for a way to do it without raw queries. 

@mickhansen 
With ordinary JSONB I'll need to rewrite all the json every time I'm adding a new object to array. With array of JSONB object I can add and remove objects without worry.

(There also some problems with adding objects to array. But I think they were mentioned before)

**Comment by mickhansen** [comment]
@leonprou Ah yeah, that does make atomic adds easier.

**Comment by janmeier** [comment]
@leonprou Could you try with latest master? I just tested and the array seems to be parsed fine.

If you still have issues, please provide a reproducible test case

**Comment by leonprou** [comment]
Working with sequelize 3.1.1 :+1: 

But I've got a problem with JSONB[]. the generated SQL statement assumes that the column is JSON[] type (it casts the json text to json[]) while mine is JSONB[] actually.

Maybe I could help to solve it

**Comment by mickhansen** [comment]
@leonprou Hmm i believe this was fixed in another PR recently, try out 3.2.0

**Comment by oysteingr** [comment]
I´m still seeing this issue in 3.3.2

..
foo: {
  type: DataTypes.ARRAY(DataTypes.JSONB)
}
..
//read object..
console.log(this.foo)
//result:
{"{\"id\": \"663d2295-c485-41ee-8700-632f1ff6f740\", \"secret\": \"123\"}"}

**Comment by janmeier** [comment]
@oysteingr Json arrays work, but there is still a bug with jsonb

Should be fixed when https://github.com/brianc/node-pg-types/pull/26 is released
