### ISSUE TITLE
Cannot update model in hook if using transactions and Promise.map()

### ISSUE THREAD

**Issue by canebat** [sequelize/sequelize#3775]
I have a transactions that builds a group and creates a bunch of users together. Once the group has been created, I update its slug field inside `afterCreate()` hook.

The problem is the the group model never gets updated in the hook. I think it has to do with `Promise.map` when creating the users, because if I comment that part out then the model does update the slug.

Everything else seems to get inserted just fine, just that the group doesn't get its slug field updated.

model:
```
var Group = sequelize.define('group', ....);

// Update slug field
Group.afterCreate(function(group, options) {
    var slug = makeSlug(group.name);
    group.updateAttributes({ slug: slug});
});
```

The transaction code:
```
var sequelize = Sequelize(config.database, config.username, config.password, config);
var new_users = [{ name: 'bob', id: 0}, { name; 'alice', id: 1}, { name: 'carol', id: 2 }];
var Promise = require('bluebird');

return sequelize.transaction(function(t) {
    return models.group.create({ name: groupname}, {transaction: t}).then(function(group) {
   
        // If I comment this part out, 'slug' gets updated, otherwise 'slug' will remain null!
       //     /*
        return Promise.map(new_users, function(user) {
            return models.user.create({ name: user.name, myid: user.id }, {transaction: t});
        }); 
        //    */       

    });
});
```

The make things stranger, I do see this SQL line:

```
Executing (default): UPDATE "groups" SET "slug"='test',"updatedAt"='2015-05-20 03:02:04.367 +00:00' WHERE "id" = 9
Executing (63f43e08-6f4d-4629-aa80-f892a0874145): COMMIT;
```

So the `group.updateAttributes()` does get run, but `slug` field will still remain `null` for some reason.

**Comment by mickhansen** [comment]
Should be fixed by https://github.com/sequelize/sequelize/pull/3694
What version are you running?

**Comment by canebat** [comment]
I was using 2.0.6, and now I updated to 3.0.1.

I'm still getting this problem.

**Comment by mickhansen** [comment]
Oh you're not even using CLS, i just assumed that was the issue.
The problem is that you're not using the transaction in the hook, hence the call not being part of the transaction.
