### ISSUE TITLE
Instance.reload() fails if instance was fetched with many-to-many association included

### ISSUE THREAD

**Issue by sheepcount** [sequelize/sequelize#3973]
I have two models, Meetings and Participants, in a many-to-many relationship. Reloading an instance fails if the association has been included in `findOne()/findAll()`:

```
db.Meeting.findOne({ include: [db.Participant] })
.then(function(result) {
  return result.reload(); // fails (works fine if { include: [db.Participant] } is omitted)
});

Unhandled rejection TypeError: Cannot read property 'name' of undefined                                                                               
    at C:\Users\username\src\playground\many-to-many\node_modules\sequelize\lib\model.js:275:39                                                           
    at Array.map (native)                                                                                                                             
    at conformOptions (C:\Users\username\src\playground\many-to-many\node_modules\sequelize\lib\model.js:259:37)                                          
    at C:\Users\username\src\playground\many-to-many\node_modules\sequelize\lib\model.js:291:7                                                            
    at Array.map (native)                                                                                                                             
    at conformOptions (C:\Users\username\src\playground\many-to-many\node_modules\sequelize\lib\model.js:259:37)                                          
    at null.<anonymous> (C:\Users\username\src\playground\many-to-many\node_modules\sequelize\lib\model.js:1162:5)                                        
    at tryCatcher (C:\Users\username\src\playground\many-to-many\node_modules\sequelize\node_modules\bluebird\js\main\util.js:24:31)                      
    at Promise._settlePromiseFromHandler (C:\Users\username\src\playground\many-to-many\node_modules\sequelize\node_modules\bluebird\js\main\promise.js:454:31)                                                                                                            
    at Promise._settlePromiseAt (C:\Users\username\src\playground\many-to-many\node_modules\sequelize\node_modules\bluebird\js\main\promise.js:530:18)    
    at Promise._settlePromiseAtPostResolution (C:\Users\username\src\playground\many-to-many\node_modules\sequelize\node_modules\bluebird\js\main\promise.js:224:10)                                                                                                                                   
    at Async._drainQueue (C:\Users\username\src\playground\many-to-many\node_modules\sequelize\node_modules\bluebird\js\main\async.js:187:12)             
    at Async._drainQueues (C:\Users\username\src\playground\many-to-many\node_modules\sequelize\node_modules\bluebird\js\main\async.js:192:10)            
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\username\src\playground\many-to-many\node_modules\sequelize\node_modules\bluebird\js\main\async.js:15:14)                                                                                                                                
    at processImmediate [as _immediateCallback] (timers.js:358:17)                                                                                    
```

My models are

```
module.exports = function(sequelize, DataTypes) {
  var Participant = sequelize.define('Participant', {
    firstName: DataTypes.STRING
  }, {
    classMethods: {
      associate: function(models) {
        models.Participant.belongsToMany(
          models.Meeting, 
          { through: 'MeetingParticipants' }
        );
      }
    }
  });
  return Participant;
};

module.exports = function(sequelize, DataTypes) {
  var Meeting = sequelize.define('Meeting', {
    description: DataTypes.STRING
  }, {
    classMethods: {
      associate: function(models) {
        models.Meeting.belongsToMany(
          models.Participant, 
          { through: 'MeetingParticipants' }
        );
      }
    }
  });
  return Meeting;
};
```

**Comment by mickhansen** [comment]
Seems like a bug.

**Comment by ikhos** [comment]
+1 Ran into this same issue. Did you manage to solve it?

**Comment by DanMMX** [comment]
I'm reloading `belongsToMany` associations having a model defined for the `through` property (not as string).

Also, you might need to define explicitly an `id` as primary key for that model on the association.

**Comment by stowns** [comment]
+1 exact same issue here. failing w/ 

```
Unhandled rejection TypeError: Cannot read property 'name' of undefined
```

**Comment by sushantdhiman** [comment]
FIXED in `v4`

**SSCCE Test**

```js
'use strict';

/*
 * Copy this file to ./sscce.js
 * Add code from issue
 * npm run sscce-{dialect}
 */

const Sequelize = require('./index');
const sequelize = require('./test/support').createSequelizeInstance();

const M = sequelize.define('M', {
  name: Sequelize.STRING
});
const N = sequelize.define('N', {
  name: Sequelize.STRING
});

M.belongsToMany(N, { through: 'MN' });
N.belongsToMany(M, { through: 'MN' });

sequelize.sync({ force: true })
.then(() => Sequelize.Promise.join(M.create({ name: 'XyZ1'}), N.create({ name: 'XyZ2'})))
.spread((m, n) => m.setNs([n]))
.then(() => M.findOne({ include: [N]}))
.then(m => m.reload())
.then(m => m.reload())
.then(m => m.reload())
.then(console.log);
```

**Output**

```js
▶ DIALECT=sqlite node sscce_template.js
Using database:  sequelize-test-88
M {
  dataValues: 
   { id: 1,
     name: 'XyZ1',
     createdAt: 2016-11-30T17:03:52.385Z,
     updatedAt: 2016-11-30T17:03:52.385Z,
     Ns: [ [Object] ] },
  _previousDataValues: 
   { id: 1,
     name: 'XyZ1',
     createdAt: 2016-11-30T17:03:52.385Z,
     updatedAt: 2016-11-30T17:03:52.385Z,
     Ns: [ [Object] ] },
  _changed: {},
  _modelOptions: 
   { timestamps: true,
     validate: {},
     freezeTableName: false,
     underscored: false,
     underscoredAll: false,
     paranoid: false,
     rejectOnEmpty: false,
     whereCollection: { id: 1 },
     schema: null,
     schemaDelimiter: '',
     defaultScope: {},
     scopes: [],
     hooks: {},
     indexes: [],
     name: { plural: 'Ms', singular: 'M' },
     omitNul: false,
     sequelize: 
      Sequelize {
        options: [Object],
        config: [Object],
        dialect: [Object],
        models: [Object],
        modelManager: [Object],
        connectionManager: [Object],
        importCache: {},
        test: [Object],
        queryInterface: [Object] },
     uniqueKeys: {},
     hasPrimaryKeys: true },
  _options: 
   { isNewRecord: false,
     _schema: null,
     _schemaDelimiter: '',
     include: [ [Object] ],
     includeNames: [ 'Ns' ],
     includeMap: { Ns: [Object] },
     includeValidated: true,
     attributes: [ 'id', 'name', 'createdAt', 'updatedAt' ],
     raw: true },
  hasPrimaryKeys: true,
  __eagerlyLoadedAssociations: [],
  isNewRecord: false,
  Ns: 
   [ N {
       dataValues: [Object],
       _previousDataValues: [Object],
       _changed: {},
       _modelOptions: [Object],
       _options: [Object],
       hasPrimaryKeys: true,
       __eagerlyLoadedAssociations: [],
       isNewRecord: false,
       MN: [Object] } ] }

```

**Comment by paul-at** [comment]
Seems like not fixed entirely. Ran into same symptoms with 4.33.4 (perhaps something in my setup was different from the test case though).

Was able to work around by adding
```
    id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true,
    },
```
to the many-to-many model.
