### ISSUE TITLE
3.4 is a BC

### ISSUE THREAD

**Issue by BridgeAR** [sequelize/sequelize#4133]
Right now 3.4 breaks findOrCreate, since it'll add a transaction if you use cls. This breaks [connect-session-sequelize] (https://github.com/mweibel/connect-session-sequelize) the way I use it right now: 

Here's the full case:
1) We use the same database connection for the sessions and the rest of our models. We use cls and have all our querys wrapped in a transaction.
2) The calls in connect-session-sequelize are not wrapped in a transaction.
3) After looking up the session while logging in we get the user information and also save the last login in our code and that part is wrapped in a transaction again. This block obviously opens a transaction and we return the result .
4) While doing this there is a findOrCreate call from the connect-session-sequelize and it did not use a transaction, so one is added, since this part is not wrapped into a transaction block.

So to conclude the transaction leaks into a place where it should not got to.

`WARNING:  there is already a transaction in progress`

```js
SequelizeDatabaseError: ERROR:  SET TRANSACTION ISOLATION LEVEL must be called before any query

    at Query.formatError (/home/ruben/fintura/finturanode/node_modules/sequelize/lib/dialects/postgres/query.js:427:14)
    at null.<anonymous> (/home/ruben/fintura/finturanode/node_modules/sequelize/lib/dialects/postgres/query.js:108:19)
    at emit (events.js:107:17)
    at NativeQuery.handleError (/home/ruben/fintura/finturanode/node_modules/pg/lib/native/query.js:41:10)
    at after (/home/ruben/fintura/finturanode/node_modules/pg/lib/native/query.js:59:19)
    at onError (/home/ruben/fintura/finturanode/node_modules/pg-native/index.js:160:5)
    at g (events.js:199:16)
    at emit (events.js:129:20)
    at Client._readError (/home/ruben/fintura/finturanode/node_modules/pg-native/index.js:81:8)
    at Client._read (/home/ruben/fintura/finturanode/node_modules/pg-native/index.js:121:19)
    at PQ.emit (events.js:104:17)
From previous event:
    at Query.run (/home/ruben/fintura/finturanode/node_modules/sequelize/lib/dialects/postgres/query.js:100:17)
    at /home/ruben/fintura/finturanode/node_modules/sequelize/lib/sequelize.js:713:18
From previous event:
    at Promise.then (/home/ruben/fintura/finturanode/node_modules/sequelize/lib/promise.js:21:17)
    at Transaction.prepareEnvironment (/home/ruben/fintura/finturanode/node_modules/sequelize/lib/transaction.js:179:6)
    at transactionResolver (/home/ruben/fintura/finturanode/node_modules/sequelize/lib/sequelize.js:1132:19)
    at /home/ruben/fintura/finturanode/node_modules/continuation-local-storage/context.js:74:17
    at Sequelize.transaction (/home/ruben/fintura/finturanode/node_modules/sequelize/lib/sequelize.js:1161:12)
    at /home/ruben/fintura/finturanode/server/config/passport.js:21:19
    at pass (/home/ruben/fintura/finturanode/node_modules/passport/lib/authenticator.js:353:9)
    at Authenticator.deserializeUser (/home/ruben/fintura/finturanode/node_modules/passport/lib/authenticator.js:358:5)
    at SessionStrategy.authenticate (/home/ruben/fintura/finturanode/node_modules/passport/lib/strategies/session.js:49:28)
    at attempt (/home/ruben/fintura/finturanode/node_modules/passport/lib/middleware/authenticate.js:341:16)
    at authenticate (/home/ruben/fintura/finturanode/node_modules/passport/lib/middleware/authenticate.js:342:7)
From previous event:
    at Sequelize.transaction (/home/ruben/fintura/finturanode/node_modules/sequelize/lib/sequelize.js:1161:12)
    at /home/ruben/fintura/finturanode/server/config/passport.js:21:19
    at pass (/home/ruben/fintura/finturanode/node_modules/passport/lib/authenticator.js:353:9)
    at Authenticator.deserializeUser (/home/ruben/fintura/finturanode/node_modules/passport/lib/authenticator.js:358:5)
    at SessionStrategy.authenticate (/home/ruben/fintura/finturanode/node_modules/passport/lib/strategies/session.js:49:28)
    at attempt (/home/ruben/fintura/finturanode/node_modules/passport/lib/middleware/authenticate.js:341:16)
    at authenticate (/home/ruben/fintura/finturanode/node_modules/passport/lib/middleware/authenticate.js:342:7)
    at Layer.handle [as handle_request] (/home/ruben/fintura/finturanode/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/ruben/fintura/finturanode/node_modules/express/lib/router/index.js:312:13)
    at /home/ruben/fintura/finturanode/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/ruben/fintura/finturanode/node_modules/express/lib/router/index.js:330:12)
    at next (/home/ruben/fintura/finturanode/node_modules/express/lib/router/index.js:271:10)
    at initialize (/home/ruben/fintura/finturanode/node_modules/passport/lib/middleware/initialize.js:62:5)
    at Layer.handle [as handle_request] (/home/ruben/fintura/finturanode/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/ruben/fintura/finturanode/node_modules/express/lib/router/index.js:312:13)
    at /home/ruben/fintura/finturanode/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/ruben/fintura/finturanode/node_modules/express/lib/router/index.js:330:12)
    at next (/home/ruben/fintura/finturanode/node_modules/express/lib/router/index.js:271:10)
    at /home/ruben/fintura/finturanode/node_modules/express-session/index.js:433:7
From previous event:
    at Promise.then (/home/ruben/fintura/finturanode/node_modules/sequelize/lib/promise.js:21:17)
    at SequelizeStore.getSession [as get] (/home/ruben/fintura/finturanode/node_modules/connect-session-sequelize/lib/connect-session-sequelize.js:48:49)
    at session (/home/ruben/fintura/finturanode/node_modules/express-session/index.js:404:11)
    at Layer.handle [as handle_request] (/home/ruben/fintura/finturanode/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/ruben/fintura/finturanode/node_modules/express/lib/router/index.js:312:13)
    at /home/ruben/fintura/finturanode/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/ruben/fintura/finturanode/node_modules/express/lib/router/index.js:330:12)
    at next (/home/ruben/fintura/finturanode/node_modules/express/lib/router/index.js:271:10)
    at /home/ruben/fintura/finturanode/server/config/express.js:108:9
    at Layer.handle [as handle_request] (/home/ruben/fintura/finturanode/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/ruben/fintura/finturanode/node_modules/express/lib/router/index.js:312:13)
    at /home/ruben/fintura/finturanode/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/ruben/fintura/finturanode/node_modules/express/lib/router/index.js:330:12)
    at next (/home/ruben/fintura/finturanode/node_modules/express/lib/router/index.js:271:10)
    at jsonParser (/home/ruben/fintura/finturanode/node_modules/body-parser/lib/types/json.js:100:40)
    at Layer.handle [as handle_request] (/home/ruben/fintura/finturanode/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/ruben/fintura/finturanode/node_modules/express/lib/router/index.js:312:13)
    at /home/ruben/fintura/finturanode/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/ruben/fintura/finturanode/node_modules/express/lib/router/index.js:330:12)
```

**Comment by mickhansen** [comment]
I'm not sure i understand how this breaks?
Getting the transaction from CLS is intended, since we added it.
Is the transaction leaking into where it shouldn't be? If that's the case it might be a CLS issue, or the old issue with when transaction is added to CLS.

Can you show some example code that explains the issue?

**Comment by mickhansen** [comment]
That actually might look like the issue with us setting the transaction before it's actually "ready".

**Comment by janmeier** [comment]
Isn't this the same as https://github.com/sequelize/sequelize/issues/3674? Which should be fixed now.

I wouldn't say that setting trnasaction from CLS is a BC break - it was a bug that we didn't do so to begin with. You can set `transaction = null` to prevent CLS from interfering :)

**Comment by mickhansen** [comment]
Yeah i would think that https://github.com/sequelize/sequelize/commit/b063d617e3e9636e01102b8855cc585795af83cc likely fixes this.

**Comment by BridgeAR** [comment]
b063d617e3e9636e01102b8855cc585795af83cc indeed fixed #3674 but this one is the result of #4062 and still occurs.

Adding the transaction the way it's done since that time seems to find "default" transaction blocks...

The findOrCreate will result in the following:
```
Executing (default): START TRANSACTION;
Executing (fd68dd09-0b67-4f3c-bcae-7f633ca5e2fc): SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
WARNING:  SET TRANSACTION can only be used in transaction blocks
Executing (fd68dd09-0b67-4f3c-bcae-7f633ca5e2fc): SET autocommit = 1;
Executing (fd68dd09-0b67-4f3c-bcae-7f633ca5e2fc): SELECT "sid", "data", "createdAt", "updatedAt" FROM "Sessions" AS "Session" WHERE "Session"."sid" = 'jusUV_3wh-bKh3ZI72atw6CGRo4vvGRi';
Executing (default): COMMIT;
WARNING:  there is no transaction in progress
Executing (default): UPDATE "Sessions" SET "data"='{"cookie":{"originalMaxAge":null,"expires":null,"httpOnly":true,"path":"/"},"passport":{}}',"updatedAt"='2015-07-17 10:46:31.586 +00:00' WHERE "sid" = 'jusUV_3wh-bKh3ZI72atw6CGRo4vvGRi'
```

**Comment by janmeier** [comment]
@BridgeAR default transaction block - not sure what you mean? It seems that findOrCreate uses the CLS transaction, which it should? Is the problem that foc commits the trasnaction?

**Comment by BridgeAR** [comment]
PR incoming

**Comment by mickhansen** [comment]
`START TRANSACTION` and `COMMIT` are not on transaction connection, that looks very odd.
