### ISSUE TITLE
place JSON in findOrCreate will throw error

### ISSUE THREAD

**Issue by lcjnil** [sequelize/sequelize#5691]
## What you are doing?

Background: sequelize(3.20.0), postgres(9.5.1)

I am trying to create a new schema, and insert some data, and it throw an error, here is the code. 

``` js
const Sequelize = require('sequelize');
const sequelize = require('./db');
const rateTypes = ['self', 'peer', 'oneToMany', 'manyToOne'];
const Promise = require('bluebird');

const RateGroup = sequelize.define('rate_group', {
  name: {
    type: Sequelize.STRING,
    field: 'name'
  },
  fields: {
    type: Sequelize.JSON,
    field: 'fields'
  },
  type: {
    type: Sequelize.ENUM(...rateTypes),
    field: 'type'
  }
});

Promise.coroutine(function *() {
  yield RateGroup.sync();
  yield RateGroup.findOrCreate({
    where: {
      name: 'test',
      type: 'self',
      fields: [{type: 'input', name: '123'}]
    }
  })
})().then(() => console.log('Rate Group Table Sync Success!'));

```

output is 

```
❯ node server/model/rate_group.js                                                                                                                                                             [12:42:07]
Executing (default): SELECT t.typname enum_name, array_agg(e.enumlabel ORDER BY enumsortorder) enum_value FROM pg_type t JOIN pg_enum e ON t.oid = e.enumtypid JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname='enum_rate_groups_type' GROUP BY 1
Executing (default): CREATE TABLE IF NOT EXISTS "rate_groups" ("id"   SERIAL , "name" VARCHAR(255), "fields" JSON, "type" "public"."enum_rate_groups_type", "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));
Executing (default): SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'rate_groups' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
Executing (e6ac25f0-7e27-4771-a79e-81375b0f4960): START TRANSACTION;
Executing (e6ac25f0-7e27-4771-a79e-81375b0f4960): SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
Executing (e6ac25f0-7e27-4771-a79e-81375b0f4960): COMMIT;
Unhandled rejection TypeError: val.replace is not a function
    at Object.SqlString.escape (/Users/nil/Documents/School_Project/new-rate/client/node_modules/sequelize/lib/sql-string.js:61:15)
    at Object.QueryGenerator.escape (/Users/nil/Documents/School_Project/new-rate/client/node_modules/sequelize/lib/dialects/abstract/query-generator.js:973:22)
    at /Users/nil/Documents/School_Project/new-rate/client/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2165:23
    at Array.map (native)
    at Object.QueryGenerator.whereItemQuery (/Users/nil/Documents/School_Project/new-rate/client/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2164:49)
    at /Users/nil/Documents/School_Project/new-rate/client/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1865:25
    at /Users/nil/Documents/School_Project/new-rate/client/node_modules/sequelize/node_modules/lodash/lodash.js:4040:15
    at baseForOwn (/Users/nil/Documents/School_Project/new-rate/client/node_modules/sequelize/node_modules/lodash/lodash.js:2573:24)
    at Function.forOwn (/Users/nil/Documents/School_Project/new-rate/client/node_modules/sequelize/node_modules/lodash/lodash.js:11030:24)
    at Object.QueryGenerator.whereItemsQuery (/Users/nil/Documents/School_Project/new-rate/client/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1864:9)
    at Object.QueryGenerator.getWhereConditions (/Users/nil/Documents/School_Project/new-rate/client/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2289:19)
    at Object.QueryGenerator.selectQuery (/Users/nil/Documents/School_Project/new-rate/client/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1454:28)
    at QueryInterface.select (/Users/nil/Documents/School_Project/new-rate/client/node_modules/sequelize/lib/query-interface.js:661:25)
    at null.<anonymous> (/Users/nil/Documents/School_Project/new-rate/client/node_modules/sequelize/lib/model.js:1408:32)
    at tryCatcher (/Users/nil/Documents/School_Project/new-rate/client/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/nil/Documents/School_Project/new-rate/client/node_modules/bluebird/js/release/promise.js:503:31)
```

however, if I replace `findOrCreate` with `create`, it would be working.

First time to submit a issues, if i was doing wrong, please inform me the right way

**Comment by vitaly-t** [comment]
The first problem that's reported, your code is missing the `.catch` section in the end.

You cannot use promises without `.catch`. Add, one, and then log what it is reporting as the problem. Then it will be possible to analyze.

**Comment by lcjnil** [comment]
Thanks to your feedback, i'd adjusted my code.

```js
const Sequelize = require('sequelize');
const sequelize = require('./db');
const rateTypes = ['self', 'peer', 'oneToMany', 'manyToOne'];
const Promise = require('bluebird');

const RateGroup = sequelize.define('rate_group', {
  name: {
    type: Sequelize.STRING,
    field: 'name'
  },
  fields: {
    type: Sequelize.JSON,
    field: 'fields'
  },
  type: {
    type: Sequelize.ENUM(...rateTypes),
    field: 'type'
  }
});

Promise.coroutine(function *() {
  yield RateGroup.sync();
  yield RateGroup.findOrCreate({
    where: {
      name: 'test',
      type: 'self',
      fields: [{type: 'input', name: '123'}]
    }
  })
})().then(() => console.log('Rate Group Table Sync Success!'))
  .catch((e) => console.log(e));
```

the log is 

```
 ❯ node server/model/rate_group.js                                                                                                                                                             [10:56:30]
Executing (default): SELECT t.typname enum_name, array_agg(e.enumlabel ORDER BY enumsortorder) enum_value FROM pg_type t JOIN pg_enum e ON t.oid = e.enumtypid JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname='enum_rate_groups_type' GROUP BY 1
Executing (default): CREATE TABLE IF NOT EXISTS "rate_groups" ("id"   SERIAL , "name" VARCHAR(255), "fields" JSON, "type" "public"."enum_rate_groups_type", "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));
Executing (default): SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'rate_groups' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
Executing (41f051ed-935a-4501-b175-0fd13823a7b2): START TRANSACTION;
Executing (41f051ed-935a-4501-b175-0fd13823a7b2): SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
Executing (41f051ed-935a-4501-b175-0fd13823a7b2): COMMIT;
[TypeError: val.replace is not a function]
```

**Comment by vitaly-t** [comment]
I have looked at the source of this problem:
```
[TypeError: val.replace is not a function]
```

The code look logically incomplete: https://github.com/sequelize/sequelize/blob/master/lib/sql-string.js#L15

If `val` is passed in as a function/generator, what is supposed to happen? The code is missing it. Therefore, I can't tell what is happening there.

Whoever is developing Sequelize should look at it. This looks like a bug.

**Comment by vitaly-t** [comment]
@lcjnil in addition, your transaction looks broken. It opens only after running the queries, and then tries to execute an empty commit.

**Comment by lcjnil** [comment]
@vitaly-t So it's probably a sequelize bug? Thanks to your recheck

**Comment by mickhansen** [comment]
`val.replace` is almost always bad input, although the error message is horrible.
By looking at the stack it looks like a where parameter is the issue, maybe the JSON field, in which case there's a bug with our library.

**Comment by janmeier** [comment]
Seems to be a problem where the array is being interpreted as an `$in` query, instead of JSON

**Comment by JLHwung** [comment]
I cannot reproduce this bug on sequelize(3.23.0), postgres(9.5.3), maybe it has been fixed?

**Comment by sushantdhiman** [comment]
I can still reproduce this on `master` 

**SSCCE Test**

```js
/*
 * Copy this file to ./sscce.js
 * Add code from issue
 * npm run sscce-{dialect}
 */

var Sequelize = require('./index');
var sequelize = require('./test/support').createSequelizeInstance();

const RateGroup = sequelize.define('rate_group', {
  name: {
    type: Sequelize.STRING,
    field: 'name'
  },
  fields: {
    type: Sequelize.JSON,
    field: 'fields'
  },
  type: {
    type: Sequelize.ENUM('self', 'peer', 'oneToMany', 'manyToOne'),
    field: 'type'
  }
});

sequelize.sync({ force: true })
.then(() => RateGroup.findOrCreate({
    where: {
      name: 'test',
      type: 'self',
      fields: [{ type: 'input', name: '123' }]
    }
  }))
.then(console.log)
.catch(console.error)
```

**Output**
```js
Using database:  sequelize-test-28
Error: Invalid value [object Object]
    at Object.escape (/var/www/sequelize/lib/sql-string.js:59:11)
    at Object.escape (/var/www/sequelize/lib/dialects/abstract/query-generator.js:949:22)
    at value.(.map.item (/var/www/sequelize/lib/dialects/abstract/query-generator.js:2134:66)
    at Array.map (native)
    at Object.whereItemQuery (/var/www/sequelize/lib/dialects/abstract/query-generator.js:2134:49)
    at _.forOwn (/var/www/sequelize/lib/dialects/abstract/query-generator.js:1853:25)
    at /var/www/sequelize/node_modules/lodash/lodash.js:4411:15
    at baseForOwn (/var/www/sequelize/node_modules/lodash/lodash.js:2654:24)
    at Function.forOwn (/var/www/sequelize/node_modules/lodash/lodash.js:12327:24)
    at Object.whereItemsQuery (/var/www/sequelize/lib/dialects/abstract/query-generator.js:1852:9)
    at Object.getWhereConditions (/var/www/sequelize/lib/dialects/abstract/query-generator.js:2266:19)
    at Object.selectQuery (/var/www/sequelize/lib/dialects/abstract/query-generator.js:1414:28)
    at QueryInterface.select (/var/www/sequelize/lib/query-interface.js:634:27)
    at Promise.try.then.then.then (/var/www/sequelize/lib/model.js:1328:34)
```

This issue is definitely appearing due to presence of `Array` in `findOrCreate` input. Error will go away if you change this
```js
 fields: [{ type: 'input', name: '123' }] // throw error
```

to this
```js
 fields: { type: 'input', name: '123' } // will work
```

**Comment by lcjnil** [comment]
I can still reproduce this issue in master.
