### ISSUE TITLE
Data unavailable when using nested attributes with include

### ISSUE THREAD

**Issue by FabriceMonnereau** [sequelize/sequelize#6316]
Hello,

I'm using sequelize to save my life for a long time now and i've recently come up with a strange behaviour. When i try to include an attribute from a nested included model, I'm expecting to be able to access it in the request result. But, obviously, if i'm here thats not the case ! :)

Did I do something wrong ?
PS. I'm using a Postgre backend and I'm use the master branch. I've test with the last release (3.23.3), but I've a bug resolve with this [pull request](https://github.com/sequelize/sequelize/pull/6297) in the master branch

Sequelize request: 
```
zone_result.findAll({
  where: {
    start_date: {$between: [request.query.start_date, request.query.end_date]},
    zone_id: request.params.zoneId,
  },   
  include: [{ model: product__zone_result, attributes:[],
    include: [{ model: product, attributes:['id'] }]
  }],  
  attributes:[
     'start_date',
     'end_date',
  ],   
  group: ['zone_result.id', 'product__zone_results.product.id'],
  order : ['product__zone_results.product.id', [sequelize.col(request.query.order_by), request.query.sort]],
}) 
```

SQL request:
```
SELECT "zone_result"."id",
"zone_result"."start_date",
"zone_result"."end_date",
"product__zone_results.product"."id" AS "product__zone_results.product.id"
FROM "zone_result" AS "zone_result"
LEFT OUTER JOIN "product__zone_result" AS "product__zone_results"
ON "zone_result"."id" = "product__zone_results"."zone_result_id"
LEFT OUTER JOIN "product" AS "product__zone_results.product"
ON "product__zone_results"."product_id" = "product__zone_results.product"."id"
WHERE "zone_result"."start_date"
BETWEEN '2016-06-19 00:00:00.000 +00:00'
AND '2016-06-19 23:59:59.000 +00:00'
AND "zone_result"."zone_id" = 1
GROUP BY "zone_result"."id", "product__zone_results.product"."id"
ORDER BY "product__zone_results.product"."id", "start_date" ASC;
```
I'm expecting to have something like a "product__zone_results.product.id" field in the result...

The result:
```
[ zone_result {
    dataValues: 
     { start_date: 2016-06-19T18:00:00.000Z,
       end_date: 2016-06-20T04:00:00.000Z },
    _previousDataValues: 
     { start_date: 2016-06-19T18:00:00.000Z,
       end_date: 2016-06-20T04:00:00.000Z },
    _changed: {},
    _modelOptions: 
     { timestamps: false,
       validate: {},
       freezeTableName: true,
       underscored: true,
       underscoredAll: false,
       paranoid: false,
       rejectOnEmpty: false,
       whereCollection: [Object],
       schema: null,
       schemaDelimiter: '',
       defaultScope: {},
       scopes: [],
       hooks: {},
       indexes: [],
       name: [Object],
       omitNul: false,
       sequelize: [Object],
       uniqueKeys: {},
       hasPrimaryKeys: true },
    _options: 
     { isNewRecord: false,
       _schema: null,
       _schemaDelimiter: '',
       include: [Object],
       includeNames: [Object],
       includeMap: [Object],
       includeValidated: true,
       attributes: [Object],
       raw: true },
    hasPrimaryKeys: true,
    __eagerlyLoadedAssociations: [],
    isNewRecord: false } ]
```

Model zone_result:
```
(function() {

  'use strict';
  var Sequelize = require('sequelize');
  var product__zone_result = require('./product__zone_result');

  module.exports = function(sequelize){
    if (!sequelize.isDefined('zone_result')){
      var zone_result = sequelize.define('zone_result', {
        id: {type: Sequelize.BIGINT, primaryKey:true, autoIncrement:true},
        start_date : Sequelize.DATE,
        end_date : Sequelize.DATE,
      }); 

      zone_result.hasMany(product__zone_result(sequelize));
      return zone_result;
    } else {
      return sequelize.models.zone_result;
    }   
  };  

})();
```

Model product__zone_result:
```
(function() {

  'use strict';
  var Sequelize = require('sequelize');

  module.exports = function(sequelize){
    if (!sequelize.isDefined('product__zone_result')){
      var product__zone_result = sequelize.define('product__zone_result', {
        id: {type: Sequelize.BIGINT, primaryKey:true, autoIncrement:true},
        volume_theoretical: Sequelize.NUMERIC,
        volume_real: Sequelize.NUMERIC,
        dose: Sequelize.INTEGER,
        container_theoretical: Sequelize.NUMERIC,
        container_real: Sequelize.NUMERIC
      }); 

      return product__zone_result;
    } else {
      return sequelize.models.product__zone_result;
    }   
  };  


})();
```

Model product:
```
(function() {

  'use strict';
  var Sequelize = require('sequelize');
  var product__zone_result = require('./product__zone_result');
  
  module.exports = function(sequelize){
    if (!sequelize.isDefined('product')){
      var product = sequelize.define('product', {
        id: {type: Sequelize.BIGINT, primaryKey:true, autoIncrement:true},
        label: {type: Sequelize.TEXT, unique:'unique'},
        capacity: {type: Sequelize.NUMERIC, unique:'unique'},
        viscosity: Sequelize.NUMERIC,
        subscriber_id: {type: Sequelize.BIGINT}
      }); 

      product__zone_result(sequelize).belongsTo(product);
      return product;
    } else { 
      return sequelize.models.product;
    } 
  };
})();
```

**Comment by sushantdhiman** [comment]
#6297 was a simple fix, But its being released in `v4` currently, you can take that code and submit a PR for `v3`. we will merge it and release new version for you :)

**Comment by sushantdhiman** [comment]
As its already fixed by #6297, I am closing this issue. @FabriceMonnereau you are free to submit a PR to port #6297 to `v3` branch

**Comment by FabriceMonnereau** [comment]
OK I see my english isn't so good. I think we misunderstood. 

My last sentence was intended to meant:

> PS. I'm using Postgre backend and the master branch. I did test on the last release (3.23.3) but it had _another_ bug (the 6297) so the one I describe did not even appeared.


To be sure to be clear, the 6297 did not resolve this issue ;)

**Comment by FabriceMonnereau** [comment]
any news ? :-)

**Comment by felixfbecker** [comment]
@FabriceMonnereau I'm confused, are you using the master branch or not? Also, it might be because you set `attributes` on the outer options to only include the start_date and end_date

**Comment by FabriceMonnereau** [comment]
Thanks for your reponse.
I use the master branch and i have made a npm update today for the tests.
I have made a test without attributes and it's the same result.

**Comment by FabriceMonnereau** [comment]
Help me, @felixfbecker , you're my only hope :)

**Comment by FabriceMonnereau** [comment]
No one has any idea ?

**Comment by sushantdhiman** [comment]
@FabriceMonnereau If its not fixed, I am reopening the issue
