### ISSUE TITLE
select json attributes 

### ISSUE THREAD

**Issue by frogcjn** [sequelize/sequelize#6406]
```javascript
const existedIds = (await AEntity.findAll({
        attributes: [ [sequelize.json("aStruct.id"), "aStruct.id"]],
        where: { aStruct: { someKey: "someValue" } },
        logging: console.log
    })).map(model => model.get("aStruct.id"))
```
will lead to
`SequelizeDatabaseError: column "astruct" does not exist`

the SQL sentence:
```postgresQL
Executing (default): SELECT aStruct#>>'{id}' FROM "aEntity" AS "aEntity" WHERE (("aEntity"."aStruct"#>>'{someKey}') = 'someValue');
```

`SELECT aStruct#>>'{id}'` should be `SELECT "aStruct"#>>'{id}'`

**Comment by frogcjn** [comment]
And by the way, await AEntity.findAll() will always return entire entities, I just want the value array, how can I get the value array only with sequelize API?

**Comment by janmeier** [comment]
`raw: true` will give you to raw result set (but this is completely raw, which also means includes won't be parsed

**Comment by frogcjn** [comment]
I'll make PR to resolve the quote issue.

**Comment by janmeier** [comment]
Hmm, we do have some tests for this, seems to work https://github.com/sequelize/sequelize/blob/9f0b5d1af24f6741aadebba411a21dc1d774d2c1/test/integration/dialects/postgres/dao.test.js#L170

**Comment by frogcjn** [comment]
The key point is the fields name contains upper case latter. So if there is a test for this case?

**Comment by janmeier** [comment]
Ah yeah, probably not :)

**Comment by frogcjn** [comment]
And even though the uppercase quote problem solved, how can I get the attributes from the entity array?
```
const existedIds = await AEntity.findAll({
        attributes: [ sequelize.json("aStruct.id")],
        where: { aStruct: { someKey: "someValue" } },
        logging: console.log
    })
```
existedIds[0] will contain no fields.

**Comment by frogcjn** [comment]
existedIds.get("siteIdStruct.id") is undefined.

only existedIds.$options.attributes[0].path has a value of 'aStruct.id'

**Comment by janmeier** [comment]
You should give it an alias `attributes: [ [sequelize.json("aStruct.id"), 'id']]`

**Comment by frogcjn** [comment]
How about using aggregate with json field?
MyModel.aggregate(sequelize.json(), 'DISTINCT', { plain: false }).then(...)

**Comment by janmeier** [comment]
What about it? Try it out and tell me what happens :)

**Comment by frogcjn** [comment]
OK I'll summarize using find All with json attribute

const existedIds = (await AEntity.findAll({
        attributes: [ [sequelize.json("aStruct.id"), "aStruct.id"]],
        where: { aStruct: { someKey: "someValue" } },
        logging: console.log
    })).map(model => model.get("aStruct.id"))

**Comment by frogcjn** [comment]
unfortunately , it is not possible use sequelize API to query aggregate with json attributes:

`SELECT DISTINCT("aStruct -> 'id'") AS "DISTINCT" FROM ...`
should be
`SELECT DISTINCT("aStruct"-> 'id') AS "DISTINCT" FROM ...`

**Comment by sushantdhiman** [comment]
Fixed in #6407

**Comment by Djalmar** [comment]
i'm using versión 3.33.0, it still not working can anyone give me an advise

**Comment by evenfrost** [comment]
How can one select and get specific JSON attributes without aliasing, as is? E.g. running this:
```js
AEntity.findAll({ attributes: [[sequelize.json("aStruct.id"), "aStruct.id"]] });
```
and getting in the result
```js
[{
  aStruct: {
    id: 123
  }
}]
```
instead of
```js
[{
  "aStruct.id": 123
}]
