### ISSUE TITLE
`removeAttribute('id')` results in `undefined: null` data value

### ISSUE THREAD

**Issue by broofa** [sequelize/sequelize#7318]
Removing the `id` property results in an "undefined" property being set on the dataValues object.

```
> var Thing = db.sequelize.define('Thing')

> console.log(model.build().dataValues)
{ id: null }

> model.removeAttribute('id')

> console.log(model.build().dataValues)
{ undefined: null }

> model.build().toJSON()
{ undefined: null }
```

__Dialect:__ mysql
__Database version:__ mysql  Ver 14.14 Distrib 5.7.16, for osx10.11 (x86_64) using  EditLine wrapper
__Sequelize version:__ 3.30.2

**Comment by sushantdhiman** [comment]
Its a bug, with very low priority.

**SSCCE**
```js
const Entry = sequelize.define('Entry', {
  description: {
    type: Sequelize.STRING
  },
  value: {
    type: Sequelize.DECIMAL(17, 2),
    allowNull: false
  }
});

let instance = Entry.build({ description: 'Hello', value: 23 });
console.log(instance.toJSON());

Entry.removeAttribute('value');
instance = Entry.build({ description: 'Hello', value: 23 });
console.log(instance.toJSON());

Entry.removeAttribute('description');
Entry.removeAttribute('id');
instance = Entry.build({});
console.log(instance.toJSON());
```

**OUTPUT**
```js
{ id: null, description: 'Hello', value: 23 }
{ id: null, description: 'Hello' }
{ undefined: null }
```

**Comment by sushantdhiman** [comment]
Fixed in https://github.com/sequelize/sequelize/pull/7382

**Comment by ratulSharker** [comment]
I'm still facing this issue. Removed `id` using `Model.removeAttribute(`id`)`, then including `hasMany` association causes `null` values to appear.
