### ISSUE TITLE
Limit is broken for findAll and findAndCountAll with include

### ISSUE THREAD

**Issue by Alexsey** [sequelize/sequelize#7344]
Consider we have a two simple models "Events" and "Tags" with many-to-many relation and we want to get all events with specific tag. And we want to limit maximum number of response items.

(Consider you are using ```NodeJS``` 7.6+ with ```async/await``` or ```Babel``` with ```async/await``` plugin)
```js
'use strict'

const Sequelize = require('sequelize')

const dbConfig = {
    type: 'mysql', user: 'root', password: 'root',
    database: 'db', host: 'localhost'
}

;(async () => {
    const sequelize = new Sequelize(
        dbConfig.database, dbConfig.user, dbConfig.password, {
            host: dbConfig.host,
            dialect: dbConfig.type,
            pool: {max: 100, min: 0, idle: 10000},
            dialectOptions: {
                charset: 'utf8_general_ci',
            }
        }
    )
    await sequelize.authenticate()

    const Events = sequelize.define('events', {
        id: {type: Sequelize.INTEGER, primaryKey: true, autoIncrement: true},
        title: {type: Sequelize.STRING}
    }, {timestamps: false})

    const Tags = sequelize.define('tags', {
        name: {type: Sequelize.STRING}
    }, {timestamps: false})

    const EventsTags = sequelize.define('events_tags', {}, {timestamps: false})

    Events.belongsToMany(Tags, {through: EventsTags})
    Tags.belongsToMany(Events, {through: EventsTags})

    await sequelize.sync()

    await Promise.all([
        Events.bulkCreate([
            {title: 'event_1'}, {title: 'event_2'},
            {title: 'event_3'}, {title: 'event_4'}
        ]),
        Tags.bulkCreate([
            {name: 'tag_1'}, {name: 'tag_2'},
            {name: 'tag_3'}, {name: 'tag_4'},
        ])
    ])
    await EventsTags.bulkCreate([
        {eventId: 1, tagId: 1}, {eventId: 2, tagId: 2},
        {eventId: 3, tagId: 3}, {eventId: 4, tagId: 1}
    ])

    const eventsWithTag1 = await Events.findAndCountAll({
        limit: 3,
        include: [{
            model: Tags,
            where: {name: 'tag_1'}
        }]
    })

    console.log('found events with tag_1:', eventsWithTag1.rows.length) // 1
    console.log('count events with tag_1:', eventsWithTag1.count) // 2

    await sequelize.close()
})()
```
This query will found only one event:
```console.log('found events with tag_1:', eventsWithTag1.rows.length)``` is logging ```1```

but it should found two:
```console.log('found events with tag_1:', eventsWithTag1.rows.length)``` must log ```2```
because there are two of them and ```limit``` is 3

If we remove ```limit``` or set it to 4+ or change the sequence of ```EventsTags``` creation to
```js
EventsTags.bulkCreate([
  {eventId: 1, tagId: 1}, {eventId: 2, tagId: 2},
  {eventId: 4, tagId: 1}, {eventId: 3, tagId: 3}
])
```
results in that the request will found both events
```console.log('found events with tag_1:', eventsWithTag1.rows.length)``` will log ```2```

So ```limit``` should limit the maximum number of records in the result, but it limits the number of records in intermediate query and final result is unpredictable.

If you put ```findAll``` instead of ```findAndCountAll``` you will face the same problem

This is generated SQL for the last select query:
```sql
SELECT
  `events`.*, `tags`.`id` AS `tags.id`, `tags`.`name` AS `tags.name`,
  `tags.events_tags`.`eventId` AS `tags.events_tags.eventId`,
  `tags.events_tags`.`tagId` AS `tags.events_tags.tagId`
FROM
  (
    SELECT
      `events`.`id`, `events`.`title`
    FROM
      `events` AS `events`
    WHERE
      (
        SELECT
          `events_tags`.`eventId`
        FROM
          `events_tags` AS `events_tags` 
        INNER JOIN
            `tags` AS `tag`
          ON
            `events_tags`.`tagId` = `tag`.`id`
        WHERE
          (
            `events`.`id` = `events_tags`.`eventId`
          ) LIMIT 1 
      ) IS NOT NULL LIMIT 3
  ) AS `events`
INNER JOIN
    (
      `events_tags` AS `tags.events_tags`
      INNER JOIN
          `tags` AS `tags`
        ON
          `tags`.`id` = `tags.events_tags`.`tagId`
    )
  ON
      `events`.`id` = `tags.events_tags`.`eventId`
    AND
      `tags`.`name` = 'tag_1';
```

I have try this on MySQL 5.7 and Sequelize 4.0.0-2 and 3.30.2

**Comment by Alexsey** [comment]
Hm... it looks like to fix the query we need to move ``` AND `tags`.`name` = 'tag_1'``` from the tail to the inner query before the ```LIMIT 1```

Looks like this
```SELECT `events`.*, `tags`.`id` AS `tags.id`, `tags`.`name` AS `tags.name`, `tags.events_tags`.`eventId` AS `tags.events_tags.eventId`, `tags.events_tags`.`tagId` AS `tags.events_tags.tagId` 
FROM (SELECT `events`.`id`, `events`.`title` 
    FROM `events` AS `events` WHERE (
        SELECT `events_tags`.`eventId` 
        FROM `events_tags` AS `events_tags` INNER JOIN `tags` AS `tag` ON `events_tags`.`tagId` = `tag`.`id` WHERE (`events`.`id` = `events_tags`.`eventId`) AND `tag`.`name` = 'tag_1' LIMIT 1 
    ) IS NOT NULL LIMIT 4
    ) AS `events` 
    INNER JOIN (`events_tags` AS `tags.events_tags` 
    INNER JOIN `tags` AS `tags` ON `tags`.`id` = `tags.events_tags`.`tagId`) ON `events`.`id` = `tags.events_tags`.`eventId`
```
is the right query

**Comment by Alexsey** [comment]
I have looked a little bit in the source code and bug is probable place of bug is in <a href="https://github.com/sequelize/sequelize/blob/master/lib/dialects/abstract/query-generator.js#L756">this</a> function, somewhere in ```include``` processing. Owner of the code base should understand it better. Just run my example (it is complete and dependableness)

**Comment by lassombra** [comment]
This also affected me.  As a workaround I did an unlimited, unsorted initial query and then introduced pagination on the result set, which eliminates any server performance benefits from pagination, especially if we get to scale (I'm expecting to stop around 500 records at any time, but this could really slow down with much more than that, especially with nested filters)

**Comment by Alexsey** [comment]
Checked on 4.0.0 - still bug is still there

**Comment by Alexsey** [comment]
As mentioned in https://github.com/sequelize/sequelize/issues/4716 - workaround is to add `subQuery: false`. Also https://github.com/sequelize/sequelize/issues/5715 is looks like related

**Comment by rrjohnson85** [comment]
@Alexsey `subQuery: false` can help, but can lead to other issues.  For example, I'm noticing an incorrect count for some of my queries now.

**Comment by nicholasli137** [comment]
I am also getting same issue with `limit` in `findAll()` even though I have added `subQuery: false`. Are there any ways for me to get correct number of results?

**Comment by Alexsey** [comment]
@nicholasli137 when I met this bug I have ended up writing raw SQL query. If you will find any other solution - please write here about it

**Comment by Alexsey** [comment]
As I mentioned above the problem is that limit is applying to subquery instead of query. @mickhansen if we change [in your code](https://github.com/sequelize/sequelize/blob/master/lib/dialects/abstract/query-generator.js#L1173)
```
// Add LIMIT, OFFSET to sub or main query
const limitOrder = this.addLimitAndOffset(options, mainTable.model);
if (limitOrder && !options.groupedLimit) {
  if (subQuery) {
    subQueryItems.push(limitOrder);
  } else {
    mainQueryItems.push(limitOrder);
  }
}
```
to
```
// Add LIMIT, OFFSET to sub or main query
const limitOrder = this.addLimitAndOffset(options, mainTable.model);
if (limitOrder && !options.groupedLimit) {
  mainQueryItems.push(limitOrder);
}
```
the bug goes away. Can you please comment may this be the right solution or will this lead to a new bugs?

**Comment by VladimirPal** [comment]
Hi guys! Any news about this issue?

**Comment by Ieremchuk** [comment]
bump

**Comment by DavidVeloso** [comment]
Hi guys! Any news about this issue?

**Comment by austinksmith** [comment]
I am also encountering this issue, it's becoming a real pain point with the current application stack I am working on, query is necessary to have the includes for proper tagging and filtering functionality but this throws off the limit param to essentially be useless and random. Removing subQuery: false will resolve the limit issues but will then introduce issues with the tag include not working and returning invalid counts. Eg. Count: 1 but no rows.

```js
File.findAndCountAll({
		distinct: true,
		subQuery: false, // This option is required for tag (include) functionality to work, 100% undocumented in sequalize. - Austin K. Smith 10/9/17
		offset: (req.query.start ? parseInt(req.query.start, 10) : 0),
		limit: (req.query.number ? parseInt(req.query.number, 10) : 12),
		where: _where,
		order: [
			[req.query.sort, req.query.order]
		],
		include: [
			{ 
				model: FileCategory, 
				as: 'categories', 
				through: 'fileFileCategories', 
				foreignKey: 'fileId', 
				where: _filters.category ? {
					id: _filters.category.id 
				} : null },
			{ 
				model: FileTag, 
				as: 'tags', 
				through: 'fileFileTags', 
				foreignKey: 'fileId',
				where: _filters.tag ? {
					id: _filters.tag.id 
				} : null },
			{ 
				model: Role, 
				as: 'roles', 
				through: 'fileRoles', 
				foreignKey: 'fileId', 
				where: _roleWhere, 
				required: false 
			}
		]
	}).then(function (files) {
		if (!files) {
			return res.status(404).send({
				message: 'No files found'
			});
		} else {
			return res.json(files);
		}
	}).catch(function (err) {
		winston.error('files.server.controller', err);
		// not secure send only generic message
		return res.status(500).send('files.server.controller error');
	});

```

Sub Query false is not an acceptable solution as this also causes problems with `distinct: true` not working properly and thus ending up with duplicate records that I have to manually strip out of the final result set, this is both inefficient and problematic as it then makes the pagination "remaining" count inaccurate.

**Comment by fabienvauchelles** [comment]
+1

**Comment by DavidVeloso** [comment]
+1

**Comment by lucasmendes2105** [comment]
+1

**Comment by Alexsey** [comment]
@sushantdhiman it looks like there are a lot of people who are stumbling on this one. Could you please add a `bug` label on it so when someone else would search on it he would see that this issue is really about something

**Comment by alifaff** [comment]
Any update on the bug resolution?  Any alternatives that we could take advantage of in the meantime?

**Comment by vkhattar** [comment]
unable to paginate because of this bug, is the only solution to write raw sql ?

**Comment by nghenglim** [comment]
Have encountered this issue in production code using Postgres. Seems like sequelize have problem including 1:m or m:m relationship. 

IMHO, if this bug cannot be resolved soon, a warning message should be shown in the console.log whenever 1:m or m:m include is being used. I'll rather unable to include 1:m or m:m at all if the result is inconsistence.

**Comment by SirWojtek** [comment]
I found another workaround working for me. I've just added `distinct: true` to my `findAndCountAll` query.

**Comment by DaniilVystoskiy** [comment]
@SirWojtek [As already mentioned above](https://github.com/sequelize/sequelize/issues/7344#issuecomment-335212889), it is not workaround as it will brake results with pagination case.

+1

Devs, please, look closer to this problem, it brings unresolvable issues. E.g. this query:
```
var searchObject = {
        distinct: 'id',
        attributes: ['id', 'hidden', 'sortIndex'],
        where: {
          type: 'hardware'
        },
        include: [{
          model: SaleComponents,
          as: 'prices',
          where: {
            hidden: false,
            $or: [
              {
                regionId: regionId
              },
              {
                regionId: null
              }
            ]
          }
        }],
        limit: limit,
        offset: offset,
        order: productsOrder,
        subQuery: false
      };
```
leads to this:
![Pagination broken](https://storage.googleapis.com/openscreenshot/M/H/y/rk9zWGyHM.png)

**Comment by NotAmaan** [comment]
I don't think this issue is going away anytime soon as there is no work being done on this. Don't get me wrong, appreciate Sequelize as an open source project, but when you are using something this popular, you wouldn't expect an issue this major to exist and be ignore. Before somebody tells me to submit a PR myself, trust me I would but I don't have the SQL expertize require to handle this. 

We've been working on a big API and are now testing knex.js along with Objection.js, this is a huge setback in terms of time and resources which would be spent on re-doing things the knex.js way.

**Comment by mickhansen** [comment]
@NotAmaan I can appreciate your situation, consider that Sequelize is probably at something like two active maintainers right now, that both probably work in startups or similar.

Personally i don't see a huge reason to have findAndCountAll at all when it's so simply implemented in userland without any of the huge edge cases.

**Comment by jamiesoncj** [comment]
Unfortunately I too am in the situation where this issue is causing headaches in our product (we've worked around it by doing pagination in the application after loading all rows from the DB but it won't scale for us much longer), and while I would like to submit a PR for the fix I just don't have enough knowledge of Sequelize under the hood.

However I would be very happy to contribute to a "bug bounty" if this might help us to get a fix in place for this. Is this something that would be of interest to any experienced Sequelize contributors? I would happily put GBP 100 into the pot. Perhaps any others facing this issue who could contribute can speak up too. Apologies in advance if this is deemed not appropriate by the maintainers!

**Comment by NotAmaan** [comment]
@mickhansen That is understandable about maintainer it being able to fix everything on their own for an open source project and I respect the fact that you guys are still looking into the issues. 

The main problem we faced is querying data with association. It doesn't necessarily break the limit everytime, there are workarounds to that as mentioned in other posts, but I have not yet found any solution which works perfectly. In short even if you're using `findAll` with `distinct`, `where: {$association.id$}`, `include[{model: AssociationModel}]`, and `order: [['colName', 'DESC']],`, you're bound to face one or the other issues. And I wouldn't consider this an edge case either, we're building a search UI which pretty much filter data in our database and displays result. There are thousands of items so we definitely need pagination. I could setup a test environment if any maintainer is willing to spend some time looking into it.

**Comment by NotAmaan** [comment]
@jamiesoncj count me in as well. If this can help us get this issue resolved, I am willing to contribute $120 to towards the bug as well.

**Comment by mickhansen** [comment]
In general joins and limits are a complex thing in the land of SQL.
You need to use subqueries usually which Sequelize has poor support for - but that is generally how i solve the issue in personal projects, i use include.seperate and subqueries (these days it's mostly all graphql where dataloader comes in handy).

I personally no longer work on this project, but bounties used to be appreciated (there's a bounty page somewhere).
But do keep in mind that even if a fix is possible on a issue like this each different case is likely to take multiple hours to solve.

**Comment by Alexsey** [comment]
I have looked for and found that this issue is already on [bountysource](https://www.bountysource.com/issues/42820407-limit-is-broken-for-findall-and-findandcountall-with-include). I'm not working with sequelize any more but it was give me that much pain when I found it that I'm also willing to give some money on it :)

**Comment by jamiesoncj** [comment]
Thanks @Alexsey for finding that on Bountysource - I have added my USD 150 bounty there and see you have also added a bounty... hopefully someone will find it appetising enough to take on the issue :smile:

**Comment by ruanjiayou** [comment]
distinct is boolean type.in findAndCountAll() method, set it true, defaultly,count(distinct(primaryKey))?but still count(distinct(*))...unexpected...英语不好(english is not good)

**Comment by DaniilVystoskiy** [comment]
@ruanjiayou 用中文写，我翻译=)

**Comment by NotAmaan** [comment]
Moved to knex.js with objection.js. Much faster in terms of the query as well. findAndCountAll (with 5 asssociations included) was taking ~3000ms in sequelize is taking me ~400ms with knex. 
Also, sequelize.js's findAndCount all has `distinct` applied to the count query but not the select query which leads to duplicate results.

**Comment by mattdiamond** [comment]
I think I may be facing the same problem as @ruanjiayou (if I understand their post correctly)...

using `distinct: true` solves count problems for some of our queries, but it breaks other queries by generating SQL like this:

```sql
SELECT count(DISTINCT(*)) AS "count" FROM ...
```

which leads to `syntax error at or near "*"`.

I vaguely recall another post saying that `distinct: true` only needed to be applied to specific queries, but I forget what that distinction was. Maybe it had to do with the presence or absence of subqueries?

**Comment by mickhansen** [comment]
Knex is a query builder, you'll always see better performance with raw queries/query builders rather than an ORM.

**Comment by nghenglim** [comment]
@mickhansen agree and knex is quite irrelevant to this issue. 

For me I am perfectly fine with sequelize to only query 1:1 relationship. The problem with sequelize is it give documentation on using function that give inconsistence result. This result normally can only be found out when you are querying against a lot of pages.

As a library with so much usage, I really think it should add obvious documentation/warning message for developer (as I don't think this is a bug that can be quickly solved).

**Comment by rlindgren** [comment]
Adding my two cents to this discussion...

As an ORM, Sequelize is great and the query language is user-friendly and descriptive, like mongoDB.  In so many ways, Sequelize does what we want it to do, precisely how we want to do it.  The deal-breaker problems that I think most people encounter are related to the query builder doing unexpected things, as in the case of this and numerous similar issues posted here.  Some of these issues have existed for years without resolution, not due to lack of interest in fixing them, but due to the complex nature of the query builder.

If Sequelize has 2 primary maintainers, then the code should be as maintainable as possible to allow for meaningful contributions to be made by the community, with a low barrier to entry.

My suggestion, with all due respect, is to consider out-sourcing the query builder to something like knex.js, which provides a clear and human-readable interface for building queries.  I understand that this is no trivial undertaking, but I am willing to contribute to this effort.  I, admittedly, am not particularly familiar with the inner workings of the Sequelize codebase and I haven't really used knex.js in any significant capacity, so I know there will be hurdles and other issues, but it's hard to believe that these longstanding issues can or will be resolved without some fairly major overhaul...

**Comment by Alexsey** [comment]
@rlindgren I'm afraid none of that 2 primary maintainers are participants in this discussion. You should call them here or create a new issue and link this one (and maybe others) to it

**Comment by andrzejWilde** [comment]
It may be a particular design of my DB but I managed to get LIMIT and OFFSET working for me with this approach:
- queries without filtering on included models or with filtering on 1-1 included models: don't specify `subQuery`,
- queries with filtering on n-m models - specify `subQuery: false`.

And for count I use a dirty hack:

```
const original = sequelize.query.bind(sequelize);
sequelize.query = function(...args){
  args[0] = args[0].replace('count(', 'count(distinct ');
  return original(...args);
};
```
Maybe it will help someone as a hotfix.

**Comment by saighost** [comment]
set distinct and clo in findAndCountAll
try like this:
```
 const eventsWithTag1 = await Events.findAndCountAll({
      // attributes: ['id'],
      distinct: false,
      col: 'events.id',
      limit: 3,
      include: [
        {
          model: Tags,
          where: { name: "tag_1" },
        }
      ],
      subQuery: false
    });

    console.log("found events with tag_1:", eventsWithTag1.rows.length); // 2
    console.log("count events with tag_1:", eventsWithTag1.count); // 2
  
```

**Comment by saighost** [comment]
SQL when set distinct true 
```
SELECT count(DISTINCT(`events`.`id`)) AS `count` FROM `events` AS `events` INNER JOIN (`events_tags` AS `tags.events_tags` INNER JOIN `tags` AS `tags` ON `tags`.`id` = `tags.events_tags`.`tagId`) ON `events`.`id` = `tags.events_tags`.`eventId` AND `tags`.`name` = 'tag_1';
Executing (default): SELECT `events`.`id`, `events`.`title`, `tags`.`id` AS `tags.id`, `tags`.`name` AS `tags.name`, `tags.events_tags`.`eventId` AS `tags.events_tags.eventId`, `tags.events_tags`.`tagId` AS `tags.events_tags.tagId` FROM `events` AS `events` INNER JOIN (`events_tags` AS `tags.events_tags` INNER JOIN `tags` AS `tags` ON `tags`.`id` = `tags.events_tags`.`tagId`) ON `events`.`id` = `tags.events_tags`.`eventId` AND `tags`.`name` = 'tag_1' LIMIT 3;
```

**Comment by rusekr** [comment]
@saighost have you tried this on postgres?

**Comment by saighost** [comment]
@rusekr sorry, I only use with MySql.
But in document 'distinct' can be seen in options of 'count',  so you can try it.

**Comment by sushantdhiman** [comment]
This issue is possibly fixed by https://github.com/sequelize/sequelize/pull/9188

I request thread participants to verify this. If looks ok then bounty can be awarded to @jharting who submitted that PR

**Comment by Alexsey** [comment]
The code from the initial post is now fixed. If anything would go wrong with the fix - please write about it in the PR #9188

**Comment by pbrink231** [comment]
referencing my fix here that was more a temporary solution to close that issue.  I am still having the issue.
#9563 
I am currently on v4.37.10

**Comment by radoslavpetranov** [comment]
I am facing the same issue. I took a quick look at the sequelize code and it seems to me the easiest way to allow us to set a limit on the main query instead of the inner subquery is just an extra option, say `isGlobalLimit: boolean`.

If you take a look here

https://github.com/sequelize/sequelize/blob/master/lib/dialects/abstract/query-generator.js#L1329

notice how if `subquery` is `true` (which is the case when we have associations) we add the limit to the `subQueryItems` and if it's false, we add it to `mainQueryItem`.

The easiest way to resolve this problem seems to just change that check to something like

```
if (subQuery && !options.isGlobalLimit) {
    subQueryItems.push(limitOrder);
} else {
    mainQueryItems.push(limitOrder);
}
```

so that if the user added `isGlobalLimit: true` to their options, the limit would still get applied to the main query because that's the only possible way you can get pagination working right with `sequelize` if you have any non-trivial filtering and sorting conditions.

**Comment by kimobrian** [comment]
My solution was to use a WITH operator on the main/parent model before the joins. I have a model called Board which stores bulletin board posts and a post can have a reactions(emoji reaction). I was getting less results so I ended up using a query that looked like this:

```sql

**Comment by iszlailorand** [comment]
If I understand well, your limit and offset is broken by the join, I think you can use group by `Events.id` and you will get a good result, but instead of count you will get an array of counts and the real count is the length of the array. something like this: 

` { 
  count: [
    { count: '3' },
    { count: '1' },
    { count: '1' }
  ],
  rows: [ 
    {
      dataValues: [Object],
      Tags: [Array]
    }, 
    {
      dataValues: [Object],
      Tags: [Array]
    }, 
    {
      dataValues: [Object],
      Tags: [Array]
    }
  ]
}`

**Comment by JamesMGreene** [comment]
There is a workaround in my issue that may be useful: https://github.com/sequelize/sequelize/issues/10557#issuecomment-481399247

**Comment by yashdabi** [comment]
https://github.com/sequelize/sequelize/issues/9869#issuecomment-510393362

**Comment by BartusZak** [comment]
In my scenario adding ` subQuery: false` helped. 
That should be documented somehow coz I spent 6h looking for a issue...

**Comment by radoslavpetranov** [comment]
Yeah for the record adding `subQuery: false` resolved my problem as well.

**Comment by vishavnokhwal** [comment]
**Still an issue consider I have 3 tables Contact, Company, Individual**

```
class Contact extends Sequelize.Model {
  static init(sequelize, DataTypes) {
    return super.init(
      {
        contactType: {
          type: DataTypes.STRING,
          allowNull: false,
        }
      },
      { sequelize }
    );
  }
  static associate(models){
    this.hasOne(models.Company);
    this.hasMany(models.Individual);
  }
}


class Company extends Sequelize.Model {
  static init(sequelize, DataTypes) {
    return super.init(
      {
        name: {
          type: DataTypes.STRING
          },
        compType: {
          type: DataTypes.STRING
        },
        affType: {
          type: DataTypes.STRING
        },
        lsNo: {
          type: DataTypes.STRING
        }
      },
      { sequelize }
    );
  }
  static associate(models){
    this.belongsTo(models.Contact);
  }
}


class Individual extends Sequelize.Model {
  static init(sequelize, DataTypes) {
    return super.init(
      {
        firstName: {
          type: DataTypes.STRING
          }
      },
      { sequelize }
    );
  }
  static associate(models){
    this.belongsTo(models.Contact);
  }
}
```
**and this is my code** 


```
const results= await Contact.findAndCountAll({
  where:{
    [Op.and]:[
    {
      contactType:{
      [Op.iLike]:{
        [Op.any]:[
        "abc",
        "def"
        ]
      }
    },
    },
    {
      [Op.or]:[
      sequelize.where(sequelize.fn('lower',sequelize.cast(sequelize.col('Contact.name'), 'TEXT')),{ [Op.like]: `%as%` }),
      sequelize.where(sequelize.fn('lower',sequelize.cast(sequelize.col('Company.compType'), 'TEXT')),{ [Op.like]: `%as%` }),
      sequelize.where(sequelize.fn('lower',sequelize.cast(sequelize.col('Company.lsNo'), 'TEXT')),{ [Op.like]: `%as%` }),
      sequelize.where(sequelize.fn('lower',sequelize.cast(sequelize.col('Company.affType'), 'TEXT')),{ [Op.like]: `%as%` })
      sequelize.where(sequelize.fn('lower',sequelize.cast(sequelize.col('Individual.firstName'), 'TEXT')),{ [Op.like]: `%as%` })
      ]
    }
    ]
  },
col:['id']
limit:10,
offset:0,
include:[
{ 
  model:Company,
  attributes:['id','name','compType','affType','lsNo'],
  required:true,
  where:{
    affType:{
      [Op.iLike]:{
        [Op.any]:['abc','def']
      }
    }
  }
},
{
  model:Individual,
  attributes:['id','firstName']
}
],
order:[[
'Company',
'name',
'DESC'
]]
});
```
**On execution of above code I am getting this error**
_missing FROM-clause entry for table "Individual"_

**Raw Query** 

_SELECT          "Contact".*, 
                "Individuals"."id"        AS "Individuals.id", 
                "Individuals"."firstName" AS "Individuals.firstName" 
FROM            ( 
                           SELECT     "Contact"."contactType", 
                                      "Contact"."id", 
                                      "Contact"."createdAt", 
                                      "Contact"."updatedAt", 
                                      "Company"."id"            AS "Company.id",
                                      "Company"."name"          AS "Company.name",
                                      "Company"."compType"   AS "Company.compType",
                                      "Company"."affType" AS "Company.affType",
                                      "Company"."lsNo"     AS "Company.lsNo"
                           FROM       "Contacts"                 AS "Contact" 
                           INNER JOIN "Companies"         AS "Company"
                           ON         "Contact"."id" = "Company"."ContactId"
                           AND        "Company"."affType" ilike ANY (array['abc','def'])
                           WHERE      ( 
                                                 "Contact"."contactType" ilike ANY (array['abc','def'])
                                      AND        ( 
                                                            lower(cast("Company"."name" AS text)) LIKE '%as%'
                                                 OR         lower(cast("Company"."compType" AS text)) LIKE '%as%'
                                                 OR         lower(cast("Company"."lsNo" AS text)) LIKE '%as%'
                                                 OR         lower(cast("Company"."affType" AS text)) LIKE '%as%'
                                                 OR         lower(cast("Individuals"."firstName" AS text)) LIKE '%as%'))
                           ORDER BY   "Contact"."Company" "name" DESC limit 10 offset 0) AS "Contact"
LEFT OUTER JOIN "los"."Individuals"                                              AS "Individuals"
ON              "Contact"."id" = "Individuals"."ContactId" 
ORDER BY        "Contact"."Company""name" DESC;_

**On adding** `subQuery=false`  **issue is resolved but limit is being applied on Individuals not on Contact**

**Comment by Alexsey** [comment]
@vishavnokhwal you should better create a new issue with the bug report if you expect it to be processed

**Comment by mopcweb** [comment]
After about a week of hell found acceptable workaround for my case. Believe it would be helpful as found a lot of unanswered topics/issues on github.

__TL;DR; actual solution is at the end of post, just the last piece of code.__

The main idea is that Sequelize builds correct SQL query, but when having left joins we produce carthesian product, so there will be a lot of rows as query result.

Example: A and B tables. Many to many relation. If we want to get all A joined with B we will receive A * B rows, so there will be a lot of rows for each record from A with different values from B.

```sql
CREATE TABLE IF NOT EXISTS a (
	id INTEGER PRIMARY KEY NOT NULL,
	title VARCHAR
)

CREATE TABLE IF NOT EXISTS b (
	id INTEGER PRIMARY KEY NOT NULL,
	age INTEGER
)

CREATE TABLE IF NOT EXISTS ab (
	id INTEGER PRIMARY KEY NOT NULL,
	aid INTEGER,
	bid INTEGER
)

SELECT *
FROM a
LEFT JOIN (ab JOIN b ON b.id = ab.bid) ON a.id = ab.aid
```

In sequelize syntax:

```ts
class A extends Model {}
A.init({
	id: {
      type: Sequelize.INTEGER,
      autoIncrement: true,
	  primaryKey: true,
	},
	title: {
      type: Sequelize.STRING,
	},
});

class B extends Model {}
B.init({
	id: {
	  type: Sequelize.INTEGER,
      autoIncrement: true,
	  primaryKey: true,
	},
	age: {
      type: Sequelize.INTEGER,
	},
});

A.belongsToMany(B, { foreignKey: ‘aid’, otherKey: ‘bid’, as: ‘ab’ });
B.belongsToMany(A, { foreignKey: ‘bid’, otherKey: ‘aid’, as: ‘ab’ });

A.findAll({
	distinct: true,
	include: [{ association: ‘ab’ }],
})
```

Everything works ok.

So, imagine i want to receive 10 records from A with mapped to them records from B.
When we put LIMIT 10 on this query, Sequelize build correct query but LIMIT is applied to whole query and as result we receive only 10 rows , where all of them could be for only one record from A. Example:

```ts
A.findAll({
	distinct: true,
	include: [{ association: ‘ab’ }],
	limit: 10,
})
```

Which will be converted into:

```sql
SELECT *
FROM a
LEFT JOIN (ab JOIN b ON b.id = ab.bid) ON a.id = ab.aid
LIMIT 10

id  |  title    |   id  |  aid  |  bid  |  id   |  age
--- |  -------- | ----- | ----- | ----- | ----- | -----
1	|	first	| 	1	|	1	|	1   |	1   |	1
1	|	first	| 	2	|	1	|	2   |	2   |	2
1	|	first	| 	3	|	1	|	3   |	3   |	3
1	|	first	| 	4	|	1	|	4   |	4   |	4
1	|	first	| 	5	|   1	|	5   |	5   |	5
2	|	second	| 	6	|	2	|	5   |	5   |	5
2	|	second	| 	7	|	2	|	4   |	4   |	4
2	|	second	| 	8	|	2	|	3   |	3   |	3
2	|	second	| 	9	|	2	|	2   |	2   |	2
2	|	second	| 	10	|	2	|	1   |	1   |	1
```

After output is received, Seruqlize as ORM will make data mapping and over query result in code will be:

```ts
[
 {
  id: 1,
  title: 'first',
  ab: [
   { id: 1, age:1 },
   { id: 2, age:2 },
   { id: 3, age:3 },
   { id: 4, age:4 },
   { id: 5, age:5 },
  ],
 },
  {
  id: 2,
  title: 'second',
  ab: [
   { id: 5, age:5 },
   { id: 4, age:4 },
   { id: 3, age:3 },
   { id: 2, age:2 },
   { id: 1, age:1 },
  ],
 }
]
```

Obviously NOT what we wanted. I wanted to receive 10 records for A, but received just 2, while i know that there are more in database.

So we have correct SQL query but still received incorrect result. 

Ok, i had some ideas but the easiest and most logical is:
1. Make first request with joins, and group results by source table (table on which we are making query and to which making joins) 'id'  property. Seems easy..... 

	To make so we need to provide 'group' property to Sequelize query options. Here we have some problems. First - Sequelize makes aliases for each table while generating SQL query. Second - Sequelize puts all columns from JOINED table into SELECT statement of its query and passing __'attributes' = []__ won't help. In both cases we'll receive SQL error.

	To solve first we need to convert Model.tableName to singluar form of this word (this logic is based on Sequelize). Just use [pluralize.singular()](https://www.npmjs.com/package/pluralize#usage). Then compose correct property to GROUP BY:
	```ts
	const tableAlias = pluralize.singular('Industries') // Industry

    {
     ...,
     group: [`${tableAlias}.id`]
	}
	```
	
	To solve second (it was the hardest and the most ... undocumented). We need to use undocumented property 'includeIgnoreAttributes' = false. This will remove all columns from SELECT statement unless we specify some manually. We should manually specify attributes = ['id'] on root query.

2. Now we will receive correctly output with only necessary resources ids. Then we need to compose seconf query WITHOUT limit and offset, but specify additional 'where' clause: 
```ts
{
 ...,
 where: {
  ...,
  id: Sequelize.Op.in: [array of ids],
 }
}
```
3. With query about we can produce correct query with LEFT JOINS.

__Solution__
Method receives model and original query as arguments and returns correct query + additionally total amount of records in DB for pagination. It also correctly parse query order to provide ability to order by fields from joined tables:

```ts
/**
   *  Workaround for Sequelize illogical behavior when quering with LEFT JOINS and having LIMIT / OFFSET
   *
   *  Here we group by 'id' prop of main (source) model, abd using undocumented 'includeIgnoreAttributes'
   *  Sequelize prop (it is used in its static count() method) in order to get correct SQL request
   *  Witout usage of 'includeIgnoreAttributes' there are a lot of extra invalid columns in SELECT statement
   *
   *  Incorrect example without 'includeIgnoreAttributes'. Here we will get correct SQL query
   *  BUT useless according to business logic:
   *
   *  SELECT "Media"."id", "Solutions->MediaSolutions"."mediaId", "Industries->MediaIndustries"."mediaId",...,
   *  FROM "Medias" AS "Media"
   *  LEFT JOIN ...
   *  WHERE ...
   *  GROUP BY "Media"."id"
   *  ORDER BY ...
   *  LIMIT ...
   *  OFFSET ...
   *
   *  Correct example with 'includeIgnoreAttributes':
   *
   *  SELECT "Media"."id"
   *  FROM "Medias" AS "Media"
   *  LEFT JOIN ...
   *  WHERE ...
   *  GROUP BY "Media"."id"
   *  ORDER BY ...
   *  LIMIT ...
   *  OFFSET ...
   *
   *  @param model - Source model (necessary for getting its tableName for GROUP BY option)
   *  @param query - Parsed and ready to use query object
   */
  private async fixSequeliseQueryWithLeftJoins<C extends Model>(
    model: ModelCtor<C>, query: FindAndCountOptions,
  ): IMsgPromise<{ query: FindAndCountOptions; total?: number }> {
    const fixedQuery: FindAndCountOptions = { ...query };

    // If there is only Tenant data joined -> return original query
    if (query.include && query.include.length === 1 && (query.include[0] as IncludeOptions).model === Tenant) {
      return msg.ok({ query: fixedQuery });
    }

    // Here we need to put it to singular form,
    // because Sequelize gets singular form for models AS aliases in SQL query
    const modelAlias = singular(model.tableName);

    const firstQuery = {
      ...fixedQuery,
      group: [`${modelAlias}.id`],
      attributes: ['id'],
      raw: true,
      includeIgnoreAttributes: false,
      logging: true,
    };

    // Ordering by joined table column - when ordering by joined data need to add it into the group
    if (Array.isArray(firstQuery.order)) {
      firstQuery.order.forEach((item) => {
        if ((item as GenericObject).length === 2) {
          firstQuery.group.push(`${modelAlias}.${(item as GenericObject)[0]}`);
        } else if ((item as GenericObject).length === 3) {
          firstQuery.group.push(`${(item as GenericObject)[0]}.${(item as GenericObject)[1]}`);
        }
      });
    }

    return model.findAndCountAll<C>(firstQuery)
      .then((ids) => {
        if (ids && ids.rows && ids.rows.length) {
          fixedQuery.where = {
            ...fixedQuery.where,
            id: {
              [Op.in]: ids.rows.map((item: GenericObject) => item.id),
            },
          };
          delete fixedQuery.limit;
          delete fixedQuery.offset;
        }

        /* eslint-disable-next-line */
        const total = (ids.count as any).length || ids.count;

        return msg.ok({ query: fixedQuery, total });
      })
      .catch((err) => this.createCustomError(err));
  }
```

**Comment by monokai-kirov** [comment]
I've created the package where have fixed this problem. All magic is in defining correct include prop - required: true|false

[https://github.com/monokai-kirov/nestjs-crud-utils/blob/main/src/crud/services/entity.service.ts#L219](https://github.com/monokai-kirov/nestjs-crud-utils/blob/main/src/crud/services/entity.service.ts#L219)
[https://github.com/monokai-kirov/nestjs-crud-utils/blob/main/src/crud/services/correction.service.ts#L8](https://github.com/monokai-kirov/nestjs-crud-utils/blob/main/src/crud/services/correction.service.ts#L8)
[https://github.com/monokai-kirov/nestjs-crud-utils/blob/main/src/crud/services/correction.service.ts#L164](https://github.com/monokai-kirov/nestjs-crud-utils/blob/main/src/crud/services/correction.service.ts#L164)

**Comment by phil714** [comment]
This is still a problem in sequelize v6 and v7, any updates on this issue ?

**Comment by ephys** [comment]
Is this the same issue as https://github.com/sequelize/sequelize/issues/4146 ?

**Comment by pyrozhok** [comment]
> This is still a problem in sequelize v6 and v7, any updates on this issue ?

I think this issue has been fixed in v7.  The problem was with count using findAndCountAll with includes when I tried set **where** clause.

I added `required: true` to the nested include according to the [documentation](https://sequelize.org/v7/manual/eager-loading.html) (check section **Using findAndCountAll with includes**)

`RouteView.findAndCountAll({
    limit,
    offset,
    attributes: [
      "id",
      "mainImage",
      "title",
      "duration",
      "length",
      "ascent",
      "createdAt",
      "placesCount",
    ],
    include: [
      {
        model: Place,
        required: true,
        attributes: ["id", "title", "mainImage", "latitude", "longitude"],
        through: {
          attributes: [],
        },
        include: [
          {
            model: Tag,
            attributes: ["id", "name"],
            through: {
              attributes: [],
            },
            where: tagConditions,
          },
        ],
      },
      {
        model: DifficultyCategory,
        attributes: ["id", "name"],
        where: difficultyConditions,
      },
      {
        model: District,
        attributes: ["id", "name"],
        where: districtConditions,
      },
    ],
    where: conditions,
    order: [["createdAt", "DESC"]],
  })
    .then(...)
    .catch(...);
    });
};`

sequelize 7.0.0-alpha.10

**Comment by Tapendra-Nickelfox** [comment]
I am still facing the same issue , I have used the `findAndCountAll` method which returns the correct count but the wrong numbers of row data. I passed the limit for 10 rows but it returns only 4 row

```
const users=await A.findAndCountAll({
        include:[
            {model:B,attributes:['id', 'name'] },
            {model:C,attributes:['id', 'name']},
            {model: D,as:'Area', attributes:['id', 'name'],
                through: {attributes: ['id'],
                }
            }
        ],
        where:whereCondition,
        order:[sortOrder],
        distinct: true,
        subQuery: false,
        offset: 0, limit: 10,
      })
```

**Comment by Tapendrakmr** [comment]
I am still facing the same issue with sequelize v"^6.26.0", I have used the findAndCountAll method which returns the correct count but the wrong numbers of row data. I passed the limit for 10 rows but it returns only 4 row

```
const users=await A.findAndCountAll({
        include:[
            {model:B,attributes:['id', 'name'] },
            {model:C,attributes:['id', 'name']},
            {model: D,as:'Area', attributes:['id', 'name'],
                through: {attributes: ['id'],
                }
            }
        ],
        where:whereCondition,
        order:[sortOrder],
        distinct: true,
        subQuery: false,
        offset: 0, limit: 10,
      })
```

**Comment by Tapendra-Nickelfox** [comment]
> Is this the same issue as #9940?

Yes

**Comment by Tapendrakmr** [comment]
> Is this the same issue as #9940?

yes

**Comment by taylanyildiz** [comment]
#9940 Same Issue, 

```js
Job.belongstoMany(
    TechnicianUser,{
        as:'technicians',
        through: TechnicianJob,
        onDelete:'',
        onUpdate:'',
});

TechnicianUser.belongsToMany(
    Job,{
        as:'jobs',
        through: TechnicianJob,
        onDelete:...,
        onUpdate:...,
});

/// Find jobs
Job.findCountAll({
    limit:limit && parseInt(limit),
    offset:offset && parseInt(limit),
    distinct:true,
    col:'id',
    subquery:false,
    where:{
        '$technicians.first_name$':{[Op.subString]:keyword},
    },
    include:[
        {
            model:TechnicianUser,
            as:'technicians',
            through:{
                ....
            }
        }
    ]
});

```

-> `Expected` result 
-      count:6,
        rows:[
            {...},
            {...},
            {...},
            {...},
            {...},
        ]

-> `Actual` result 
-      count:6,
        rows:[
            {...},
            {...},
            {...},
            {...},
        ]

Some fileds missing but `count` same
