### ISSUE TITLE
Include with where and order on aliased column creates incorrect query

### ISSUE THREAD

**Issue by kingjerod** [sequelize/sequelize#8100]
## What you are doing?

Getting latest row by `teamId`, includes an association, and sorting on a column `created_at` with an alias of `createdAt`. 
```js
const Order = sequelize.define('orders', {
  id: {type: Sequelize.INTEGER, primaryKey: true, autoIncrement: true},
  customerId: {type: Sequelize.INTEGER, field: "customer_id"},
  product: {type: Sequelize.STRING},
}, {timestamps: false});
const Customer = sequelize.define('customers', {
  id: {type: Sequelize.INTEGER, primaryKey: true, autoIncrement: true},
  teamId: {type: Sequelize.INTEGER, field: "team_id"},
  createdAt: {type: Sequelize.DATEONLY, field: "created_at"},
}, {timestamps: false});
Customer.hasMany(Order, {foreignKey: "customerId"});
const customer = await Customer.findOne({where: {teamId: 5}, include: [Order], order: [["createdAt"]]});
```

## What do you expect to happen?
I expect it to generate a query to get the latest customer with team_id = 5, including all their orders. 

## What is actually happening?
Sequelize is generating an invalid query. The inner query aliased the `created_at` column to `createdAt` correctly, so it does not exist in the outer query to order by. This causes the error `column customers.created_at does not exist`.

```sql
SELECT
	"customers".*, "orders"."id" AS "orders.id",
	"orders"."customer_id" AS "orders.customerId",
	"orders"."product" AS "orders.product"
FROM
	(
		SELECT
			"customers"."id",
			"customers"."team_id" AS "teamId",
			"customers"."created_at" AS "createdAt"
		FROM
			"customers" AS "customers"
		WHERE
			"customers"."team_id" = 5
		ORDER BY
			"customers"."created_at"
		LIMIT 1
	) AS "customers"
LEFT OUTER JOIN "orders" AS "orders" ON "customers"."id" = "orders"."customer_id"
ORDER BY
	"customers"."created_at";
```

Dialect: postgres
Database version: 9.6.2
Sequelize version: 4.4.3

**Comment by Chapurin** [comment]
Sequelize ORDER in subquery and main query this problem for me to

**Comment by Chapurin** [comment]
The solution for me is to roll back to version v3.24.3 and use order as plain string (not as an array value) ((

**Comment by gc1508** [comment]
GROUP BY also causes issues as far as I can tell.

**Comment by hiradimir** [comment]
I have same issue.
I can not find workaround

**Comment by kingjerod** [comment]
This is still an issue.

**Comment by aprilmintacpineda** [comment]
https://github.com/sequelize/sequelize/issues/8802
https://github.com/sequelize/sequelize/issues/9095
https://github.com/sequelize/sequelize/issues/8602

**Comment by jharting** [comment]
@kingjerod this should be fixed with https://github.com/sequelize/sequelize/pull/9188
Can you verify?

**Comment by faq885** [comment]
i am still having issues with this...

**Comment by Exilz** [comment]
I still cannot fix this problem unless I set `subQuery: false` in the `fetchAll` method options.

**Comment by aristov** [comment]
`subQuery: false` helps.
