### ISSUE TITLE
afterUpsert hook should receive the instance (in the same way as afterCreate, afterUpdate, afterDelete)

### ISSUE THREAD

**Issue by iamjochem** [sequelize/sequelize#8531]
## What are you doing?
I'm performing a `Model.upsert()` 

## What do you expect to happen?
I expect the "afterUpsert" hook to receive a reference to the DOA instance (just like the "afterCreate", "afterUpdate", "afterDelete" hooks). I would like this for auditing purposes (I log the details of all my DB mutations).

## What is actually happening?
the "afterUpsert" hook receives 2 parameters, the first is a boolean stating whether the DB was mutated or not, the second being the `options` object relevant to the original call. ("afterCreate", "afterUpdate", "afterDelete" hooks receive the DAO instance as their first argument and the `options` object as their second argument).

I believe that there is no need to call the "afterUpsert" hook if no DB mutation took place (this is a matter for discussion) and should receive the instance (it is available in the context that the hook is called) instead, alternatively it should receive 3 arguments (`<Object>instance, <Boolean>result, <Object>options`) ... either way it is a breaking change.

I have a branch with such a change here:

https://github.com/OOShoppingnl/sequelize/tree/feature/upsertHooksCalledWithInstance

in that branch I opted for 3 arguments, in the following order `<Boolean>result, <Object>instance, <Object>options` ... I figured keeping the `result` argument in first place would be least likely to cause breakage in practice.

the changes in my branch probably breaking something (I haven't run the test suite on it) but it does work in my production code ... anyway it might serve as a starting point for discussion.

__Dialect:__ mysql
__Dialect version:__ 2
__Database version:__ 5.7.18
__Sequelize version:__ master
__Tested with master branch:__ N/A

**Comment by tybro0103** [comment]
+1

**Comment by sushantdhiman** [comment]
Fixed by https://github.com/sequelize/sequelize/pull/8924 , pass `returning: true` and hook will receive upserted instance. Only Postgres and MSSQL supports this

**Comment by aat2703** [comment]
This isn't fixed... MySQL is not supported... Whats the issue with implementing this for MySQL? Just returning true in afterUpsert is kind of useless...

**Comment by Sneyder2328** [comment]
+1, please implement this with Mysql

**Comment by papb** [comment]
The only dialect that has the `RETURNING *` syntax is postgres, as far as I know, so this isn't Sequelize's fault, it's the dialects fault... Do any of you propose a working single SQL query to perform this in non-postgres?

**Comment by ThomasEg** [comment]
> The only dialect that has the `RETURNING *` syntax is postgres, as far as I know, so this isn't Sequelize's fault, it's the dialects fault... Do any of you propose a working single SQL query to perform this in non-postgres?

Correct. It is not possible natively in MySQL. So implementing it in Sequelize would be difficult(impossible)... 

However, it is IMO a major issue during development and i think everyone "creates their own workaround" with more or less success. Maybe it should be considered to make either a "best practice" for how to solve this with Sequelize or maybe some sort of "high level" helper for this(e.g. UPDATE + SELECT wrapper). My guess is that it is "harder than it looks" due to things like locking, transactions etc...

**Comment by papb** [comment]
You're right, good idea. Can you please open a new issue describing your idea as a feature request? Something like "enable `returning` option on all dialects" which would be done via a wrapper for example
