### ISSUE TITLE
Issue to exclude attributes that use with getter

### ISSUE THREAD

**Issue by CherryChann** [sequelize/sequelize#9001]
## What are you doing?

My model is like that.
```js
startDate: {
            type: DataTypes.DATE,
            get: function () {
                return moment(this.getDataValue('startDate')).format('YYYY-MM-DD');
            }
        }
```

## What do you expect to happen?
I'd like to exclude these attributes for some functions like including this model with other model.Whenever i fetch this model the startDate is included although I specify what attributes to include.

## What is actually happening?
_But the output was bar!_
Whenever i fetch this model the startDate is included although I specify what attributes to include.
_Output, either JSON or SQL_
"project": {
                    "projectDate": "2018-02-06",
                    "endDate": "2018-02-06",
                    "id": 2,
                    "name": "Project Name"
                }

__Dialect:__ mysql 
__Dialect version: 5.7.19
__Database version: 
__Sequelize version: 4.32.1
__Tested with latest release:__ No (If yes, specify that version)

**Comment by dattran92** [comment]
I'm having the same issue.

**Comment by sushantdhiman** [comment]
Fixed in master

**Comment by gerardomaranan** [comment]
I'm still encountering this issue on 4.42.0, can anyone help?

**Comment by vivek-Havalad** [comment]
Still facing same issue is any workaround so that we can exclude this type of virtual attributes in findOne({})
and findAll({}) query

**Comment by ecdemis123** [comment]
I am also seeing this issue.

**Comment by santiagogarza** [comment]
Still an issue in Sequelize version 6.3.5: any attribute with a getter function is returned, regardless of whether it is included or excluded in the attributes list.
