### ISSUE TITLE
Duplicate column names for associations and misleading documentation

### ISSUE THREAD

**Issue by atomanyih** [sequelize/sequelize#9328]
## Summary

We ran into an issue recently where `sequelize` generates queries with duplicate column names that cause mysql to errors in subqueries. 
A similar issue documented here: https://github.com/sequelize/sequelize/issues/3035 allowed us to fix the issue by specifying the `foreignKey`. 
However this appears to be in conflict with the [documentation](http://docs.sequelizejs.com/manual/tutorial/associations.html#foreign-keys) which suggests that `foreignKey` is `camelCase` by default

**It seems like `sequelize` has mismatched casing assumptions: association definitions assume `camelCase` while the query builder assumes `UpperCamelCase`**

## Longer explanation

We have three models, `Basket`, `Apple`, `Farmer` with associations as defined below:

```js
Basket.belongsTo(models.Farmer)
Basket.hasMany(models.Apple)
```

```js
Farmer.hasMany(models.Basket)
```

If we `findAll`

```js
Basket.findAll()
```

It generates the following query. (note that `farmerId` is duplicated)

```sql
SELECT `id`,
       `farmerId`,
       `FarmerId`
FROM   `Baskets` AS `Basket`;
```

If we instead want only 10 `Baskets`, plus any `Apples` in each `Basket`:

```js
Basket.findAll({
  limit: 10,
  include: [
    {
      model: Apple
    }
  ]
})
```

It generates the following query with a subquery

```sql
SELECT `Basket`.*,
       `Apples`.`id`    AS `Apples.id`,
FROM   (SELECT `Basket`.`id`,
               `Basket`.`farmerId`,
               `Basket`.`FarmerId`
        FROM   `Baskets` AS `Basket`
        LIMIT  10) AS `Basket`
       LEFT OUTER JOIN `Apples` AS `Apples`
                    ON `Basket`.`id` =
`Apples`.`BasketId`;

```

Our duplicated columns are now in a subquery. When this query is run in mysql, it throws an error!

```
SequelizeDatabaseError: Duplicate column name 'FarmerId'
```

We can fix this by specifying the foreign key on our relationships:

```js
Basket.belongsTo(models.Farmer, { foreignKey: 'farmerId' })
Basket.hasMany(models.Apple)
```

```js
Farmer.hasMany(models.Basket, { foreignKey: 'farmerId' })
```

However, the [documentation](http://docs.sequelizejs.com/manual/tutorial/associations.html#foreign-keys) suggests that `foreignKey` should already be `camelCase` by default. It's not super clear to me why the query builder would assume `UpperCamelCase`. This seems like a bug.

## Info

__Dialect:__ mysql, (generates the same queries for sqlite, but doesn't cause an error)
__Dialect version:__ default?
__Database version:__ `mysqld  Ver 5.7.21 for osx10.12 on x86_64 (Homebrew)`
__Sequelize version:__ `4.17.0` and `5.0.0-beta.3`

**Comment by sushantdhiman** [comment]
`UpperCamelCase` attributes are generated because model name is defined with upper case like 

```js
const Basket = sequelize.define('Basket', { .... });
``` 

Well its up to discussion, @sequelize/orm what do you suggest here? Enforce proper camel case key even if model name is upper cased?

I think many user prefer PascalCase naming for model, but camel case for attributes name. It make sense to keep keys camelCased not PascalCased

**Comment by heisian** [comment]
I think the implication is that the foreign key column should assume that it is in camelCase even if the model is in PascalCase, which I think is a logical assumption.

**Comment by parkerdan** [comment]
Yeah...not the best bug to try and sort out.  I guess I will just be explicit in all model associations

**Comment by sangaman** [comment]
Same issue here, I was getting the `Duplicate column name` errors for PascalCase properties after adding several associations to existing models where I didn't explicitly specify `foreignKey` because it seemed like the default value was fine. The solution for me as well was to go and explicitly specify each `foreignKey` using camelCase.

**Comment by HansHammel** [comment]
still an issue

**Comment by imikemiller** [comment]
I am seeing this problem even when explicitly defining `foreignKey` using camelCase.

**Comment by broox** [comment]
i just ran into this duplicate column bug after updating from sequelize `4.44.4` to `5.21.5`.
the solution to explicitly define the foreignKey works, but it's kinda gross that you have to do that.

**Comment by SysOpsNet** [comment]
@broox thank you for your help, I just downgraded my Sequelize version to actually fix this issue. 
@sequelize you should fix this seriously...

**Comment by robertmarriott** [comment]
Yes, this really should be fixed and the naming conventions used in the documentation should be consistent. In some examples they're using pascal case; in other examples they're using camel case. Coming from ORMs like Laravel's Eloquent and .Net's Entity Framework, which are well documented and extremely reliable, I'm not feeling as confident with Sequelize. I like Node, but whenever I return to the npm ecosystem I always end up frustrated with the amount of inconsistencies, long-standing bugs and workarounds that JavaScript developers seem to just accept as normal. In this case, I generated my models using the sequelize cli tool with the same case used in the official documentation examples. But, when I ran sync() upon starting my app, I get the error above and am told I need to explicitly define my foreign keys (or I guess redefined all my columns as pascal case) when this should just work as per the examples. =/

**Comment by sasa6277** [comment]
thank u , i have this issue , it help me

**Comment by kingsleyramos** [comment]
I tried to downgrade to 4.44.4, currently on 5.21.3, also tried 6.3.3, I'm still having the same issue for all three versions

**Comment by afsaneGhafouri** [comment]
I am using version `5.18.4` and I have the same issue. 😞

**Comment by matias4205** [comment]
Every time I ran into this kind of problem, either I use one of these 2 options into the query config:
- subQuery: false
- distinct: true

**Comment by LeonxLJX** [comment]
I'd like to take this one.

Reading the issue, this looks like a documentation-clarity gap rather than a code defect: the current page doesn't give readers enough to self-diagnose, which is why it surfaces here as an issue instead of being answered by the docs.

Plan: locate the relevant section, confirm what the code actually does today (so the docs match behavior, not intent), tighten the wording, and scan neighboring pages for the same inconsistency — otherwise the fix just relocates the confusion.

One thing to confirm before writing: minimal correction scoped to this page, or also cross-link from related guides if the same gap shows up there?

(claiming via @LeonxLJX)
